### PR TITLE
bump softfork3 activation by about 2 weeks

### PR DESCRIPTION
**Pull request by arvidn**
since the 2.0 release has been slipping

### CODE REVIEW

**Review by wjblanke — DISMISSED** [review]
aok

**Comment by wjblanke** [comment]
i'm ok with this but we'd need to get everyone onboard before merging

**Comment by hoffmang9** [comment]
I have no security related objection - just want to make sure we update all the various docs around.

**Review by paninaro — APPROVED** [review]

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
