### PR TITLE
revert delayed pool config handling (#12795, #13154)

### PR DESCRIPTION
**Pull request by altendky**
- Revert "We did not await the async function (#13154)"
- Revert "add delayed pool config update feature (#12796)"

### CODE REVIEW

**Comment by emlowe** [comment]
This works in my testing pretty well, and seems a reasonable revert of the code.

I think this is a good plan for 1.7.0 - and then we can work on fixing the fix for another day with some better code, especially if we feel there might be some more dragons in there somewhere.

**Comment by emlowe** [comment]
I tested this and it seems solid. I create two plotnfts and set one to pool and one to self - I then at one time reversed that (well two commands with &&) - set the one to self and the other to pool.

All went through fine and everything in config is ok.
I'm testing a wallet resync to see what happen while we walk the chain, but I do expect the old behaviour that we tried to fix.

I'm pretty good with this

**Comment by emlowe** [comment]
Testing complete, syncing from 0 as expected in the wallet wrt config changes

**Review by emlowe — APPROVED** [review]

**Review by jack60612 — APPROVED** [review]
Looks good!

**Pull request merged**
