### PR TITLE
Use negative amount to indicate send in wallet get_transactions output

### PR DESCRIPTION
**Pull request by altendky**
Actual (redacted) example send:
```
Transaction <redacted>
Status: Confirmed
Amount: -0.001 xch
To address: <redacted>
Created at: <redacted>
```

Actual (redacted) example receive:
```
Transaction <redacted>
Status: Confirmed
Amount: 0.001 xch
To address: <redacted>
Created at: <redacted>
```

### CODE REVIEW

**Comment by emlowe** [comment]
I understand the goal here, but this doesn't read properly to me. You aren't sending negative amounts - to me, this is equally confusing, albeit in a different way.

**Comment by altendky** [comment]
Am I still thinking too alike a normal transaction list in a non-blockchain context?  Positive and negative are certainly normal differentiators.

Maybe `Amount sent:` and `Amount received:`?

**Comment by emlowe** [comment]
I like that better, not sure if others have comments.

Amount sent (withdrawal):
Amount received (deposit):

Might be too verbose though...

**Comment by altendky** [comment]
Just updated to use `sent`/`received` labeling.  Both provided below as reference.

`sent`/`received`
```
Transaction 4c87e92a025a59662142acb341d8282939e0f454977850650e1227f41d26ed76
Status: Confirmed
Amount received: 0.25 txch
To address: txch1x0k6apktwmwvtfuzzat4kkcwaf0waa0ap9x73wtaedskwkrfvzms2gw7rf
Created at: 2021-08-28 22:03:20

Transaction 0eace03f232f1e67e2cbcfd63efa5e277373645f0675067e9e3b8f0c1fda9729
Status: Confirmed
Amount received: 0.25 txch
To address: txch1x0k6apktwmwvtfuzzat4kkcwaf0waa0ap9x73wtaedskwkrfvzms2gw7rf
Created at: 2021-08-28 22:03:20

Transaction b7a63213532693596586a82f56a3d758f2f9f59947d70178524a85c396e18b5b
Status: Confirmed
Amount sent: 1 txch
To address: txch1vpfp0u65t63h7c8lp7jaulyu25cy9qqtnfr5muswjheyymgqj7lsml0zky
Created at: 2021-08-28 22:08:34
```

`1`/`-1`
```
Transaction 4c87e92a025a59662142acb341d8282939e0f454977850650e1227f41d26ed76
Status: Confirmed
Amount: 0.25 txch
To address: txch1x0k6apktwmwvtfuzzat4kkcwaf0waa0ap9x73wtaedskwkrfvzms2gw7rf
Created at: 2021-08-28 22:03:20

Transaction 0eace03f232f1e67e2cbcfd63efa5e277373645f0675067e9e3b8f0c1fda9729
Status: Confirmed
Amount: 0.25 txch
To address: txch1x0k6apktwmwvtfuzzat4kkcwaf0waa0ap9x73wtaedskwkrfvzms2gw7rf
Created at: 2021-08-28 22:03:20

Transaction b7a63213532693596586a82f56a3d758f2f9f59947d70178524a85c396e18b5b
Status: Confirmed
Amount: -1 txch
To address: txch1vpfp0u65t63h7c8lp7jaulyu25cy9qqtnfr5muswjheyymgqj7lsml0zky
Created at: 2021-08-28 22:08:34
```

**Review by emlowe — APPROVED** [review]
Looks good to me

**Pull request merged**
