### PR TITLE
Add points found 24h to CLI reporting

### PR DESCRIPTION
**Pull request by altendky**
The points_found_24h seems to include more data than that so first it
gets filtered down to the past 24 hours.  This additionally affects the
existing percent successful points 24 hours number.  Which is actually
the percent of partials successful, not points.  This could differ a bit
if the difficulty is changed during the relevant period.

Draft for:
- [x] Checking against the GUI when I get home later
- [x] Looking into the existing apparently wrong `points_found_24h` numbers
  - https://github.com/Chia-Network/chia-blockchain/pull/7611#pullrequestreview-710163459
  - So, I guess I'll leave this PR just using it as if it were correct and check if Mariano still wants to fix it or if I should take a look.
  - https://github.com/Chia-Network/chia-blockchain/pull/7906 submitted
- [x] Update this to not duplicate the 24-hour-stripping added in https://github.com/Chia-Network/chia-blockchain/pull/7906
- [ ] Will be totally wrong until https://github.com/Chia-Network/chia-blockchain/pull/7906 is merged.

### CODE REVIEW

**Comment by altendky** [comment]
Note that this also switches the points successful to be a ratio of points rather than a ratio of partials.  I believe this is in keeping with the GUI.

https://github.com/Chia-Network/chia-blockchain-gui/blob/3bbef783557fb1aab267f341cfe8f7b86b509c5e/src/util/getPercentPointsSuccessfull.ts
```ts
import { sumBy } from 'lodash';
import type Point from '../types/Point';

function sumPoints(points: Point[]): number {
  return sumBy(points, (point) => point[1]) ?? 0;
}

export default function getPercentPointsSuccessfull(
  pointsAcknowledged: Point[],
  pointsFound: Point[],
): number {
  const acknowledged = sumPoints(pointsAcknowledged);
  const found = sumPoints(pointsFound);

  if (!acknowledged || !found) {
    return 0;
  }

  return acknowledged / found;
}
```

**Comment by altendky** [comment]
Combined with #7906 (and a diagnostic check that the data does not exceed 24 hours) it at least matches the GUI at less than 24 hours.  We'll see tomorrow if it holds up afterwards.

image

**Review by mariano54 — APPROVED** [review]

**Comment by arvidn** [comment]
ideally there would be a test demonstrating the bug as well. Otherwise we could break this again in the future without knowing

**Comment by altendky** [comment]
Thanks for the feedback.  I'll take a look through the tests later and see where it would fit.

**Comment by altendky** [comment]
I added a quick test for the 24h age out over in https://github.com/Chia-Network/chia-blockchain/pull/7906.  As to the output and calculations added here, where would tests for that belong?  Did I overlook the CLI test files?  I know I'll need to get a feel for the testing expectations and such here.  I'm certainly happy to write more tests, just trying to figure out how to fit in.

**Pull request merged**
