### PR TITLE
remove one magic number from weight_proof

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]
Good one, that will speed things up a lot

**Comment by arvidn** [comment]
actually, `_num_processes` is still hard coded to `4` in this same file, so it's a small step in the right direction :)

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Comment by mariano54** [comment]
What if we do the same as in blockchain.py
```python
     cpu_count = multiprocessing.cpu_count()
        if cpu_count > 61:
            cpu_count = 61  # Windows Server 2016 has an issue https://bugs.python.org/issue26903
        num_workers = max(cpu_count - reserved_cores, 1)
        ```

**Comment by arvidn** [comment]
I'd have to defer to @Yostra . This code came in with merging the new wallet code

**Pull request merged**
