### PR TITLE
New test files with CAT2 coins

### PR DESCRIPTION
**Pull request by emlowe**
Update run_block tests with new test blocks with CAT2 coins.
Remove xfail

### CODE REVIEW

**Review by jack60612 — DISMISSED** [review]
LGTM, sorry for not doing earlier!

**Review by altendky — CHANGES_REQUESTED** [review]
It looks like  `149988.json` is no longer used.

It looks like the block height is present inside the file.  Perhaps another unchanging name would be better and would allow future diffs to be relevant diffs?

**Comment by jack60612** [comment]
> It looks like `149988.json` is no longer used.
> 
> It looks like the block height is present inside the file. Perhaps another unchanging name would be better and would allow future diffs to be relevant diffs?

yeah thats what i recommended in an earlier pr.

**Comment by emlowe** [comment]
The program can also follow chains of blocks via `transactions_generator_ref_list` which lists additional blocks which are then found by using the `height as filename` scheme (eg. 466212 references 442734)

Notes, any diffs would really be very readable any way since this is using the `transactions_generator` which is just a long string of hex bytes.

**Review by altendky — APPROVED** [review]
Yeah, the file naming wasn't a big deal.  I just look for opportunities for diffs to have context.  Anyways, thanks for the explanation.

**Review by jack60612 — APPROVED** [review]
lgtm

**Review by wjblanke — APPROVED** [review]
thanks for these tests!

**Pull request merged**
