### PR TITLE
fix long sync cache

### PR DESCRIPTION
**Pull request by almogdepaz**
### Purpose:
only warmup the cache at the forkpoint

this pr pulls the cache warmup up to the sync_from_fork_point call and avoids calling the warmup on each batch

### Current Behavior:
we currently dont add blocks that we already know during reorg long sync that means we need to load these blocks each time from the db

### New Behavior:
add blocks that are already known so we dont have to warmup the cache each time, this is ok since we clean the cache up to BLOCKS_CACHE_SIZE after each batch

### Testing Notes:
since we use add_block in the tests for big reorg we need to manually warmup to the forkpoint before looping and adding each block

### CODE REVIEW

**Comment by almogdepaz** [comment]
coverage failing since we dont test reorg cases where fork point is not 0

**Review by arvidn — APPROVED** [review]
nice!

**Comment by arvidn** [comment]
the tests I made intended to reorg from a non-zero height, but I think there's a quantizing effect of reorging from the nearest epoch, or something like that. Is that right?
Would the tests need to for from a greater height?

**Comment by almogdepaz** [comment]
> the tests I made intended to reorg from a non-zero height, but I think there's a quantizing effect of reorging from the nearest epoch, or something like that. Is that right? Would the tests need to for from a greater height?

in long sync we find the fork point using only the sub_epoch_summary list (from the wp) we compare the sub_epoch_summary lists and we start syncing 2 sub epochs to avoid forking attacks in the last common sub epoch

i think your change to test-cache should be more then enough but if we changed all the forked chains in the test-cache we might be missing the forkpoint == 0 (unless theres an explicit test for that)

**Comment by pmaslana** [comment]
@arvidn @almogdepaz Are we good to remove the coverage-diff label?

**Comment by arvidn** [comment]
@pmaslana actually, I'm working on a patch against this PR to extend the test coverage

**Comment by arvidn** [comment]
extending the tests will take a bit longer than I thought. I think it's OK to land this first

**Pull request merged**
