### PR TITLE
CHIA-1626 Move some modules to the utils virtual project

### PR DESCRIPTION
**Pull request by AmineKhaldi**
### Purpose:

Mark some modules as belonging to the `utils` virtual project. This seems like a good temporary package to allow us to explore further actionable items to untangle our deps. For starters, it will allow us to extract `streamable` as a virtual project.

The end goal here is to separate `wallet` from `full_node`.

### Current Behavior:

The modules in question are currently marked as belonging to the `chia-blockchain` project.

### New Behavior:

They're now marked as belonging to the `utils` project.

### CODE REVIEW

**Review by Quexington — DISMISSED** [review]

**Comment by richardkiss** [comment]
As I've said in the past, I believe we'd be better off centralizing this virtual package information in a config file. It's just one more thing that new people looking at our code base will see and think "WTF is going on here?!?" Another advantage is it's a lot easier to keep local changes that reorg the code base by keeping a config file locally that you just don't bother checking in.

As for the content of the patch. I understand the name `utils` is intended to be temporary. I note that it doesn't match the (suffix of the) current name, which is `util`.

I don't completely understand what benefit this step does, or what goal it brings us closer to. Do we get new warnings when someone introduces new cyclic dependencies?

All this said, I don't want to continue to stand in the way so I won't hold up this PR.

**Comment by Quexington** [comment]
> I don't completely understand what benefit this step does, or what goal it brings us closer to. Do we get new warnings when someone introduces new cyclic dependencies?

Right now, there's a default assumption that all unmarked files are in the `chia-blockchain` package.  This makes separating a whole package out very difficult because it's very likely that something from this massive default depends on it and also that it depends on something from this massive default.  As I understand it, this change shears off a section of loosely related files that are not necessarily at the granularity we want, but which give us the ability to shear off more granular bits that we troublesome (I think Amine is eye-ing `streamable` first if I'm not mistaken.

**Comment by arvidn** [comment]
I agree 100% with richard. I think the end goal ought to be having packages either defined by a configuration file or simply directory structure. I don't think having that as an end-goal prevents us from making progress on organizing the repository though.

I think @AmineKhaldi should justify this change a bit better. "utils" vs. "util" is one thing. But I would also prefer some more confidence that this *will* help with something. Perhaps you know that this will allow separating out `Streamable`, or something else. Did you test it locally?

**Comment by AmineKhaldi** [comment]
>As for the content of the patch. I understand the name utils is intended to be temporary. I note that it doesn't match the (suffix of the) current name, which is util.

I got this name from @arvidn in https://gist.github.com/Quexington/9e154fcc6d1b9720583b2d59f3a07c4f and I don't mind changing it to whatever we like.

>I don't completely understand what benefit this step does, or what goal it brings us closer to. Do we get new warnings when someone introduces new cyclic dependencies?

I second @Quexington's explanation in https://github.com/Chia-Network/chia-blockchain/pull/18692#issuecomment-2415193959 and I also second/mention that defaulting to chia-blockchain virtual project for unmarked files is proving to be quite annoying when you attempt to extract a virtual project.

>I think @AmineKhaldi should justify this change a bit better. "utils" vs. "util" is one thing. But I would also prefer some more confidence that this will help with something. Perhaps you know that this will allow separating out Streamable, or something else. Did you test it locally?

I've updated the description to mention that this is a stepping stone towards extracting streamable as a virtual project.

**Comment by arvidn** [comment]
>  got this name from @arvidn in https://gist.github.com/Quexington/9e154fcc6d1b9720583b2d59f3a07c4f and I don't mind changing it to whatever we like.

why is this package meant to be temporary? What's the underlying reason to pull this out if you don't think it makes sense as separate?

I think you need to provide even more convincing reasons to pull this out if you don't think it makes sense to keep it.

> I second @Quexington's explanation in https://github.com/Chia-Network/chia-blockchain/pull/18692#issuecomment-2415193959 and I also second/mention that defaulting to chia-blockchain virtual project for unmarked files is proving to be quite annoying when you attempt to extract a virtual project.

You're probably trying to pull out the wrong project then. Pull out its dependencies first. only leaf-projects can (easily) be pulled out.

**Comment by AmineKhaldi** [comment]
>why is this package meant to be temporary? What's the underlying reason to pull this out if you don't think it makes sense as separate?

>I think you need to provide even more convincing reasons to pull this out if you don't think it makes sense to keep it.

This is a leaf-project, these utilities do not depend on anything else in `chia-blockchain`, and `streamable` depends on some of these utilities.

It's temporary in my mind because I have no idea if you want to keep it as a virtual project or not, in the end. I sent this as an exploratory PR to gather concrete actionable items on what we want to do to move forward with this. I have no final vision of what the virtual projects should be.

Having this leaf-project marked, if we accidentally introduce a cycle in any of its modules the CI will inform us accordingly which I thought is a step forward.

>You're probably trying to pull out the wrong project then. Pull out its dependencies first. only leaf-projects can (easily) be pulled out.

In the process of extracting a project, as you mark modules, the tool doesn't tell you exactly what's pulling what after that when it detects cycles, it only tells you that you're going back to chia-blockchain, so you have to somehow find out what exactly is getting you that behavior and that's what's quite annoying about it.

When you see `chia/wallet/wallet_weight_proof_handler.py (wallet) -> chia/util/ints.py (utils) -> (chia-blockchain) -> (wallet)` you have no idea what exactly in `chia/util/ints.py` is taking you back to `chia-blockchain`, and what exactly in `chia-blockchain` there is taking you back to `wallet`.

**Comment by AmineKhaldi** [comment]
In case it's not obvious, I updated the description to mention the end goal (separating `wallet` from `full_node`).

**Review by arvidn — APPROVED** [review]

**Pull request merged**
