### PR TITLE
Refactor how the Chialisp files are handled in chia-blockchain

### PR DESCRIPTION
**Pull request by Quexington**
Currently, we have every single piece of Chialisp located in chia/wallet/puzzles and we actually cannot move them out of there or create new ones elsewhere.  The idea of this refactor is to clean up and organize the puzzles in that directory without changing their compilation, and then move them to more sensible places in the project so we don't have one bloated folder of puzzles.

### CODE REVIEW

**Comment by Quexington** [comment]
Here's of summary of everything that changes, hopefully so that it's easier to review:

* File naming conventions have changed to `.clvm` (for plain CLVM in a file), `.clsp` (for Chialisp in a file), and `.clib` (for a file that is meant be `(include`d). The hex files will still be filename.whatever.hex.

* `load_clvm` works a bit differently now: By default it searches the directory from which it was called, but that can be overidden with another path or package to search in.  It also takes a new argument `search_paths` specifying where to search for files that are `(include`d.  It will search `chia.clvm.clibs` by default.

* As mentioned above, all of the general purpose clibs now live in the package`chia.clvm.clibs` which will be searched by default when loading a file.  A couple of new ones were added for treehashing and standard utility functions like `assert` or `is_in_list`.  All of the Chialisp files were refactored to include from them rather than have their own local copy.

* All of the Chialisp files were also refactored to conform loosely to some style decisions:
  * > 2 module arguments on separate lines below the `(mod`
  * Curried arguments are capitalized
  * Snake_case for everything
  * Consistent tabbing
  * `(if` branches have an extra tab to line up with the condition
  * A comment of `; main` above the main entry point in every file

* Lastly, most of the puzzle files were moved out of the `chia/wallet/puzzles` directory and into the directories that utilized them.  You can find a complete list of the new locations here: https://github.com/Chia-Network/chia-blockchain/blob/94c932dbdb32c08a29ae9d9c579e7ff44712b575/tests/clvm/test_clvm_compilation.py but here are some of note:
  * All of the singleton files now live in `chia/clvm/singletons/puzzles`
  * All of the generator and compression files now live in `chia/full_node/generator_puzzles

**Comment by richardkiss** [comment]
Another gotcha: the GUI distribution will likely need to know about all the `.clvm.hex` files. So once this is committed, we need to make corresponding changes to the full build, to ensure the `.hex` files are included.

**Comment by richardkiss** [comment]
At first, I thought 163 files changed must be a mistake. I completely underestimated the massiveness of this amazing piece of work. Wow!!

**Comment by Quexington** [comment]
> 
> 
> Another potential gotcha: the GUI distribution will likely need to know about all the `.clvm.hex` files. So once this is committed, we need to make corresponding changes to the full build, to ensure the `.hex` files are included.

@richardkiss I'm not entirely sure that the GUI cares.  Anything CLVM related is going to be asked for from the node I would presume.  And I made sure in the setup.py to include every potential file extension that should be used including both versions of .hex.

**Review by richardkiss — DISMISSED** [review]

**Comment by richardkiss** [comment]
This is the file that makes me suspicious that the installer doesn't just blindly take everything that's in the distribution (which would seem like the smart behaviour to me): https://github.com/Chia-Network/chia-blockchain/blob/main/chia/pyinstaller.spec

**Comment by Quexington** [comment]
> 
> 
> This is the file that makes me suspicious that the installer doesn't just blindly take everything that's in the distribution (which would seem like the smart behaviour to me): https://github.com/Chia-Network/chia-blockchain/blob/main/chia/pyinstaller.spec

Oh that's true, I've only ever tested by pip installing, not by using the pyinstaller built version.  Let me look into that.

**Pull request closed without merging**
