### PR TITLE
make synchronous mode in sqlite database connections configurable

### LINKED ISSUE #8715: [BUG] `pragma synchronous=OFF` causes database corruption on crash
Version 1.2.8/9 began using `pragma synchronous=OFF` every time a connection to the sqlite database is opened. This is **unsafe if the machine crashes** and will result in users having to resync the blockchain/wallet from scratch. This can cause users to lose days of farming time as they wait for the database to resync as well as waste network bandwidth and possibly waste data on their network plan with a data cap. The sqlite [page for pragmas](https://sqlite.org/pragma.html) details why this is unsafe (sorry, you'll have to search for `synchronous` as I can't link directly to it). Namely, it does not wait for the kernel to notify sqlite that data is persisted, only that it has been submitted to the kernel.

**To Reproduce**
1. launch any chia component that writes data to the sqlite database (full node, wallet), preferably something that needs to sync
2. wait for chia to begin syncing data
3. randomly unplug/hard shutdown the machine without waiting for chia to properly stop
4. restart chia, database may be reported as corrupted

As the above depends on the precise timing of when the machine was powered off/crashed relative to I/O submitted by sqlite, this may require several attempts to see a corrupted database.

**Expected behavior**
Database should not become corrupted if the machine crashes. Users should not have to resync the entire blockchain and their wallet if their machine crashes.

**Desktop**
Any machine that writes data to any sort of storage device

**Additional context**
While this doesn't directly explain the numerous database corruption issues seen by people recently (including some in #8694 as those were not caused by a computer crash), there's a good chance that either this, or this combined with some transaction management issue could cause database corruption if chia is stopped improperly.

The changelog for 1.2.8 indicates that this pragma change was added to improve disk performance. If faster transaction commits are desired, multiple operations should be batched into a single transaction instead of completely disabling the crash consistency mechanism of the database. Since sqlite is run in WAL mode, sqlite could be set to use `pragma synchronous=NORMAL` which the documentation seems to indicate would provide sufficient crash consistency while being faster than `pragma synchronous=FULL`

### PR DESCRIPTION
**Pull request by arvidn**
Default to enabling synchronous mode, leaving the door open for a more sophisticated heuristic in the future

### CODE REVIEW

**Review by jack60612 — DISMISSED** [review]
lgtm

**Review by xdustinface — DISMISSED** [review]
Looks good!

**Review by xdustinface — DISMISSED** [review]

**Review by emlowe — DISMISSED** [review]
looks good

**Review by xdustinface — APPROVED** [review]

**Review by jack60612 — APPROVED** [review]
lgtm

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
