### PR TITLE
Atari catch up merge - main 0ba838b7a8ea2b5410d438ac70295df699a30dae

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
I'll propose ignoring the LGTM issues here for a few reasons.  The `atari` branch hasn't been working on the gui and the submodule hash seems to match the master commit being merged.  I suspect that this reporting relates to the fixes done in https://github.com/Chia-Network/chia-blockchain/commit/ab74bd0d1cf6522b76f65dba97fb524ab32d6b44 and will hopefully resolve once they are in `atari` and whatever PRs against `atari` (and the `atari-main` CI trickery branch).  The Python bits of the LGTM complaints relate to the multi-plotter support which shouldn't have anything to do with `atari` and is often missed in the introducing PR because of how LGTM reports.

**Comment by altendky** [comment]
For reference on the need to rename the `announcements_to_consume` parameter to `coin_announcements_to_consume, see https://github.com/Chia-Network/chia-blockchain/commit/64e20308d9a40c18933ec095416042d6eb851a8d.

**Review by Quexington — APPROVED** [review]
CI is green and that's the most confidence I can have `:]`

**Review by emlowe — APPROVED** [review]
Looks good - all the parts I checked seemed correct.

**Pull request merged**
