### PR TITLE
Set long_description_content_type for a nicer PyPI page

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by mariano54** [comment]
LGTM

**Comment by hoffmang9** [comment]
I of course fixed this on all the sub repos and totally forgot about it for chia-blockchain. Huge thanks @altendky - will merge once the ci completes (mostly) succesfully.

**Comment by altendky** [comment]
Could add a `twine check` to CI as an extra guardrail.  Though I don't know what else that'll catch...  I should at least add that to my own though, I suppose.  `:]`

```bash
$ venv/bin/twine check dist/*
Checking dist/chia_blockchain-1.0b12-py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/chia-blockchain-1.0b12.tar.gz: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```

**Comment by hoffmang9** [comment]
I'd be happy if test pypi hadn't mysteriously stopped working during our release today...

**Pull request merged**
