### PR TITLE
Backend changes to support passphrase hints and additional GUI passphrase support

### PR DESCRIPTION
**Pull request by paninaro**
Trello issue: https://trello.com/c/P4SmvQVs/1373-final-ux-for-passphrase-encryption-feature

These changes complement the requested GUI changes to finalize keyring passphrase support. The ability to save the passphrase to the macOS Keychain or Windows Credential Manager was previously implemented for the CLI, but is now exposed to the GUI.

Additionally, a passphrase hint can now be set by the user. The GUI will display the hint (if set) in the passphrase dialog. The passphrase hint is stored in the clear in keyring.yaml and is set at the same time a passphrase change is made. CLI options have been added to manage the passphrase hint:

`$ chia passphrase hint display # Displays the passphrase hint`

`$ chia passphrase hint set "my deepest darkest secret" # Sets the passphrase hint`

`$ chia passphrase hint remove # Removes the passphrase hint`

`$ chia passphrase set --hint "some hint" # Sets the passphrase and hint`

### CODE REVIEW

**Review by jack60612 — DISMISSED** [review]
lgtm

**Comment by jack60612** [comment]
Why did that not work?

**Comment by jack60612** [comment]
@paninaro let me know when you get lgtm to shut up

**Comment by paninaro** [comment]
> Why did that not work?

Unfortunately LGTM will continue to complain, even after suppressing the warning, until the PR is merged: https://lgtm.com/help/lgtm/alert-suppression

"...if you suppress an alert in a pull request, LGTM will continue to report the related alert for as long as the pull request is open"

**Comment by jack60612** [comment]
> > Why did that not work?
> 
> Unfortunately LGTM will continue to complain, even after suppressing the warning, until the PR is merged: https://lgtm.com/help/lgtm/alert-suppression
> 
> "...if you suppress an alert in a pull request, LGTM will continue to report the related alert for as long as the pull request is open"

Ah let me just approve this again.

**Review by jack60612 — DISMISSED** [review]
lgtm

**Comment by paninaro** [comment]
> Jeff, are you aware of test failures like this one?
> 
> https://github.com/Chia-Network/chia-blockchain/pull/8799/checks?check_run_id=3862681531

Those test failures should have been addressed by https://github.com/Chia-Network/chia-blockchain/pull/8766 (merged into main). Is your branch up-to-date with main?

**Review by altendky — COMMENTED** [review]
In general, we seem to have a separation of `chia/cmds/x.py` and `chia/cmds/x_funcs.py`.  I'm not taking sides on having that or not at the moment, but this addition is lacking that separation.  That might be fine.

**Comment by paninaro** [comment]
> In general, we seem to have a separation of `chia/cmds/x.py` and `chia/cmds/x_funcs.py`. I'm not taking sides on having that or not at the moment, but this addition is lacking that separation. That might be fine.

Moved the implementations into `passphrase_funcs.py`

**Review by arvidn — COMMENTED** [review]
it seems to me that the 4 new functions in `passphrase_funcs.py` are redundant, and likely belong in the command line utility itself. They all seem to be tailored to only be usable in a command line utility.

(by redundant, I mean the extra layer of indirection is redundant, not the functionality itself. but it could just directly be part of the command line tool)

**Review by arvidn — APPROVED** [review]

**Pull request merged**
