### PR TITLE
Dl wallet store index fix

### PR DESCRIPTION
**Pull request by neurosis69**
- renamed the indexes according to #13304
- removed index `coin_id` as there is already an internal index for the PK: sqlite_autoindex_singleton_records_1
- removed index `inner_puzzle_hash` as I found no SQL query using it
- fixed wrong indexed column for index `confirmed_at_height`, indexed column was `root`
- removed index `id` as there is already an internal index for the PK: sqlite_autoindex_launchers_1
- added index `mirrors_launcher_id_index` as there is a query [here](https://github.com/Chia-Network/chia-blockchain/blob/98c44fdd15ea0f06948a393d237142c71bd9d532/chia/data_layer/dl_wallet_store.py#L303) which would benefit from it

### CODE REVIEW

**Comment by emlowe** [comment]
Close and reopen for new CI run

**Review by altendky — DISMISSED** [review]
Tracking here that I looked over this, but this PR isn't going in what with the unsigned commits.  We can create new signed commits in our own PR.

**Comment by neurosis69** [comment]
> Tracking here that I looked over this, but this PR isn't going in what with the unsigned commits. We can create new signed commits in our own PR.

signed my commits according to a guide from @wallentx

**Comment by wjblanke** [comment]
This will go in after branch

**Review by wjblanke — APPROVED** [review]
aok but for main after release branch

**Comment by altendky** [comment]
I'm going to draft this for now for clarity that it should not be merged yet.  I'll also kick CI for a fresh run.

**Pull request merged**
