### PR TITLE
Daemon hostname

### PR DESCRIPTION
**Pull request by snikch**
Take two at #373

### CODE REVIEW

**Comment by hoffmang9** [comment]
Adding the original opening comment back:

# What

This adds a separate configuration key for the daemon hostname. Currently it uses `self_hostname`.

# Why

At the moment it's assumed that the daemon runs on the same host as the rpc server when attempting to start the rpc server. This is prohibitive when attempting to run all the components separately in their own containers. Allowing the daemon to run on its own host allows all components to be distributed, such as in a docker setup. 

# How

This adds a new `daemon_hostname` field to the configuration that defaults to the `self_hostname` value both in the config and in the code (fallback). It should be a no-op for all existing installations.

**Comment by Yostra** [comment]
Daemon is used to launch/stop services, them being on remote machines breaks this. 
You can probably achieve desired network configuration by running services individually without a daemon. 

Can you explain what kind of setup you tried to achieve ?

**Comment by Yostra** [comment]
If you really want to have support for running daemon with remote services, the path would probably include running daemon on remote machine as well. 
Then have local daemon connect to the remote daemon and do service discovery / remote control. 
(client <-> local-daemon <-> remote-daemon <-> services)

Also, in order to make this secure we need SSL support for communication between daemons & ip whitelisting.

**Comment by snikch** [comment]
This was effectively the easiest way for me to get individual components running, as I effectively didn't want the daemon to run. I'm using docker / container for scheduling / process management, so I guess the daemon serves no purpose. I had plenty of issues with various components attempting to connect to the daemon and failing when they couldn't.

Would the alternative be to provide some sort of `connect_to_daemon` key in the configuration for each of the various services, like the `start_rpc_server` option?

My current setup at home is a docker swarm with a harvester running on each node, and a single full node and farmer running on the manager. I also use docker for scheduling plotters, which allows for zero downtime upgrades of the code used for plotting (I just update the image).

**Comment by Yostra** [comment]
Oh interesting, what was the failure mode? (probably something we should get fixed)

Yes, having config to connect/not connect to daemon and start/not-start the rpc server seems reasonable.

**Comment by snikch** [comment]
If they failed to connect to the daemon, they wouldn't start. It was a while back so I can't remember the specific details, but I got it in my head that I should get the daemon working rather than stop trying to connect to the daemon. I think I tried to starting the rpc server as a solution to this, but it would still attempt to connect to the daemon. I'm happy to implement something to avoid connecting to the daemon. I question whether there would be any affects with the rpc server if this were the case, e.g. receiving commands that should be forwarded to the daemon (or perhaps I'm inverting the relationship here somehow).

**Comment by Yostra** [comment]
If you start rpc server you'll still be able to make HTTP post requests to it, but you won't be able to do websocket ones. (they are routed via daemon) 
Also,  remember to change "self_hostname" config so that external client can connect to it.

**Comment by snikch** [comment]
Turns out this is a quick fix if I create a config option to disable the daemon and pass that through to the `connect_to_daemon` param in `start_rpc_server`. It feels like this could be some sort of `daemon_enabled` / `daemon_disabled` key at the root of the config like the other daemon parameters. Do you have a preference for this key name?

**Comment by Yostra** [comment]
Hi @snikch Sry, I somehow missed this.
No preference for key name, can you open a PR with your changes and option added to initial-config file?

**Pull request closed without merging**
