### PR TITLE
pass through max cost all the way down to where we execute the CLVM code

### PR DESCRIPTION
**Pull request by arvidn**
@richardkiss @Yostra I'm especially interested in if all the places where we *don't* enforce an upper limit on CLVM cost are safe.

If we need to enforce cost in those places, a `max_cost` parameter needs to be passed through a lot more paths.

### CODE REVIEW

**Comment by arvidn** [comment]
btw. I don't intend to land this as-is. I will wait for https://github.com/Chia-Network/chia-blockchain/pull/1948 to land and then rebase and retarget this to `main`.

**Review by richardkiss — DISMISSED** [review]
This looks very useful. The places where `INFINITY` is used should serve as a warning that the API behind it should be deprecated (like `additions`). Eventually, we should create an object that is a dictionary of condition types that returns a list of `(coin, condition)` pairs, and use *just* this object to figure out *everything*, and then have a method that returns this dictionary given a `SpendBundle` and one that returns it for a block.

**Comment by arvidn** [comment]
rebased onto main

**Review by richardkiss — APPROVED** [review]
Looks good! Definitely an improvement over what we have.

**Pull request merged**
