### PR TITLE
plotting|harvester|tests: Improve batch processing

### PR DESCRIPTION
**Pull request by xdustinface**
Let it only process `batch_size` files per `refresh_batch` call instead of all files.

### CODE REVIEW

**Comment by jack60612** [comment]
@xdustinface I appreciate what you do. Without you the chia code would be alot more spaghetti

I really appreciate it!

**Comment by xdustinface** [comment]
> I really appreciate it!

Cheers :beers: :slightly_smiling_face:

**Comment by xdustinface** [comment]
Okay, back to draft. Need to refactor some stuff in tests.

**Review by arvidn — COMMENTED** [review]
looks good to me. just some minor comments

**Review by arvidn — APPROVED** [review]

**Pull request merged**
