### PR TITLE
remove extra bt from as many tests as possible ( speed up tests)

### PR DESCRIPTION
**Pull request by jack60612**
max speed, 25% faster now

### CODE REVIEW

**Comment by jack60612** [comment]
Appears to be faster

**Comment by mariano54** [comment]
Can you provide some concrete numbers on the speed difference?

**Comment by jack60612** [comment]
> Can you provide some concrete numbers on the speed difference?

is there an easy way to benchmark it?

**Comment by jack60612** [comment]
> > Can you provide some concrete numbers on the speed difference?
> 
> is there an easy way to benchmark it? ( I am going to just time running all the tests without the change, then with)

ah, ill profile it

**Comment by mariano54** [comment]
You can compare the changed test files in this PR vs main for example, and post the difference

**Comment by jack60612** [comment]
This makes all of the tests run on my mac in 31 minutes, while main takes 42 minutes. that is a 10 MINUTE DECREASE!

**Review by mariano54 — APPROVED** [review]

**Comment by mariano54** [comment]
Let's merge @wallentx

**Comment by wallentx** [comment]
> Let's merge @wallentx

@Chia-Network/required-reviewers have been busy the past few days, so I'm trusting your suggestion (and I want to speed up tests)

**Pull request merged**
