### PR TITLE
simplify new peak timeout

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [ ] sync test

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]

**Comment by mariano54** [comment]
I will close https://github.com/Chia-Network/chia-blockchain/pull/10044 as this replaces it

**Comment by mariano54** [comment]
can we merge this @altendky ?

**Comment by altendky** [comment]
I've only synced to about 600k so far.  Things look good but I don't have the detailed logging in place to have full insight and catastrophic failures occurred in the 600k-900k range in the couple cases i had records to that point.  Also, there's no test.  I'm not sure if we can write a deterministic test or not, but I haven't tried as of yet.

**Comment by wjblanke** [comment]
hey kyle let me know when ur finished with your test sync

**Comment by altendky** [comment]
@wjblanke, that'll be a few days.  It's on the RPi where I was consistently reproducing the issue.

**Comment by mariano54** [comment]
I think it's good to go, if the sync test does well.

**Comment by wjblanke** [comment]
ill merge but let it run kyle. if there are problems we can revisit it

**Pull request merged**
