### PR TITLE
Block summaries of CAT1 offers in the RPC and CLI

### PR DESCRIPTION
**Pull request by Quexington**
This is a less invasive alternative to https://github.com/Chia-Network/chia-blockchain/pull/12618

### CODE REVIEW

**Review by jack60612 — DISMISSED** [review]
Works great, tested on CLI

**Comment by emlowe** [comment]
We need some test code that exercises this. I trust the existing CI runs would test that this doesn't break anything - but I think we need a CAT1 test to make sure this does what we want

**Review by emlowe — APPROVED** [review]
Looks good

**Comment by jack60612** [comment]
Missed the notification, reviewing now

**Review by jack60612 — APPROVED** [review]
Lgtm

**Pull request merged**
