### PR TITLE
bump soft-fork3 activation height

### PR DESCRIPTION
**Pull request by arvidn**
since release is slipping

### CODE REVIEW

**Review by emlowe — APPROVED** [review]

**Comment by emlowe** [comment]
Does this need to change in initial-config?

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Comment by wallentx** [comment]
> Does this need to change in initial-config?

https://github.com/Chia-Network/chia-blockchain/blob/a5a988c32098d8a3f56d4c284680f20aeed2fccb/chia/util/initial-config.yaml#L74-L78

These look like they are prob not right.

**Comment by arvidn** [comment]
the config file contains overrides for testnet. but testnet has already activated soft-fork3, so we can't change those.

**Comment by arvidn** [comment]
I think we have to accept the benchmark workflow an exception, since we don't have those runners back up yet

**Pull request merged**
