### PR TITLE
remove setting of SCM_VERSION in install-version.py

### PR DESCRIPTION
**Pull request by altendky**
This seems unused internally and I am not aware of any scenario where it would get inherited back out to other processes.

Extracted from https://github.com/Chia-Network/chia-blockchain/pull/11077.

### CODE REVIEW

**Comment by hoffmang9** [comment]
This is there to override a version in a CI failure by simply adding it to a workflow to override. Fine to remove it but important to record what it was doing.

**Comment by altendky** [comment]
I don't quite follow.  How would this environment variable have been exposed to anything else?  Did `installer-version.py` used to subprocess to other stuff so that they would inherit this variable?

**Comment by hoffmang9** [comment]
One could modify eg build-MacOS-installer.yml to add an env variable to the build step that would obtain installers with version 1.3.4 and not 1.3.5.dev01 in an instance where there was an installer build failure

**Comment by altendky** [comment]
Sure, but this is setting an env var, not reading it, with no apparent path out of this process which doesn't use it from what I can tell.  It does not subprocess nor would the variable be inherited back up to the parent process since that isn't how environment variables work.  This script is also mostly 'not importable' since it has a `-` in the name (you can, but only via contortions).  I don't see a practical way for this to be leveraged as a way to get access to the version.  Am I missing a path for the data to get used?

This is entirely a side note and not needed for anything else I'm working on so it isn't important for it to change.  I'm just trying to make sure I understand how leaving the code in place could be leveraged by anything.

**Comment by hoffmang9** [comment]
Yep, looking again it looks like it's some sort of now lost vestigial thing.

**Review by xdustinface — APPROVED** [review]

**Comment by wjblanke** [comment]
i think this was the byproduct of debugging SCM long long ago

**Pull request merged**
