### PR TITLE
correct wallet rpc api for get spendable coins with specified excluded coins

### PR DESCRIPTION
**Pull request by altendky**
### Purpose:

found while exploring more hinting with https://github.com/Chia-Network/chia_rs/pull/772

note that this is related to the older object field name that we back-compat support on the api end

### CODE REVIEW

**Review by Quexington — APPROVED** [review]

**Review by Quexington — CHANGES_REQUESTED** [review]
Wait sorry, does this work?  If `excluded_coins_input.values` is `dict[str, Any]` then `Coin.from_json_dict` isn't going to ever match it right?

**Comment by altendky** [comment]
It's not tested, I just know the hinting here.

https://github.com/Chia-Network/chia-blockchain/blob/e2c63db676dad321b8cf2a4e8b67b06f669773e3/chia/wallet/signer_protocol.py#L18-L23

Does the `@clvm_streamable` bit make `.from_json_dict()` not take the dict you would otherwise expect?

**Comment by altendky** [comment]
This situation was pointed out when I tried the now merged https://github.com/Chia-Network/chia_rs/pull/772 in blockchain.

**Review by Quexington — APPROVED** [review]
nvm I'm dumb

**Review by emlowe — APPROVED** [review]

**Pull request merged**
