### PR TITLE
Resolve v6 addresses

### PR DESCRIPTION
**Pull request by cross**
Replace calls to `socket.gethostbyname` to a new resolver method in `util/network.py` that uses a config pref to return IPv4 or IPv6 addresses appropriately.  Discussed in #8552

### CODE REVIEW

**Review by emlowe — CHANGES_REQUESTED** [review]

**Comment by emlowe** [comment]
It looks like the tests are failing
`introducer full_node_server       : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '::1', 'port': 21233}.`

The code seems to be using the ::1 IPv6 address for localhost, but perhaps the server is not listening properly for that.

**Comment by cross** [comment]
> It looks like the tests are failing `introducer full_node_server : ERROR Exception: <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '::1', 'port': 21233}.`
> 
> The code seems to be using the ::1 IPv6 address for localhost, but perhaps the server is not listening properly for that.

Thanks for that detail.  I've been wondering how my change could've been causing these issues, but now it's clear.

Let me know if you can confirm that the environment the tests are running in are listening IPv4-only, and can be changed.  And let me know if you have any more feedback on the PR as it is.

**Comment by hoffmang9** [comment]
https://github.com/actions/virtual-environments/issues/668

Certainly no third party IPv6 available on the runners. Lame...

**Comment by cross** [comment]
Okay.  And, I think this may also bring to light a concern I had about making "ipv6 preferred" the default.  There will be many people, sadly, who don't have IPv6 working and will get burned in the same way as the test runners.  This is among the reasons I wanted it to be in the on-disk config, to be easier to find and switch-flip.
I'll try to rearchitect the preference default into `get_host_addr` as @emlowe suggests, and [to my deep sadness] switch the default to false and see if the tests pass.

**Comment by cross** [comment]
> It's interesting however that the socket.getaddrinfo() call returns ::1 for localhost in this case - so the OS stack has IPv6 enabled?

Yes.  If you look at the ticket Gene referenced, you can see that the `ifconfig` output showed link local addresses on the interface, but no packets would route out.

**Comment by cross** [comment]
> I can, one option is you can try switching the default to false and see if the tests pass. Meanwhile I'll see what I can dig up.
> 
> I'm thinking one way to handle the default is to leverage Optional and None - so rather than specify the default in the various "get" calls, let the get return None, and then change get_host_addr is None is passed in that means True or False. One line then to switch the default.

I tried this.  Unfortunately, updating the calls to config.get() to not have a boolean default value and using:
```
def get_host_addr(host: Union[PeerInfo, str], prefer_ipv6: Optional[bool]) -> str:
```
causes the following errors from mypy:
```
chia/timelord/timelord_launcher.py:85: error: Argument 4 to "spawn_process" has incompatible type "Optional[Any]"; expected "bool"
chia/server/start_service.py:146: error: Argument 5 to "start_reconnect_task" has incompatible type "Optional[Any]"; expected "bool"
```
I suppose I could cause prefer_ipv6 to be typed as `Optional[Any]`, but that would be wrong, so is there a right way to do this?

**Comment by hoffmang9** [comment]
All modern OSes have ipv6 enabled even if it can't get to outside addresses.

**Comment by cross** [comment]
So, having "fixed" the code I added to always use IPv4, GitHub is okay with it.  *frown*.   But, this at least gives a config variable that people can use.
I'd really like for there to be a plan to eventually turn it on by default, or at least in some default cases, but with the test runners impaired the way they are, I'm not sure how we can plan to do that later.

**Comment by cross** [comment]
Sorry @emlowe I was already working on a change and pushed it before I saw your response.  I just plumed it into the core template, in a way that I suspect will affect all test environments.  And I see what you're saying, that resolving isn't necessarily our problem.  If this does anything at all though, I can say I've learned a little about the workflow system in chia-blockchain.  ;-)

**Comment by emlowe** [comment]
Same error - I'm starting to think maybe this is a problem is somewhere else.

I wonder if start_server in chia/server/server.py which calls 

```
   self.site = web.TCPSite(
            self.runner,
            port=self._port,
            shutdown_timeout=3,
            ssl_context=ssl_context,
        )
```
I think maybe this does not listen on both ipv4 and ipv6 when host=None?

**Comment by cross** [comment]
I could try that.  I'm thinking maybe I should completely delete that last commit from my branch, though, since I think it's not helpful, and it's a heck of a lot of changes that are of no value.  Let me know if you want me to tweak with the server TCPSite while those changes to the workflows are still in, otherwise I'll delete that commit before trying that test.

**Comment by cross** [comment]
> I wonder if start_server in chia/server/server.py which calls
> 
> ```
>    self.site = web.TCPSite
> ```
> 
> I think maybe this does not listen on both ipv4 and ipv6 when host=None?

According to the docs, it says:
```
host (str) – HOST to listen on, all interfaces if None (default).
```

So, it should be setting up an IPv4/IPv6 listener, but I could tell on my system when running test_daemon.py that it was binding only to 127.0.0.1, not even 0.0.0.0, so that's the wrong path I think.  And that wasn't working for me on main either, so I'm not running the test right I think.

**Review by emlowe — DISMISSED** [review]

**Comment by cross** [comment]
@emlowe  can you get anyone else you want to review this attached, and then we can get it merged in?  Thanks.

**Comment by emlowe** [comment]
I approved it, but we had some other more pressing issues, so it will likely wait until after the next release. It will get in though.

**Comment by cross** [comment]
The last test that failed failed to retrieve blocks from localhost, but I don't think my changes affect that flow.  Let me know, but I'm assuming that updating my branch didn't introduce this, but that it's a testing infra oddity.

**Comment by altendky** [comment]
I just kicked that workflow for you.

**Comment by wjblanke** [comment]
wanted to merge but conflicts need to be resolved. sorry its taken so long!

**Comment by cross** [comment]
I assume: `ERROR    WebSocket Error: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 62914560 exceeds limit 52428800'), extra=None)` isn't likely a defect with my changes.  Is that a failure the tests sometimes see?  Maybe can we kick the tests again @altendky ?

**Comment by altendky** [comment]
For the record on the above error...

https://github.com/Chia-Network/chia-blockchain/runs/4268413400?check_suite_focus=true
https://gist.github.com/altendky/cdfcf9aae28e1449863008b4819466b7#file-gistfile1-txt-L1623-L1626

```
2021-11-19T21:38:28.5710359Z 21:38:28 full_node_server: ERROR WebSocket Error: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 62914560 exceeds limit 52428800'), extra=None)
2021-11-19T21:38:28.5713537Z 2021-11-19T21:38:28.570 full_node full_node_server        : [31mERROR   [0m WebSocket Error: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 62914560 exceeds limit 52428800'), extra=None)[0m
2021-11-19T21:38:28.5716275Z 21:38:28 full_node_server: WARNING Trying to ban localhost for 300, but will not ban
2021-11-19T21:38:28.5718898Z 2021-11-19T21:38:28.570 full_node full_node_server        : [31mERROR   [0m WebSocket Error: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 62914560 exceeds limit 52428800'), extra=None)[0m
```

But I don't think that's the interesting bit.

https://gist.github.com/altendky/cdfcf9aae28e1449863008b4819466b7#file-gistfile1-txt-L2147-L2183
```
2021-11-19T21:40:56.1173457Z =================================== FAILURES ===================================
2021-11-19T21:40:56.1174024Z ______________________ TestRateLimits.test_periodic_reset ______________________
2021-11-19T21:40:56.1174423Z 
2021-11-19T21:40:56.1174959Z self = <test_rate_limits.TestRateLimits object at 0x7fe1ac415d90>
2021-11-19T21:40:56.1175403Z 
2021-11-19T21:40:56.1175778Z     @pytest.mark.asyncio
2021-11-19T21:40:56.1176280Z     async def test_periodic_reset(self):
2021-11-19T21:40:56.1176780Z         r = RateLimiter(True, 5)
2021-11-19T21:40:56.1177523Z         tx_message = make_msg(ProtocolMessageTypes.respond_transaction, bytes([1] * 500 * 1024))
2021-11-19T21:40:56.1178232Z         for i in range(10):
2021-11-19T21:40:56.1178706Z             assert r.process_msg_and_check(tx_message)
2021-11-19T21:40:56.1179113Z     
2021-11-19T21:40:56.1179478Z         saw_disconnect = False
2021-11-19T21:40:56.1179879Z         for i in range(300):
2021-11-19T21:40:56.1180361Z             response = r.process_msg_and_check(tx_message)
2021-11-19T21:40:56.1180856Z             if not response:
2021-11-19T21:40:56.1181265Z                 saw_disconnect = True
2021-11-19T21:40:56.1181706Z         assert saw_disconnect
2021-11-19T21:40:56.1182212Z         assert not r.process_msg_and_check(tx_message)
2021-11-19T21:40:56.1182718Z         await asyncio.sleep(6)
2021-11-19T21:40:56.1183225Z         assert r.process_msg_and_check(tx_message)
2021-11-19T21:40:56.1183644Z     
2021-11-19T21:40:56.1183978Z         # Counts reset also
2021-11-19T21:40:56.1184402Z         r = RateLimiter(True, 5)
2021-11-19T21:40:56.1185096Z         new_tx_message = make_msg(ProtocolMessageTypes.new_transaction, bytes([1] * 40))
2021-11-19T21:40:56.1185807Z         for i in range(3000):
2021-11-19T21:40:56.1186298Z             assert r.process_msg_and_check(new_tx_message)
2021-11-19T21:40:56.1186732Z     
2021-11-19T21:40:56.1187074Z         saw_disconnect = False
2021-11-19T21:40:56.1187479Z         for i in range(3000):
2021-11-19T21:40:56.1187972Z             response = r.process_msg_and_check(new_tx_message)
2021-11-19T21:40:56.1188476Z             if not response:
2021-11-19T21:40:56.1188899Z                 saw_disconnect = True
2021-11-19T21:40:56.1189329Z >       assert saw_disconnect
2021-11-19T21:40:56.1189710Z E       assert False
2021-11-19T21:40:56.1189954Z 
2021-11-19T21:40:56.1190430Z tests/core/server/test_rate_limits.py:157: AssertionError
```

I started to address something maybe similar for another test over in https://github.com/Chia-Network/chia-blockchain/pull/9206.  I'll link here and note that this test should be reviewed as well.

Rerunning the failed workflow now.

**Comment by cross** [comment]
@wjblanke this shows clean now, though @altendky 's test change is still pending.  that will only remove the possibility of the false negative we were seeing earlier here, shouldn't need to wait for it IMO.

**Review by emlowe — APPROVED** [review]

**Pull request merged**
