### PR TITLE
Add separate hostname for daemon

### PR DESCRIPTION
**Pull request by snikch**
# What

This adds a separate configuration key for the daemon hostname. Currently it uses `self_hostname`.

# Why

At the moment it's assumed that the daemon runs on the same host as the rpc server when attempting to start the rpc server. This is prohibitive when attempting to run all the components separately in their own containers. Allowing the daemon to run on its own host allows all components to be distributed, such as in a docker setup. 

# How

This adds a new `daemon_hostname` field to the configuration that defaults to the `self_hostname` value both in the config and in the code (fallback). It should be a no-op for all existing installations.

### CODE REVIEW

**Comment by snikch** [comment]
I'm guessing that's a rejection of this pr @hoffmang9. Any feedback on the PR or how I should go about suggesting changes like this in the future?

**Comment by hoffmang9** [comment]
I'm not sure how this got closed because it's not rejected at all.

**Comment by hoffmang9** [comment]
Ah - I deleted the target dev branch. Let me rebase it to a new dev branch once we're there. It was an automated close and not intentional.

**Comment by snikch** [comment]
Ah that makes sense, thanks for the update 👌

**Comment by hoffmang9** [comment]
Because it's coming from your fork, I think you have to make the PR again against the new dev branch. Sorry for the extra step. We'll huddle on the overall PR in the next day or two but it was too close to the release to consider for 11.

**Comment by snikch** [comment]
No prob. Done in #376

**Pull request closed without merging**
