### PR TITLE
Move startup / shutdown logging to INFO

### PR DESCRIPTION
**Pull request by aqk**
### Purpose:

Turn startup / shutdown logging off by default

### Current Behavior:

Log service startup and shutdown at WARNING log level (default)

### New Behavior:

Log service startup and shutdown at INFO log level

### CODE REVIEW

**Review by wallentx — APPROVED** [review]

**Review by emlowe — APPROVED** [review]

**Comment by aqk** [comment]
I still thing it would be useful to always have startup and shutdown in the log, but unfortunately log severity is conflated with "will this show up in the log" in the Python logger.

So, although these messages are "informational", they won't be displayed in people's log unless we make them `WARNING` (as far as I understand).

**Comment by wallentx** [comment]
> I still thing it would be useful to always have startup and shutdown in the log, but unfortunately log severity is conflated with "will this show up in the log" in the Python logger.
> 
> So, although these messages are "informational", they won't be displayed in people's log unless we make them `WARNING` (as far as I understand).

@aqk I just tested this post-merge:
`stdbuf -o0 grep -s '[Ss]tarting\|stopped' <(tail -F ~/.chia/mainnet/log/debug.log) | bat -Ppl cr`

> 2023-03-06T14:14:18.009 daemon chia.daemon.server         : INFO     Starting Daemon Server
> 2023-03-06T14:14:20.748 harvester harvester               : INFO     Starting service harvester ...
> 2023-03-06T14:14:20.764 harvester chia.rpc.rpc_server     : ERROR    Starting RPC server failed. Exception Traceback (most recent call last):
> 2023-03-06T14:14:20.867 farmer farmer                     : INFO     Starting service farmer ...
> 2023-03-06T14:14:20.979 full_node full_node               : INFO     Starting service full_node ...
> 2023-03-06T14:14:21.079 wallet wallet                     : INFO     Starting service wallet ...
> 2023-03-06T14:14:32.396 full_node full_node               : INFO     Service full_node at port 8444 fully stopped
> 2023-03-06T14:14:34.816 wallet wallet                     : INFO     Service wallet at port 8449 fully stopped
> 2023-03-06T14:14:35.471 daemon chia.daemon.server         : INFO     Daemon Server stopping, Services stopped: ['chia_harvester', 'chia_farmer', 'chia_full_node', 'chia_wallet']

My logging level is set to `DEBUG`, and we set `WARNING` by default, but that info is indeed in the logs for those who want to capture at that level.

**Comment by aqk** [comment]
> > I still thing it would be useful to always have startup and shutdown in the log, but unfortunately log severity is conflated with "will this show up in the log" in the Python logger.
> > So, although these messages are "informational", they won't be displayed in people's log unless we make them `WARNING` (as far as I understand).
> 
> @aqk I just tested this post-merge: `stdbuf -o0 grep -s '[Ss]tarting\|stopped' <(tail -F ~/.chia/mainnet/log/debug.log) | bat -Ppl cr`
> 
> > 2023-03-06T14:14:18.009 daemon chia.daemon.server         : INFO     Starting Daemon Server
> > 2023-03-06T14:14:20.748 harvester harvester               : INFO     Starting service harvester ...
> > 2023-03-06T14:14:20.764 harvester chia.rpc.rpc_server     : ERROR    Starting RPC server failed. Exception Traceback (most recent call last):
> > 2023-03-06T14:14:20.867 farmer farmer                     : INFO     Starting service farmer ...
> > 2023-03-06T14:14:20.979 full_node full_node               : INFO     Starting service full_node ...
> > 2023-03-06T14:14:21.079 wallet wallet                     : INFO     Starting service wallet ...
> > 2023-03-06T14:14:32.396 full_node full_node               : INFO     Service full_node at port 8444 fully stopped
> > 2023-03-06T14:14:34.816 wallet wallet                     : INFO     Service wallet at port 8449 fully stopped
> > 2023-03-06T14:14:35.471 daemon chia.daemon.server         : INFO     Daemon Server stopping, Services stopped: ['chia_harvester', 'chia_farmer', 'chia_full_node', 'chia_wallet']
> 
> My logging level is set to `DEBUG`, and we set `WARNING` by default, but that info is indeed in the logs for those who want to capture at that level.

I believe setting `DEBUG` shows all levels. and I believe setting `WARNING` level does not show `INFO`. Is that correct?

**Comment by wallentx** [comment]
@aqk Correct, I believe the hierarchy is as such:

- **NOTSET** = 0: _This is the initial default setting of a log when it is created. It is not really relevant and most developers will not even take notice of this category. In many circles, it has already become nonessential. The root log is usually created with level WARNING._
- **DEBUG** = 10: _This level gives detailed information, useful only when a problem is being diagnosed._
- **INFO** = 20: _This is used to confirm that everything is working as it should._
- **WARNING** = 30: _This level indicates that something unexpected has happened or some problem is about to happen in the near future._
- **ERROR** = 40: _As it implies, an error has occurred. The software was unable to perform some function._
- **CRITICAL** = 50: _A serious error has occurred. The program itself may shut down or not be able to continue running properly._

where the number is priority

I'm just gonna pretend that `NOTSET` isn't a thing... but apart from that:
`DEBUG` shows `DEBUG`+ all items below it
`INFO` shows `INFO`+ all items below it
`WARNING` shows `WARNING`+ all items below it
etc.

**Pull request merged**
