### PR TITLE
server: Drop some unused code

### PR DESCRIPTION
**Pull request by xdustinface**

### CODE REVIEW

**Review by arvidn — APPROVED** [review]
looks good to me. I think it would be good to hear from the person who added this code too

**Comment by hoffmang9** [comment]
There is a request for me to review this but this is not something I originally wrote or edited. I may be in blame due to some earlier co-merges.

**Comment by wallentx** [comment]
> There is a request for me to review this but this is not something I originally wrote or edited. I may be in blame due to some earlier co-merges.

Ah, your name did appear to pop up when I checked. Looking at the history it seems like it may have been just as you described

**Comment by xdustinface** [comment]
`Delivery` was added by @mariano54 and the rest by @Yostra but all this was added 2-3 years back and i assume this is either leftover from development / not longer used because of some earlier refactoring. In any case, it's not used anymore.

**Pull request merged**
