### PR TITLE
optimize CoinRecord DB access

### PR DESCRIPTION
**Pull request by arvidn**
This PR has 3 distinct patches:

1. instead of looking up coin records one at a time, from the database. Look them all up in a single SQL query
2. instead of inserting new coins one at a time, insert them all in a single SQL command
3. When marking coins as spent, instead of looking them up, modifying them and writing them back (one at a time), issue a single SQL command to set the `spent_index` and `spent=1` on the records.

Of these, (3) probably has the most significant performance impact, since it entirely avoids a redundant read from the DB of the coins we're about to mark as spent. It's quite possible we won't need the CoinRecord cache anymore with these changes, but I would want to have better measurements before making such change.

I would expect (1) and (2) primarily saves time on reduced overhead in python and aiosqlite. But (2) can probably also take better advantage of a future relaxation on the sync setting in the DB.

I was hoping to be able to collect better data on this change, but since the current callback mechanism in aiosqlite only calls us *once* when the query is issued, we can't (easily) time them.

### CODE REVIEW

**Review by emlowe — DISMISSED** [review]
Nice change. If inserting a huge number of such records, do we need to worry about any SQL query limites (max characters or max variables)?

**Comment by arvidn** [comment]
> Nice change. If inserting a huge number of such records, do we need to worry about any SQL query limites (max characters or max variables)?

We might. I think the windows build has a limit of a few thousand. I can't remember the specific limit (we hit it while we were in Miami).

Right now we don't include that many transactions per block, but a full block might get close to that limit (around 2000 spends).

**Comment by arvidn** [comment]
I'm going to extend this with a few more optimizations in the coin store as well, and hopefully try to quantify some improvement

**Review by arvidn — COMMENTED** [review]
This PR is split up into 3 bite-size commits. It may be simpler to review them individually.

**Comment by emlowe** [comment]
Looks good to me
Do we have existing tests that exercise this code?
Also, I suspect the SELECT optimization is probably less impactful than the INSERT.

**Comment by arvidn** [comment]
> Do we have existing tests that exercise this code?

Yes, these are exercised by existing tests.

> Also, I suspect the SELECT optimization is probably less impactful than the INSERT.

Probably. I would think the `_set_spent()` is probably the most impactful, but even lookups can happen in parallel now, which is especially important for spinning disks.

**Comment by arvidn** [comment]
I added some instrumentation to time `CoinStore.new_block()` before and after this patch (I left it in the PR, at `INFO` log level).

It's not a perfect apples-to-apples comparison, because it's not running on the same blocks, but it's running on the same machine instead (importantly with the DB on a spinning disk).

To compare, I divide the time it took to *add* and *update* the coins divided by the number of added and updated coins. It's not perfect since adding may be more expensive than updating.

Before this patch:

```
2021-09-10T14:56:14.246 full_node chia.full_node.coin_store: INFO     new_block() took 0.602979s additions: 14 removals: 23
2021-09-10T14:56:16.130 full_node chia.full_node.coin_store: INFO     new_block() took 0.793034s additions: 23 removals: 15
2021-09-10T14:56:29.846 full_node chia.full_node.coin_store: INFO     new_block() took 0.89939s additions: 16 removals: 7
2021-09-10T14:57:17.950 full_node chia.full_node.coin_store: INFO     new_block() took 5.6544s additions: 163 removals: 38
2021-09-10T14:57:59.038 full_node chia.full_node.coin_store: INFO     new_block() took 1.90345s additions: 20 removals: 96
2021-09-10T14:59:11.105 full_node chia.full_node.coin_store: INFO     new_block() took 5.6457s additions: 220 removals: 25
2021-09-10T15:00:05.561 full_node chia.full_node.coin_store: INFO     new_block() took 13.5758s additions: 575 removals: 28
2021-09-10T15:00:27.117 full_node chia.full_node.coin_store: INFO     new_block() took 0.084559s additions: 3 removals: 3
2021-09-10T15:01:25.883 full_node chia.full_node.coin_store: INFO     new_block() took 1.30987s additions: 51 removals: 37
2021-09-10T15:02:00.796 full_node chia.full_node.coin_store: INFO     new_block() took 0.282216s additions: 3 removals: 6
2021-09-10T15:02:57.374 full_node chia.full_node.coin_store: INFO     new_block() took 1.35237s additions: 16 removals: 50
2021-09-10T15:03:33.741 full_node chia.full_node.coin_store: INFO     new_block() took 0.162999s additions: 5 removals: 6
2021-09-10T15:04:12.951 full_node chia.full_node.coin_store: INFO     new_block() took 1.80625s additions: 12 removals: 110
2021-09-10T15:04:47.477 full_node chia.full_node.coin_store: INFO     new_block() took 0.717402s additions: 12 removals: 65
2021-09-10T15:05:25.971 full_node chia.full_node.coin_store: INFO     new_block() took 0.849008s additions: 10 removals: 58
2021-09-10T15:06:07.139 full_node chia.full_node.coin_store: INFO     new_block() took 0.633831s additions: 13 removals: 17
2021-09-10T15:06:45.423 full_node chia.full_node.coin_store: INFO     new_block() took 5.25997s additions: 220 removals: 12
2021-09-10T15:07:25.506 full_node chia.full_node.coin_store: INFO     new_block() took 0.682202s additions: 13 removals: 26
2021-09-10T15:08:01.301 full_node chia.full_node.coin_store: INFO     new_block() took 0.464986s additions: 15 removals: 14
2021-09-10T15:08:51.330 full_node chia.full_node.coin_store: INFO     new_block() took 1.38445s additions: 21 removals: 46
2021-09-10T15:09:28.229 full_node chia.full_node.coin_store: INFO     new_block() took 0.805763s additions: 8 removals: 24
2021-09-10T15:10:08.137 full_node chia.full_node.coin_store: INFO     new_block() took 0.785631s additions: 18 removals: 20
2021-09-10T15:10:46.519 full_node chia.full_node.coin_store: INFO     new_block() took 0.563406s additions: 17 removals: 29
2021-09-10T15:11:21.238 full_node chia.full_node.coin_store: INFO     new_block() took 1.44809s additions: 30 removals: 40
2021-09-10T15:12:06.531 full_node chia.full_node.coin_store: INFO     new_block() took 6.75994s additions: 240 removals: 23
2021-09-10T15:13:26.173 full_node chia.full_node.coin_store: INFO     new_block() took 16.4176s additions: 723 removals: 107
2021-09-10T15:14:23.520 full_node chia.full_node.coin_store: INFO     new_block() took 2.24882s additions: 23 removals: 89
2021-09-10T15:15:31.724 full_node chia.full_node.coin_store: INFO     new_block() took 7.34265s additions: 233 removals: 208
2021-09-10T15:16:02.392 full_node chia.full_node.coin_store: INFO     new_block() took 0.957205s additions: 33 removals: 23
2021-09-10T15:16:43.604 full_node chia.full_node.coin_store: INFO     new_block() took 0.360973s additions: 10 removals: 11
2021-09-10T15:17:19.119 full_node chia.full_node.coin_store: INFO     new_block() took 0.46504s additions: 14 removals: 11
2021-09-10T15:18:30.768 full_node chia.full_node.coin_store: INFO     new_block() took 1.95252s additions: 61 removals: 57
2021-09-10T15:19:13.574 full_node chia.full_node.coin_store: INFO     new_block() took 1.22063s additions: 11 removals: 103
2021-09-10T15:19:43.110 full_node chia.full_node.coin_store: INFO     new_block() took 0.137902s additions: 3 removals: 2
2021-09-10T15:20:37.932 full_node chia.full_node.coin_store: INFO     new_block() took 7.64212s additions: 20 removals: 281
2021-09-10T15:21:38.452 full_node chia.full_node.coin_store: INFO     new_block() took 1.11048s additions: 40 removals: 49
2021-09-10T15:22:49.003 full_node chia.full_node.coin_store: INFO     new_block() took 1.82235s additions: 7 removals: 166
2021-09-10T15:23:59.251 full_node chia.full_node.coin_store: INFO     new_block() took 5.6581s additions: 219 removals: 35
2021-09-10T15:25:07.626 full_node chia.full_node.coin_store: INFO     new_block() took 0.450871s additions: 7 removals: 13
2021-09-10T15:25:40.482 full_node chia.full_node.coin_store: INFO     new_block() took 1.07719s additions: 13 removals: 97
2021-09-10T15:26:59.828 full_node chia.full_node.coin_store: INFO     new_block() took 12.0152s additions: 557 removals: 101
2021-09-10T15:28:07.523 full_node chia.full_node.coin_store: INFO     new_block() took 0.781641s additions: 21 removals: 25
2021-09-10T15:28:48.661 full_node chia.full_node.coin_store: INFO     new_block() took 0.793653s additions: 10 removals: 53
2021-09-10T15:29:44.535 full_node chia.full_node.coin_store: INFO     new_block() took 5.28404s additions: 12 removals: 260
2021-09-10T15:30:35.999 full_node chia.full_node.coin_store: INFO     new_block() took 1.3688s additions: 27 removals: 152
2021-09-10T15:31:15.317 full_node chia.full_node.coin_store: INFO     new_block() took 1.47527s additions: 39 removals: 41
2021-09-10T15:31:53.681 full_node chia.full_node.coin_store: INFO     new_block() took 0.447645s additions: 6 removals: 13
2021-09-10T15:33:14.401 full_node chia.full_node.coin_store: INFO     new_block() took 4.81411s additions: 17 removals: 307
2021-09-10T15:34:21.358 full_node chia.full_node.coin_store: INFO     new_block() took 5.32951s additions: 214 removals: 17
2021-09-10T15:35:17.481 full_node chia.full_node.coin_store: INFO     new_block() took 2.37649s additions: 12 removals: 90
2021-09-10T15:36:07.777 full_node chia.full_node.coin_store: INFO     new_block() took 0.654009s additions: 27 removals: 12
2021-09-10T15:36:50.153 full_node chia.full_node.coin_store: INFO     new_block() took 0.49775s additions: 14 removals: 45
2021-09-10T15:37:30.130 full_node chia.full_node.coin_store: INFO     new_block() took 0.888408s additions: 7 removals: 30
2021-09-10T15:38:07.712 full_node chia.full_node.coin_store: INFO     new_block() took 0.470207s additions: 14 removals: 15
2021-09-10T15:38:48.579 full_node chia.full_node.coin_store: INFO     new_block() took 0.637561s additions: 6 removals: 22
2021-09-10T15:39:23.740 full_node chia.full_node.coin_store: INFO     new_block() took 1.04562s additions: 7 removals: 36
2021-09-10T15:41:05.992 full_node chia.full_node.coin_store: INFO     new_block() took 6.18854s additions: 52 removals: 260
2021-09-10T15:41:56.948 full_node chia.full_node.coin_store: INFO     new_block() took 11.5312s additions: 423 removals: 14
2021-09-10T15:42:26.203 full_node chia.full_node.coin_store: INFO     new_block() took 0.962532s additions: 11 removals: 111
2021-09-10T15:44:05.805 full_node chia.full_node.coin_store: INFO     new_block() took 5.99534s additions: 224 removals: 147
2021-09-10T15:44:36.047 full_node chia.full_node.coin_store: INFO     new_block() took 0.219692s additions: 4 removals: 32
2021-09-10T15:45:22.168 full_node chia.full_node.coin_store: INFO     new_block() took 2.17571s additions: 122 removals: 16
2021-09-10T15:46:04.527 full_node chia.full_node.coin_store: INFO     new_block() took 1.41128s additions: 26 removals: 95
2021-09-10T15:46:40.002 full_node chia.full_node.coin_store: INFO     new_block() took 0.392964s additions: 14 removals: 10
2021-09-10T15:47:40.995 full_node chia.full_node.coin_store: INFO     new_block() took 0.646126s additions: 11 removals: 24
2021-09-10T15:48:31.599 full_node chia.full_node.coin_store: INFO     new_block() took 0.913382s additions: 24 removals: 55
2021-09-10T15:49:09.871 full_node chia.full_node.coin_store: INFO     new_block() took 1.58134s additions: 7 removals: 92
2021-09-10T15:51:20.124 full_node chia.full_node.coin_store: INFO     new_block() took 14.519s additions: 656 removals: 388
2021-09-10T15:52:09.164 full_node chia.full_node.coin_store: INFO     new_block() took 1.05545s additions: 17 removals: 28
2021-09-10T15:53:00.478 full_node chia.full_node.coin_store: INFO     new_block() took 2.28118s additions: 88 removals: 17
2021-09-10T15:53:38.351 full_node chia.full_node.coin_store: INFO     new_block() took 0.409662s additions: 15 removals: 18
2021-09-10T15:54:46.456 full_node chia.full_node.coin_store: INFO     new_block() took 4.87723s additions: 190 removals: 113
2021-09-10T15:55:23.186 full_node chia.full_node.coin_store: INFO     new_block() took 1.22652s additions: 13 removals: 160
2021-09-10T15:55:55.460 full_node chia.full_node.coin_store: INFO     new_block() took 0.803067s additions: 22 removals: 27
2021-09-10T15:56:36.999 full_node chia.full_node.coin_store: INFO     new_block() took 0.299135s additions: 6 removals: 7
```

This works out to an average of0.018195  seconds per addition or update with 6070 additions and 4903 updates.

After:

```
2021-09-10T14:13:31.146 full_node chia.full_node.coin_store: INFO     new_block() took 0.303081s additions: 12 removals: 13
2021-09-10T14:13:31.586 full_node chia.full_node.coin_store: INFO     new_block() took 0.308944s additions: 9 removals: 5
2021-09-10T14:13:31.852 full_node chia.full_node.coin_store: INFO     new_block() took 0.132007s additions: 5 removals: 3
2021-09-10T14:13:32.613 full_node chia.full_node.coin_store: INFO     new_block() took 0.274641s additions: 3 removals: 12
2021-09-10T14:13:33.358 full_node chia.full_node.coin_store: INFO     new_block() took 0.323811s additions: 14 removals: 41
2021-09-10T14:13:34.728 full_node chia.full_node.coin_store: INFO     new_block() took 0.346025s additions: 12 removals: 52
2021-09-10T14:13:35.486 full_node chia.full_node.coin_store: INFO     new_block() took 0.278539s additions: 3 removals: 23
2021-09-10T14:13:48.029 full_node chia.full_node.coin_store: INFO     new_block() took 6.41434s additions: 289 removals: 194
2021-09-10T14:13:55.015 full_node chia.full_node.coin_store: INFO     new_block() took 0.293993s additions: 11 removals: 12
2021-09-10T14:13:55.896 full_node chia.full_node.coin_store: INFO     new_block() took 0.717256s additions: 37 removals: 19
2021-09-10T14:13:57.949 full_node chia.full_node.coin_store: INFO     new_block() took 0.459171s additions: 13 removals: 20
2021-09-10T14:14:03.403 full_node chia.full_node.coin_store: INFO     new_block() took 5.11993s additions: 209 removals: 8
2021-09-10T14:14:09.253 full_node chia.full_node.coin_store: INFO     new_block() took 0.304883s additions: 10 removals: 19
2021-09-10T14:14:10.546 full_node chia.full_node.coin_store: INFO     new_block() took 0.517094s additions: 10 removals: 30
2021-09-10T14:14:41.520 full_node chia.full_node.coin_store: INFO     new_block() took 0.881133s additions: 22 removals: 38
2021-09-10T14:15:28.116 full_node chia.full_node.coin_store: INFO     new_block() took 0.219484s additions: 5 removals: 4
2021-09-10T14:16:07.114 full_node chia.full_node.coin_store: INFO     new_block() took 0.769565s additions: 20 removals: 39
2021-09-10T14:17:16.853 full_node chia.full_node.coin_store: INFO     new_block() took 0.801106s additions: 9 removals: 61
2021-09-10T14:18:22.274 full_node chia.full_node.coin_store: INFO     new_block() took 2.6203s additions: 9 removals: 188
2021-09-10T14:19:20.099 full_node chia.full_node.coin_store: INFO     new_block() took 6.82684s additions: 584 removals: 11
2021-09-10T14:20:58.897 full_node chia.full_node.coin_store: INFO     new_block() took 23.9508s additions: 1040 removals: 73
2021-09-10T14:22:18.387 full_node chia.full_node.coin_store: INFO     new_block() took 17.1887s additions: 1019 removals: 28
2021-09-10T14:22:32.511 full_node chia.full_node.coin_store: INFO     new_block() took 0.4715s additions: 6 removals: 33
2021-09-10T14:23:10.403 full_node chia.full_node.coin_store: INFO     new_block() took 0.726185s additions: 9 removals: 7
2021-09-10T14:23:59.526 full_node chia.full_node.coin_store: INFO     new_block() took 7.19396s additions: 599 removals: 15
2021-09-10T14:24:44.618 full_node chia.full_node.coin_store: INFO     new_block() took 9.40425s additions: 406 removals: 16
2021-09-10T14:25:07.381 full_node chia.full_node.coin_store: INFO     new_block() took 0.194051s additions: 7 removals: 19
2021-09-10T14:25:54.458 full_node chia.full_node.coin_store: INFO     new_block() took 0.987373s additions: 21 removals: 162
2021-09-10T14:26:56.180 full_node chia.full_node.coin_store: INFO     new_block() took 10.0619s additions: 412 removals: 16
2021-09-10T14:27:32.755 full_node chia.full_node.coin_store: INFO     new_block() took 0.225486s additions: 10 removals: 7
2021-09-10T14:28:14.940 full_node chia.full_node.coin_store: INFO     new_block() took 0.981939s additions: 10 removals: 73
2021-09-10T14:29:01.052 full_node chia.full_node.coin_store: INFO     new_block() took 7.19684s additions: 309 removals: 14
2021-09-10T14:30:40.974 full_node chia.full_node.coin_store: INFO     new_block() took 1.14642s additions: 37 removals: 72
2021-09-10T14:31:22.637 full_node chia.full_node.coin_store: INFO     new_block() took 1.77724s additions: 56 removals: 137
2021-09-10T14:32:13.279 full_node chia.full_node.coin_store: INFO     new_block() took 18.9787s additions: 805 removals: 12
2021-09-10T14:33:36.992 full_node chia.full_node.coin_store: INFO     new_block() took 0.885406s additions: 32 removals: 114
2021-09-10T14:34:38.154 full_node chia.full_node.coin_store: INFO     new_block() took 15.8911s additions: 760 removals: 20
2021-09-10T14:34:57.863 full_node chia.full_node.coin_store: INFO     new_block() took 1.57261s additions: 3 removals: 114
2021-09-10T14:35:46.208 full_node chia.full_node.coin_store: INFO     new_block() took 0.427785s additions: 16 removals: 48
2021-09-10T14:37:24.166 full_node chia.full_node.coin_store: INFO     new_block() took 11.4335s additions: 439 removals: 209
2021-09-10T14:37:48.823 full_node chia.full_node.coin_store: INFO     new_block() took 0.291042s additions: 13 removals: 17
2021-09-10T14:38:39.859 full_node chia.full_node.coin_store: INFO     new_block() took 0.519181s additions: 16 removals: 20
2021-09-10T14:40:07.293 full_node chia.full_node.coin_store: INFO     new_block() took 13.0333s additions: 530 removals: 95
2021-09-10T14:40:46.060 full_node chia.full_node.coin_store: INFO     new_block() took 0.491776s additions: 14 removals: 11
2021-09-10T14:42:31.802 full_node chia.full_node.coin_store: INFO     new_block() took 1.44109s additions: 42 removals: 115
2021-09-10T14:43:10.256 full_node chia.full_node.coin_store: INFO     new_block() took 0.151109s additions: 3 removals: 3
2021-09-10T14:43:56.522 full_node chia.full_node.coin_store: INFO     new_block() took 0.46472s additions: 12 removals: 19
2021-09-10T14:44:41.113 full_node chia.full_node.coin_store: INFO     new_block() took 0.243552s additions: 7 removals: 8
2021-09-10T14:45:28.123 full_node chia.full_node.coin_store: INFO     new_block() took 9.52237s additions: 410 removals: 158
2021-09-10T14:46:10.233 full_node chia.full_node.coin_store: INFO     new_block() took 1.92861s additions: 84 removals: 8
2021-09-10T14:47:18.481 full_node chia.full_node.coin_store: INFO     new_block() took 12.7743s additions: 637 removals: 138
2021-09-10T14:49:40.999 full_node chia.full_node.coin_store: INFO     new_block() took 0.894043s additions: 33 removals: 87
2021-09-10T14:50:40.303 full_node chia.full_node.coin_store: INFO     new_block() took 11.6604s additions: 227 removals: 504
2021-09-10T14:51:04.666 full_node chia.full_node.coin_store: INFO     new_block() took 1.21059s additions: 34 removals: 106
2021-09-10T14:51:42.848 full_node chia.full_node.coin_store: INFO     new_block() took 0.19653s additions: 6 removals: 7
2021-09-10T14:52:30.153 full_node chia.full_node.coin_store: INFO     new_block() took 0.24215s additions: 11 removals: 8
2021-09-10T14:53:03.345 full_node chia.full_node.coin_store: INFO     new_block() took 0.540922s additions: 10 removals: 78
```

This works out to an average of 0.016822 seconds per add or update. With 9371 additions and 3363 updates.

**Review by Yostra — CHANGES_REQUESTED** [review]
It's possible to create a valid block that hits the limit of sql variables, I wrote a quick snippet to confirm this. https://gist.github.com/Yostra/a5959ac89c93d7bd95e3fd5c2ab99cf6

**Comment by Yostra** [comment]
Maybe batch inserts / removals in multiple 1k batches ?

**Comment by arvidn** [comment]
I will not pursue this PR until I have a benchmark and can demonstrate actual performance improvements. It's possible that just pipelining these SQL commands is just as efficient. i.e. not wait for the first to complete until issuing the next one

**Comment by arvidn** [comment]
thanks @Yostra !

**Comment by arvidn** [comment]
updated to `NORMAL`

**Pull request closed without merging**
