### PR TITLE
Improve show -c display format

### PR DESCRIPTION
**Pull request by wolfrage76**

### CODE REVIEW

**Comment by hoffmang9** [comment]
Have you considered IPv6 hosts?

**Review by wolfrage76 — COMMENTED** [review]
Fixed space indent

**Comment by hoffmang9** [comment]
image

**Comment by wolfrage76** [comment]
> Have you considered IPv6 hosts?

Sure, will adjust to extend to hold the max 45 character length of IPV6 and still remove the hard linebreaks that make it difficult to read.

**Comment by mariano54** [comment]
@wolfrage76 do you mind fixing the lint errors?
Thanks for the contribution

**Pull request closed without merging**
