### PR TITLE
remove implementation from `BlockRecordProtocol.is_transaction_block()`

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Review by AmineKhaldi — APPROVED** [review]
Thank you.

**Comment by arvidn** [comment]
would mypy tell us if a type doesn't implement this method when it's passed as implementing this protocol?
There's no description of the PR,so I assume all types that implement this protocol already have their own implementations, and that they are compatible. is that right?

**Comment by arvidn** [comment]
is it better to have this implemented in each class rather than in the protocol?

**Comment by altendky** [comment]
I generally avoid inheriting from protocols and thus implementing on the protocol itself doesn't do anything.  I don't think mypy would notice anything around this change.  Since this is a protocol, mypy doesn't care that there's no return in the method.  As far as other classes checked against this, mypy wouldn't care about the implementation, just the signature.

So no, I don't think mypy would notice anything changing about this.

A search only shows this protocol being used for hints, not inheritance.

The pr was just intended to clean up this seemingly unused implementation code on the interface-defining protocol.

**Review by emlowe — APPROVED** [review]

**Pull request merged**
