### PR TITLE
Faster tests

### PR DESCRIPTION
**Pull request by aqk**

### CODE REVIEW

**Comment by mariano54** [comment]
Great idea! Which tests are the slowest BTW? Maybe I can help out by optimizing those or splitting them up

**Comment by aqk** [comment]
Thanks :)

These are the slowest right now:

simulation/test_simulation.py::TestSimulation::test_simulation_1

blockchain/test_blockchain.py::TestReorgs::test_long_reorg
blockchain/test_blockchain.py::TestReorgs::test_long_compact_blockchain
blockchain/test_blockchain.py::TestBlockHeaderValidation::test_empty_sub_slots_epoch

core/full_node/full_sync/test_full_sync.py::TestFullSync::test_sync_from_fork_point_and_weight_proof
core/full_node/full_sync/test_full_sync.py::TestFullSync::test_long_sync_from_zero
core/full_node/full_sync/test_full_sync.py::TestFullSync::test_close_height_but_big_reorg

core/full_node/test_full_node_store.py::TestFullNodeStore::test_long_chain_slots
core/full_node/test_full_node_store.py::TestFullNodeStore::test_basic_store_compact_blockchain

wallet/test_wallet.py::TestWalletSimulator::test_wallet_create_hit_max_send_amount
wallet/sync/test_wallet_sync.py::TestWalletSync::test_long_sync_wallet
wallet/sync/test_wallet_sync.py::TestWalletSync::test_basic_sync_wallet
wallet/sync/test_wallet_sync.py::TestWalletSync::test_wallet_reorg_get_coinbase

core/server/test_dos.py::TestDos::test_bad_handshake_and_ban

**Review by hoffmang9 — DISMISSED** [review]
Been wanting this for a while....

**Comment by aqk** [comment]
Let's merge it!

I'll rebase this to main again now.

**Review by justinengland — APPROVED** [review]

**Pull request merged**
