### PR TITLE
Add harvester response log records

### PR DESCRIPTION
**Pull request by sashacmc**
Thanks to @fiveangle for formatting

### CODE REVIEW

**Review by mariano54 — DISMISSED** [review]

**Comment by jcasc** [comment]
Missed opportunity to print the harvester's IP and/or peer ID by annotating the function with peer_required and printing the peer info as well.

**Comment by fiveangle** [comment]
@jcasc  @sashacmc investigated and didn't see a way to do so.  I mentioned to him after seeing your change that it seems pulling in `@peer_required` would allow that but I think he must have been busy so hasn't read my comment, or he surely woudl have tweaked it.  I agree, it should be augmented to support that feature and in a way that the results passing through the GUI harvester entries identify the harvester.

This is what we get when a bunch of people have the same good idea but are using a network of tubes to communicate ;)

**Comment by mariano54** [comment]
Yeah we could print the peer also. @jespino was working on more extensive changes to save all of this info and expose it through RPC. 
I am fine with merging this though, if we fix the lint issue

**Comment by fiveangle** [comment]
> Yeah we could print the peer also. @jespino was working on more extensive changes to save all of this info and expose it through RPC.
> I am fine with merging this though, if we fix the lint issue

submitted the fix to @sashacmc 's repo  https://github.com/sashacmc/chia-blockchain/pull/2

**Comment by losingle** [comment]
good features

**Comment by fiveangle** [comment]
@mariano54, reviewing the macos wallet errors, those appear fully unrelated to this change. Let me know your thoughts. Really want this in the next official release so I don't have to keep running my own branch :)

**Comment by hoffmang9** [comment]
It is a known flaky test than you can ignore.

**Comment by emlowe** [comment]
Thanks for this PR, we believe most of these were addressed in other PRs and release - so closing this PR

**Pull request closed without merging**
