### PR TITLE
Fix typo in wallet: puzzle

### PR DESCRIPTION
**Pull request by wizicer**

### CODE REVIEW

**Review by paninaro — DISMISSED** [review]
lgtm. Thanks for the fix!

**Comment by wallentx** [comment]
@wizicer we have branch protection rules in place that require signed commits (https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) that is preventing me from merging this. Are you able to resign your commit? If you need assistance with this, I'm happy to help if you are able to provide me with your Keybase username where I could message you.

**Review by paninaro — APPROVED** [review]

**Comment by wizicer** [comment]
> @wizicer we have branch protection rules in place that require signed commits (https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) that is preventing me from merging this. Are you able to resign your commit? If you need assistance with this, I'm happy to help if you are able to provide me with your Keybase username where I could message you.

@wallentx Thanks for reminding me, I have updated with signed commits.

**Comment by wallentx** [comment]
Thanks!

**Pull request merged**
