### PR TITLE
Remove unused alert server test code and support files

### PR DESCRIPTION
**Pull request by emlowe**
Remove unused support files `create_alert_file.py` and `validate_alert.py`, along with unused test code.

Half of the test code for the alerts was removed back in #1487, this removes the rest.

All the code that actually used these alerts in the daemon was also removed in #1487, so even if we wanted to re-use this, the existing versions of Chia in the wild will never use the alerts. So I think this is all dead code we might as well just remove.

Also removed relevant files from mypy.ini

### CODE REVIEW

**Review by hoffmang9 — DISMISSED** [review]
Ah the flag drop...

**Review by xdustinface — CHANGES_REQUESTED** [review]
It's also one of the excluded files in `mypy.ini`, lets drop it there too then :)

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Comment by emlowe** [comment]
close and reopen for CI

**Review by xdustinface — APPROVED** [review]

**Review by wjblanke — APPROVED** [review]
aok

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
