### PR TITLE
revert allow-upgrades configuration option

### PR DESCRIPTION
**Pull request by arvidn**
It makes it significantly more complicated to do proper database migrations

### CODE REVIEW

**Comment by mariano54** [comment]
Will the people that already used it be in trouble for the migration?

**Comment by arvidn** [comment]
I don't believe we ever released this feature, so it would be limited to people running from git `main`. And the extent of the "trouble" people will be in, is that the transition to `v2` will be slower, because the v2 transition tool currently assumes the v1 database is in the non-upgraded state.

So, there won't be any data loss, it's just some indices that will be re-created before starting the conversion.

**Comment by arvidn** [comment]
The alternative to reverting this would be to make the transition code more sophisticated and detect (or load from settings) which indices to expect in the source DB file.

**Comment by mariano54** [comment]
I see. Ok that's not a big issue then, it would be fine as long as it works.

**Comment by arvidn** [comment]
The PR introducing this was here: https://github.com/Chia-Network/chia-blockchain/pull/9349
reviewed by @mariano54  and @emlowe so I'll add you as reviewers here too.

**Review by mariano54 — APPROVED** [review]

**Pull request merged**
