### PR TITLE
another assert to make sure wallet is correct

### PR DESCRIPTION
**Pull request by wjblanke**

### CODE REVIEW

**Comment by altendky** [comment]
I would expect this to target `release/1.4.0`.  It is 'just tests', but in so much as it does make this more reliable then I would think we would want that in the release ci runs.

**Comment by AmineKhaldi** [comment]
> I would expect this to target `release/1.4.0`. It is 'just tests', but in so much as it does make this more reliable then I would think we would want that in the release ci runs.

Bill is okay with that. I'll retarget, close and reopen.

**Comment by altendky** [comment]
Yeah, gotta rebase or make a new PR.  Otherwise you are bringing main into release.

**Comment by altendky** [comment]
Just made it draft to avoid accidental merging until the above comment is addressed.

**Comment by AmineKhaldi** [comment]
> Just made it draft to avoid accidental merging until the above comment is addressed.

Thanks, should be good to go.

**Review by altendky — DISMISSED** [review]

**Review by altendky — APPROVED** [review]
_This_ got conflicted twice today?  Wow...

**Pull request merged**
