### PR TITLE
generate file lists for workflows instead of wildcard patterns

### PR DESCRIPTION
**Pull request by altendky**
This pulls the control of the file list into our generation code rather than leaving it to OS-varying mechanisms like wildcard expansion.

Extracted from https://github.com/Chia-Network/chia-blockchain/pull/10681.

### CODE REVIEW

**Review by hoffmang9 — DISMISSED** [review]
lgtm pending CI

**Comment by wjblanke** [comment]
conflicts.... i also hesitate on this because new files wont automatically get included with this change

**Comment by altendky** [comment]
The code changing here is part of the workflow generation.  The workflows are verified to be up to date in CI itself by that same script making sure that it would not introduce any changes.  It certainly could have a bug but at the basic level the workflows are certainly checked for being out of date.

**Comment by altendky** [comment]
Testing my claim at https://github.com/Chia-Network/chia-blockchain/pull/11244.

**Comment by altendky** [comment]
Looks good.

https://github.com/Chia-Network/chia-blockchain/runs/6103492133?check_suite_focus=true

image

**Review by emlowe — APPROVED** [review]
I approve

**Pull request merged**
