### PR TITLE
fix flakey test

### PR DESCRIPTION
**Pull request by almogdepaz**
better isolation for testing ses mismatch on sync, this should now run consistently

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]

**Comment by mariano54** [comment]
Looks like it's still broken, or maybe this is something else:
https://github.com/Chia-Network/chia-blockchain/runs/8165529186?check_suite_focus=true

**Comment by mariano54** [comment]
^ @paninaro is this the same TSL cert issue as before?

**Comment by mariano54** [comment]
Or maybe we need to `await async_mock` @almogdepaz ? There is an error about that in the log.f

**Comment by almogdepaz** [comment]
> Or maybe we need to `await async_mock` @almogdepaz ? There is an error about that in the log.f

@mariano54 it looks like the event loop was closed mid sync and that failed the test, im not sure its related specifically to this test, looking into it

**Pull request merged**
