### PR TITLE
Change all commands to use one client generator function & Add chia peer command 

### PR DESCRIPTION
**Pull request by jack60612**
Copy of  #12532 due to git issues
there is no diff between this branch and old branch + merge
old branch viewable at `jn.cmds-refactor-old`, if you merge this please also delete that branch

### CODE REVIEW

**Comment by wallentx** [comment]
@mariano54 I'm not sure that the LGTM results are valid, since a glance at all the alerts that it has produced for us shows the same cyclic import errors for pretty much all of our code. If CodeQL is the suggested replacement, the results of the CodeQL scan didn't return any issues https://github.com/Chia-Network/chia-blockchain/pull/12778/checks?check_run_id=7846986494

**Comment by justinengland** [comment]
LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

**Comment by justinengland** [comment]
We either need to scan this with github code scanning. Or snyk. I agree that the LGTM stuff appears to be a false positive, and this tool is going away anyway. IPS is going to work to sunset this tool in the next month or so.

**Review by mariano54 — APPROVED** [review]
Tried to find cyclic import, can't find it... hopefully it's ok

**Pull request merged**
