### PR TITLE
add rate limits numbers to none response type

### LINKED ISSUE #14162: [Bug] Message type ProtocolMessageTypes.none_response not found in rate limits
### What happened?

There are a lot of similar entries in the log.

### Version

1.7.0rc3-dev63

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-12-15T20:19:39.297 full_node chia.server.rate_limits : WARNING  Message type ProtocolMessageTypes.none_response not found in rate limits
2022-12-15T20:19:40.793 full_node chia.server.rate_limits : WARNING  Message type ProtocolMessageTypes.none_response not found in rate limits
2022-12-15T20:19:41.373 full_node chia.server.rate_limits : WARNING  Message type ProtocolMessageTypes.none_response not found in rate limits
```

### PR DESCRIPTION
**Pull request by almogdepaz**
added rate limit numbers to the new none_response message type, doesn't change behavior 
https://github.com/Chia-Network/chia-blockchain/issues/14162

### CODE REVIEW

**Comment by arvidn** [comment]
we have a fair amount of test infrastructure around protocol messages to ensure we don't miss things like this.
Could you add a test in CI to make sure all message types have rate limits? (possibly with a hard coded whitelist of exceptions).

**Comment by almogdepaz** [comment]
> we have a fair amount of test infrastructure around protocol messages to ensure we don't miss things like this. Could you add a test in CI to make sure all message types have rate limits? (possibly with a hard coded whitelist of exceptions).

not in this pr since we have lots of other messages that are missing rate limits

**Comment by altendky** [comment]
Those tests need a lot of rework that needs to be based on a lot of API tracking rework before they'll be robust.

**Comment by altendky** [comment]
I guess the numbers for this would be dependent on which messages respond with this and how frequent they are?  Or maybe that's too detailed.

**Comment by almogdepaz** [comment]
> I guess the numbers for this would be dependent on which messages respond with this and how frequent they are? Or maybe that's too detailed.

not sure i understand what you are saying here

**Comment by altendky** [comment]
I was guessing at how to pick the proper numbers since that seemed like the most important part of this review.  How did you select the frequency of 500 and max size of 100?

**Comment by almogdepaz** [comment]
> I was guessing at how to pick the proper numbers since that seemed like the most important part of this review. How did you select the frequency of 500 and max size of 100?

i used other message types as reference, this should be a rare occasion so i dont think we will hit

**Review by altendky — APPROVED** [review]

**Review by emlowe — APPROVED** [review]

**Pull request merged**
