### PR TITLE
server: Drop outdated config update

### PR DESCRIPTION
**Pull request by xdustinface**
### Purpose:

Drop some unused code, it just seems to me that we don't need this anymore, its coming from here #1598.

### New Behavior:

No change in behaviour.

### CODE REVIEW

**Comment by almogdepaz** [comment]
how do we know if there are still users without this config entry ?

or so we just not care at this point and they should upgrade ?

**Comment by xdustinface** [comment]
> how do we know if there are still users without this config entry ?

Thanks, i checked the accesses to `trusted_peers` and just opened #14643 but other than that i don't see why adding this `local_node` entry still would help someone? I might be confused.. if there is still something let me know what scenario you are thinking about!

**Comment by almogdepaz** [comment]
> > how do we know if there are still users without this config entry ?
> 
> Thanks, i checked the accesses to `trusted_peers` and just opened #14643 but other than that i don't see why adding this `local_node` entry still would help someone? I might be confused.. if there is still something let me know what scenario you are thinking about!

they still would not have the default trusted node after #14643 no ?

**Comment by xdustinface** [comment]
> they still would not have the default trusted node after #14643 no ?

Whats the point of having it if it's not even used? I guess it would make sense if you tell the exact scenario which could lead to issues here.

**Comment by emlowe** [comment]
This code seems all wrong anyway, as it's using the old "point to certificate file" way to identify trusted peers which we changed to use the node-id, so even if you had this setting, nothing checks it correctly.

So I think this is safe to remove. We use the loopback address to trust the local node

**Review by emlowe — APPROVED** [review]

**Pull request merged**
