### PR TITLE
allow non-ssl rpc clients (2)

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by arvidn** [comment]
the handlers for RPC calls assume that RPC calls are trusted. i.e. there are DoS opportunities via the RPC. I'm not exactly sure what the intent is here, but unauthenticated RPC connections (that's not over loopback or a unix socket) would be risky

**Comment by felixbrucker** [comment]
Why is this necessary?

**Comment by altendky** [comment]
I was adding this so that tests of the rpc client don't have to setup ssl etc.  https://github.com/Chia-Network/chia-blockchain/pull/17460

**Comment by felixbrucker** [comment]
It feels weird to me to have test specific code in prod code

**Comment by altendky** [comment]
It feels weird to me to require SSL certs generated and setup in the proper directory structure with config referencing them to test the client's handling of a traceback string in JSON.  `:]`  But yes, also what you said, and Arvid shares your sentiment.  We'll see where they land on this.

**Review by arvidn — APPROVED** [review]
I think, in an ideal world, the test would short-circuit the actual socket, and feed requests via something that looks like one. Bit this might be more practical to do now.
It's not clear to me how you get away without changing the rpc_api. i.e. the server side. It needs to accept non-SSL connections too, right?

**Comment by altendky** [comment]
I have a made up webserver that records requests for some datalayer tests and I added to it the ability to send it a `{"response": {"success": True, "whatever": "you want"}}` to specify what it responds with.  It doesn't use any of our RPC API.  I went minimal for these tests.  Others testing more specific interaction between our RPC client and RPC server ought to leverage the actual RPC server, sure.

**Pull request merged**
