### PR TITLE
tests: Don't drop the test plot directory if the test gets interrupted

### PR DESCRIPTION
**Pull request by xdustinface**
If you currently cancel the test during the plot setup phase it just removes the whole directory and with it all the test plots for no good reason. At least in my opinion its just annoying. Sure, you can clone the `test-cache` repo and copy them over if this happens but i still think its better to just merge this PR :)

### CODE REVIEW

**Comment by arvidn** [comment]
I assume this was done to ensure we wouldn't have incomplete/partial plots in the test directory. Is there anything mitigating this now?

When rerun, will we re-plot the missing files?
our plotter also leaves temporary files behind when it's interrupted, are those cleared, or do they accrue indefinitely every time this stage is interrupted?

**Comment by xdustinface** [comment]
> I assume this was done to ensure we wouldn't have incomplete/partial plots in the test directory. Is there anything mitigating this now?

Nope but this can only happen if you interrupt the plot creation phase for the very first time where it really created the plots. Every other run just walks through the setup and skips the actual creation if the plot exists.

> When rerun, will we re-plot the missing files? 

If there are missing plots it will still re-plot them of course.

> our plotter also leaves temporary files behind when it's interrupted, are those cleared, or do they accrue indefinitely every time this stage is interrupted?

Yeah they are left behind if interrupted.. but again here, this is only an issue if you interrupt the plot creation for the very first time.

**Review by arvidn — DISMISSED** [review]
I think it would be good to ask someone involved in making the decision to remove the plots too

**Comment by xdustinface** [comment]
> I think it would be good to ask someone involved in making the decision to remove the plots too

Yeah thats why i also requested a review from @almogdepaz initially but it turned out it was @mariano54 who introduced it 🙈

**Comment by mariano54** [comment]
Yes this was done because if you interrupt during creation, bad things happened (you will be stuck with a setup that can no longer run tests properly). Why don't we delete the last plot being created instead of the whole directory?

**Comment by xdustinface** [comment]
@mariano54 I changed the `tmp2_dir` to be `temp_dir` and the interruption now removes the `temp_dir` instead of `plot_dir`.

**Review by arvidn — APPROVED** [review]

**Pull request merged**
