### PR TITLE
Fix plots check output when nbr of challenges < 5

### PR DESCRIPTION
**Pull request by barbem**
$ chia plots check -n 1
16:19:08.526  src.plotting.check_plots         : WARNING  5 challenges is too low, setting it to the minimum of 5
...

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
Thanks!

**Comment by eFishCent** [comment]
Thanks, my bad...

**Comment by eFishCent** [comment]
This fix was regressed in current dev. I have submitted PR 1112 to fix it in latest dev.

**Comment by hoffmang9** [comment]
It was accidentally allowed into main - pulling it out of main was the regress.

**Pull request merged**
