### PR TITLE
Issue #3475

### PR DESCRIPTION
**Pull request by FreeBitcoins-com**
Issue #3475

### CODE REVIEW

**Comment by mariano54** [comment]
It might be good to return the puzzle hash as well, for people who don't have conversion libraries

**Comment by arvidn** [comment]
I would think we would want a unit test for this also, including negative tests.

**Comment by FreeBitcoins-com** [comment]
> I would think we would want a unit test for this also, including negative tests.

Our people mentioned this as well.

**Comment by Nikolaj-K** [comment]
Cool, can you add a more descriptive name

**Comment by emlowe** [comment]
Closing this PR - there was no response to some of the comments - primarily there are missing tests

**Pull request closed without merging**
