### PR TITLE
make BlockTools generate more accurate block timestamps

### PR DESCRIPTION
**Pull request by arvidn**
when generating blocks, we truncate the time-per-block to whole seconds before assigning the timestamp to the next block. When the time-per-block has a fractional part (say, 18.75) the blocks will consistently come 0.75 seconds early.

This patch rounds up or down with a probability proportional to the size of the fractional part. This means blocks will come at the right time on average

### CODE REVIEW

**Review by mariano54 — COMMENTED** [review]
This will change the blocks that are created, and therefore it will not be compatible with the test-cache. We can update test cache.
Also we need to run the tests without the cache to see if they still pass

**Review by mariano54 — CHANGES_REQUESTED** [review]
See above

**Comment by arvidn** [comment]
ah, I see. is it the `tests/blockchain/` tests I should run?
Do we regenerate the cache periodically?

**Comment by mariano54** [comment]
All the tests need to be run.
There is no automatic way to update cache right now

**Comment by arvidn** [comment]
I made the residual deterministic, and optional. This means tests will keep behaving the same, and this new behavior is opt-in.

**Review by mariano54 — APPROVED** [review]
LGTM as long as cached blocks don't change

**Pull request merged**
