### PR TITLE
Atomic swaps example

### PR DESCRIPTION
**Pull request by Quexington**
**Things in this pull request**
- A `.clvm` file added to `src/wallet/puzzles/` that can be used to lock up coins as part of an atomic swap.
- A python module that uses the atomic swap puzzle to provide some basic functionality for creating:
  - Puzzles to lock funds up in a HTLC
  - Solutions to HTLC puzzles for either party involved
  - Spend bundles that spend standard coins to an HTLC
  - Spend bundles that spend coins locked up in an HTLC to a delegated puzzle

**Things NOT in this module**
- Automated tests for the functions (There are commented tests at the bottom of `atomic_swaps.py`)
- Ability to generate spend bundles using input coins of a generalized type
- Any connection to the standard wallet or user interface

### CODE REVIEW

**Comment by hoffmang9** [comment]
I just want to say that your PR rocks. I'm going to leave it to the chialisp experts to do the review here though.

**Review by bramcohen — COMMENTED** [review]
Is this using our standard format transaction with taproot for the failure case? We'd like to demonstrate all the tricks, although that of course requires off-chain communication.

**Comment by Quexington** [comment]
> 
> 
> Is this using our standard format transaction with taproot for the failure case? We'd like to demonstrate all the tricks, although that of course requires off-chain communication.

If I understand your question correctly, no it doesn't. It only requires a signature from the claimer to execute the delegated puzzle.  I forgot about adding the taproot scenario but it should be possible if you change the clvm code to add an `original_public_key` as an argument and then change `prepend_sig_condition` to basically copy the exact implementation as `possibly_prepend_aggsig` from `p2_delegated_or_hidden_puzzle.clvm`.  Then you just have to refactor the python to make sure all relevant functions for generating the solution are accepting the right number of arguments.

I can put that together and then merge it in if that's the preferred implementation.

**Comment by Quexington** [comment]
> 
> 
> > Is this using our standard format transaction with taproot for the failure case? We'd like to demonstrate all the tricks, although that of course requires off-chain communication.
> 
> If I understand your question correctly, no it doesn't. It only requires a signature from the claimer to execute the delegated puzzle. I forgot about adding the taproot scenario but it should be possible if you change the clvm code to add an `original_public_key` as an argument and then change `prepend_sig_condition` to basically copy the exact implementation as `possibly_prepend_aggsig` from `p2_delegated_or_hidden_puzzle.clvm`. Then you just have to refactor the python to make sure all relevant functions for generating the solution are accepting the right number of arguments.
> 
> I can put that together and then merge it in if that's the preferred implementation.

https://github.com/Quexington/chia-blockchain/blob/atomic-swaps-with-taproot/src/wallet/puzzles/atomic_swap.clvm should be a working example (python was slightly modified as well)

**Comment by aqk** [comment]
This is a fantastic example for others to learn from.

One thing to note - please rebase to dev when taking changes from upstream, instead of merging from upstream.

**Comment by Quexington** [comment]
I'm not a git master so apologies if some of the commit history was lost in what I just did there.  Here is a breakdown of the changes I made after some off Github direction:

* I misunderstood bramcohen's comment about using taproot for the failure case.  I thought he wanted taproot added as an option to claim the funds in the failure case.  I understand now that what was actually asked for was for the atomic swap to be the "hidden puzzle" of the standard transaction.  In accordance with this, I added two functions to `atomic_swap.py`: one that gets a standard puzzle with an atomic swap as the hidden puzzle and uses the sum of the two public keys to calculate the synthetic public key, and another that simply gets the hash of that puzzle.
* I deleted the functions that were previously used to generate spend bundles for the atomic swaps since, now that they are primarily used as hidden puzzles, generating spend bundles is more related to standard puzzles rather than atomic swaps alone.
* I added a new file called `test_atomic_swap.py` which defines three functions that should describe the protocol that these swaps will primarily be used in.  One describes the cooperation scenario, one describes the scenario in which either party wishes to claim their funds back with a signature (and after a time lock), and one describes the scenario in which either party wishes to claim the sent funds with a revealed preimage.
* Since that new file exists, I deleted the commented tests at the bottom of `atomic_swap.py`

**Comment by justinengland** [comment]
can you please resubmit this PR to either main, or if it needs to be merged before 3/24/21, new-main, this will allow us to move forward with the new git branching strategy

**Comment by Quexington** [comment]
Re-created here: https://github.com/Chia-Network/chia-blockchain/pull/1469

**Pull request closed without merging**
