### PR TITLE
use a temporary table in RAM for inserting new coins into coin store

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@xorinox I'm measuring a slow-down with this patch. Did you see a material improvement?

before:
```
1503.6170s, MOSTLY ADDITIONS additions: 400400 removals: 20000
584.2903s, MOSTLY REMOVALS additions: 600 removals: 140000
2462.7939s, FULLBLOCKS additions: 400400 removals: 400000
1.2303s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.9298s, GET RECORDS BY NAMES without spent 200 lookups found 20732 coins in total
22.6571s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
```

after:
```
1523.2275s, MOSTLY ADDITIONS additions: 400400 removals: 20000
633.4021s, MOSTLY REMOVALS additions: 600 removals: 140000
2532.3599s, FULLBLOCKS additions: 400400 removals: 400000
1.1939s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.9008s, GET RECORDS BY NAMES without spent 200 lookups found 20681 coins in total
22.4543s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
```

Granted, this is without the fix to make the benchmark deterministic..

**Comment by xorinox** [comment]
My measurements are below. I found it critical to use the updated benchmark to establish reproducible benchmark runs.

Can you comment on CPU/storage device that you used for your testing?

```#SSD original code
Building database
78.3017s, MOSTLY ADDITIONS additions: 400400 removals: 20000
9.2151s, MOSTLY REMOVALS additions: 600 removals: 140000
85.1686s, FULLBLOCKS additions: 400400 removals: 400000
1.4034s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
1.6274s, GET RECORDS BY NAMES without spent 200 lookups found 20669 coins in total
18.5551s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 194.2713s


#SSD bulk insert and mass update
Building database
45.6112s, MOSTLY ADDITIONS additions: 400400 removals: 20000
5.4808s, MOSTLY REMOVALS additions: 600 removals: 140000
57.1782s, FULLBLOCKS additions: 400400 removals: 400000
1.4021s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.9622s, GET RECORDS BY NAMES without spent 200 lookups found 20669 coins in total
19.2544s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 129.8889s


#SPINDLE original code
Building database
917.1889s, MOSTLY ADDITIONS additions: 400400 removals: 20000
325.2917s, MOSTLY REMOVALS additions: 600 removals: 140000
1281.8812s, FULLBLOCKS additions: 400400 removals: 400000
1.3874s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.8687s, GET RECORDS BY NAMES without spent 200 lookups found 20669 coins in total
19.5532s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 2546.1711s


#SPINDLE bulk insert and mass update
Building database
720.6202s, MOSTLY ADDITIONS additions: 400400 removals: 20000`
305.5275s, MOSTLY REMOVALS additions: 600 removals: 140000
1087.8906s, FULLBLOCKS additions: 400400 removals: 400000
1.3928s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.7278s, GET RECORDS BY NAMES without spent 200 lookups found 20669 coins in total
19.3454s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 2135.5043s

**Comment by xorinox** [comment]
@arvidn what made you choose the structure of the try/finally block in _add_coin_records? For example, why is inserting into the temp table not inside the try block?

**Comment by arvidn** [comment]
There is a test that triggers a duplicate coin id error. Without the emptying of the table in a finally clause, those entries would be inserted again, next time we called it he function

**Comment by arvidn** [comment]
I have a very slight improvement now (when running the fixed benchmark):

main:
```
1534.5546s, MOSTLY ADDITIONS additions: 400400 removals: 20000
593.4741s, MOSTLY REMOVALS additions: 600 removals: 140000
2510.7866s, FULLBLOCKS additions: 400400 removals: 400000
1.2366s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.9238s, GET RECORDS BY NAMES without spent 200 lookups found 20669 coins in total
22.3566s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 4663.3324s
```

this patch:
```
1531.3129s, MOSTLY ADDITIONS additions: 400400 removals: 20000
585.0737s, MOSTLY REMOVALS additions: 600 removals: 140000
2505.2083s, FULLBLOCKS additions: 400400 removals: 400000
1.2275s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
0.9293s, GET RECORDS BY NAMES without spent 200 lookups found 20669 coins in total
22.5309s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 4646.2826s

```

**Comment by arvidn** [comment]
I'm not entirely convinced these, quite marginal, performance improvement is worth the additional complexity. I think there are more effective improvements we can make (that would become more complicated by this change)

**Comment by xorinox** [comment]
Have you tried the patch also when the block chain is located on SSD storage? The difference appears to be much greater compared to HDD.

**Pull request closed without merging**
