### PR TITLE
added option to limit nr of worker processes in blockchain.py to reduce memory overhead

### PR DESCRIPTION
**Pull request by grayfallstown**
This pull request aims to improve sync speed and reduce resource consumption while co-farming chia and its forks. For that, it implements an optional config option to limit the nr of worker processes in blockchain.py.

Excerpt from related idea in discussions: https://github.com/Chia-Network/chia-blockchain/discussions/8441:

Currently, blockchain.py uses `os.cpu_count() - 2` to determine the number of workers it should start, see [blockchain.py](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/consensus/blockchain.py#L101).

This becomes a huge problem if you co-farm chia forks as well, as each worker uses about 50 MB of ram and quite a bit of cpu time. With 40+ instances (chia + a lot of the forks) this uses 27+GB of ram for workers alone and slows down syncing a lot, as the 560+ workers fight over the available logical cores. This will allow users to limit the number of workers.

### CODE REVIEW

**Review by KUBOTArig — DISMISSED** [review]

**Review by Taweesakpintakam7m1 — APPROVED** [review]

**Review by Taweesakpintakam7m1 — DISMISSED** [review]
#8472

**Review by jack60612 — COMMENTED** [review]
Lgtm

**Review by Taweesakpintakam7m1 — COMMENTED** [review]
chia/consensus/blockchain.py
chia/util/initial-config.yaml
[README.md](https://github.com/Chia-Network/chia-blockchain/files/7697667/README.md)

**Comment by mariano54** [comment]
This has now been added, it's the reserve_cores setting in the full_node config.

**Pull request closed without merging**
