### PR TITLE
Use Datalayer banning logic for HTTP download failures

### PR DESCRIPTION
**Pull request by emlowe**
Fix bug that when DL http download fails, we didn't properly apply the ban logic

### CODE REVIEW

**Review by fchirica — DISMISSED** [review]

**Comment by emlowe** [comment]
close and reopen

**Review by arvidn — DISMISSED** [review]

**Comment by arvidn** [comment]
@emlowe do you think it's OK to not have test coverage for this? Especially given it turned out to not work right previously

**Comment by emlowe** [comment]
I added a test for this case

**Comment by emlowe** [comment]
close and reopen

**Review by arvidn — APPROVED** [review]

**Pull request merged**
