### PR TITLE
Improve the CI runs w.r.t. timelord installation

### PR DESCRIPTION
**Pull request by AmineKhaldi**
Superficial analysis showed that only two test groups require (for now) installing the timelord.

This change aims to save us hours of CI running time by simply running the install timelord script only for those test groups, with everything else having it omitted.

Dedicated to @hoffmang9

### CODE REVIEW

**Comment by hoffmang9** [comment]
I love the idea. Won't you need to address the templates and CI build scripts in test/?

**Review by hoffmang9 — DISMISSED** [review]
Sometimes you have to put GitHub phone app in landscape. Looks great!

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Review by altendky — APPROVED** [review]
Yay!

**Pull request merged**
