### PR TITLE
Don't import a `wallet` file from `util`.

### PR DESCRIPTION
**Pull request by richardkiss**
### Purpose:

Remove a clear layer violation and slightly generalize the code. Also reduces the cycle count by 2.

### CODE REVIEW

**Review by Quexington — DISMISSED** [review]

**Comment by richardkiss** [comment]
I removed the `IntEnum` case entirely and all the tests still passed. @Quexington had concerns that this code path might be exercised somewhere but the test coverage missed it, so I switched it to `IntEnum`. A concern I have is this changes how we serialize ALL `IntEnum` values besides `WalletType`.

An alternative is to add a `.to_json_dict` method to `WalletType` and make it return `self.name`. This sucks because `self.name` is not a `dict`. The `.to_json_dict` name is very unfortunate and makes this option less palatable than it otherwise might be.

We could add a branch that looks to `.to_json` and add `.to_json` to `WalletType`. Kinda dumb, but seems to be the absolute safest (as long as nothing else implements a `.to_json` which seems pretty unlikely).

**Comment by altendky** [comment]
Yep, yuck.  Happy you're trying to address this situation.

Offhand, I might tend towards just implementing `.to_json_dict()`.  I agree the name is not accurate but I suspect it may simply be overly prescriptive and we could consider changing it at some point to just `.to_json()`.  I don't particularly like our serialization styles like this anyways, but fitting this outlier back into what we generally do now would be a clear improvement in my opinion.  A quick search doesn't show `.to_json()` already used in our code.

Now if only we registered types and their [de]serializers so potential method name conflicts weren't a concern.  `:]`

**Review by arvidn — DISMISSED** [review]

**Review by altendky — CHANGES_REQUESTED** [review]
Just requesting changes so the conversation can finish before this gets merged.

**Comment by Quexington** [comment]
> Yep, yuck. Happy you're ~trying to address~ addressing this situation.
> 
> Offhand, I might tend towards just implementing `.to_json_dict()`. I agree the name is not accurate but I suspect it may simply be overly prescriptive and we could consider changing it at some point to just `.to_json()`. I don't particularly like our serialization styles like this anyways, but fitting this outlier back into what we generally do now would be a clear improvement in my opinion. A quick search doesn't show `.to_json()` already used in our code.
> 
> Now if only we registered types and their [de]serializers so potential method name conflicts weren't a concern. `:]`

Even though it would technically be a change in behavior (not one that I can imagine matters) wouldn't it be nice to support using the enum names for all `IntEnums`?  Rather than having to (in theory probably more so than in practice) implement `.to_json_dict` on something else that we wanted to work this way?

**Comment by richardkiss** [comment]
> > Yep, yuck. Happy you're ~trying to address~ addressing this situation.
> > Offhand, I might tend towards just implementing `.to_json_dict()`. I agree the name is not accurate but I suspect it may simply be overly prescriptive and we could consider changing it at some point to just `.to_json()`. I don't particularly like our serialization styles like this anyways, but fitting this outlier back into what we generally do now would be a clear improvement in my opinion. A quick search doesn't show `.to_json()` already used in our code.
> > Now if only we registered types and their [de]serializers so potential method name conflicts weren't a concern. `:]`
> 
> Even though it would technically be a change in behavior (not one that I can imagine matters) wouldn't it be nice to support using the enum names for all `IntEnums`? Rather than having to (in theory probably more so than in practice) implement `.to_json_dict` on something else that we wanted to work this way?

If there are `IntEnums` that get passed to this `default` function that's changing, their JSON serialization will change. If that exists now, it's a problem because it changes the spec on how messages with `IntEnums` that are not `WalletType` objects are serialized.

I like how rust's `serde` crate does it. Roughly, you define structures as recursive closures of a set of base objects (like `dataclass`), and your data structures know nothing about serialization -- they are just a tree of structures. To serialize, you recursively "visit" the nodes in the graph, which then calls a function specific to serialization method (json? bincode? protobufs?) for that value (and type). This can decouple the definition and the serialization, and you can register new base types with the serializer thing. Deserialization works similarly, with visitors, although obviously it operates on a type + data (like `UInt32` and the string "712") rather than a value (like `712: uint32`). This way you can add new serializations of your objects later without touching the object definitions.

This would be quite a big change though, and I think the `.to_json_dict` is the absolute safest way to deal with this for the moment. Once serialization/"streamable" is really isolated to a library, we could look at changing how it works (although it seems a bit unnecessary since most of it has been moved to `chia_rs` by now).

I'm going to switch to `.to_json_dict`.

**Review by altendky — DISMISSED** [review]

**Review by altendky — APPROVED** [review]

**Review by Quexington — APPROVED** [review]

**Review by arvidn — APPROVED** [review]

**Pull request merged**
