### PR TITLE
Wallet cost

### PR DESCRIPTION
**Pull request by Yostra**

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Comment by jespino** [comment]
@Yostra somebody is seeing `'CCWallet' object has no attribute 'cost_of_single_tx'` can it be related to the absense of the `self.cost_of_single_tx = None` assignation in the `create` method in the `src/wallet/cc_wallet/cc_wallet.py` file?

I think the problem is related to this changes, but I'm not 100% sure.

**Comment by Yostra** [comment]
@jespino Yes, good catch, that is a bug. Do you wanna add that line and PR it?

**Comment by jespino** [comment]
@Yostra sure, I can do it.

**Comment by Yostra** [comment]
Thanks! @jespino

**Comment by jespino** [comment]
Done #1194

**Pull request merged**
