### PR TITLE
Change back constant

### PR DESCRIPTION
**Pull request by jack60612**
Reverts #9130

### CODE REVIEW

**Comment by jack60612** [comment]
Thanks @neurosis69

**Review by mariano54 — APPROVED** [review]

**Comment by wjblanke** [comment]
this isn't going to affect the majority of nodes already out there. the mempool will still be pruned by peers. why are we increasing this again?

**Comment by mariano54** [comment]
We are setting it back to where it was, and I think it should probably be even higher. We want to support sudden bursts of activity like NFT minting, or any other app that incentivizes users to transact quickly. 

Cardano had serious issues because their mempool was too small and most transactions ended up getting dropped.

**Comment by mariano54** [comment]
@wjblanke bump

**Comment by mariano54** [comment]
Is there any reason not to merge this @wjblanke ?

**Comment by altendky** [comment]
I'm removing the `ready_to_merge` label as this is not getting merged right now.  I think a discussion is needed in other venues to identify the path forward.  In the mean time, the `ready_to_merge` list will be cleaner.

**Comment by mariano54** [comment]
There are significant usability issues from keeping a small mempool, and the people most familiar with this code are in favor of merging it. What is the argument for not merging it @wjblanke @altendky ?

**Comment by hoffmang9** [comment]
I am specifically adding ready_to_merge back. This was a temporary regression that is  being held back from reversion without reason for breaking the original design.

If there is a valid test that needs to be completed, then lay it out, or revert back to the constant as shipped on 3/19/21 and 5/3/21.

**Pull request merged**
