### PR TITLE
Rename processes

### PR DESCRIPTION
**Pull request by richardkiss**
This is a non-controversial precursor to removing `setproctitle`. It doesn't actually remove it, but it creates some python commands of the same names that launch the process that we're setting with `setproctitle`.

### CODE REVIEW

**Comment by hoffmang9** [comment]
Also I assume you saw https://github.com/Chia-Network/chia-blockchain/pull/161/checks?check_run_id=574702191#step:6:602 ?

**Comment by richardkiss** [comment]
I removed an extra "start wallet" script.

**Comment by richardkiss** [comment]
> Also I assume you saw https://github.com/Chia-Network/chia-blockchain/pull/161/checks?check_run_id=574702191#step:6:602 ?

This check built, but an older one failed (I did a force push to erase history)... is that what you were referring to in this comment?

**Comment by hoffmang9** [comment]
I was referring to the failed ci around start-wallet-server, yes.

**Review by hoffmang9 — APPROVED** [review]
Looks good and merging.

**Pull request merged**
