### PR TITLE
chia keys show --json (display all keys as json)

### PR DESCRIPTION
**Pull request by kimsk**
Adding `--json` flag to return all keys in json format, so it's easier to process.

```sh
❯ chia keys show --help
Usage: chia keys show [OPTIONS]

Options:
  --show-mnemonic-seed           Show the mnemonic seed of the keys
  -d, --non-observer-derivation  Show the first wallet address using non-
                                 observer derivation. Older Chia versions use
                                 non-observer derivation when generating
                                 wallet addresses.
  -j, --json                     Displays all the keys in keychain as JSON
  -h, --help                     Show this message and exit.
```

### `chia keys show`
image

### `chia keys show --json`
image

### empty keychain
image

### CODE REVIEW

**Comment by paninaro** [comment]
@kimsk This looks great, thanks for the contribution! Can you add a root object to the output that will contain the array? That will make it easier to extend the format in the future as other options are included that affect the output. e.g.

```
{
    'keys': [
        {
            ...<key_data_1>
        },
        {
            ...<key_data_2>
        }
    ]
}
```

**Comment by kimsk** [comment]
@paninaro Thanks for the suggestion! I update the code to output a root object containing the keys array.

### chia keys show --json
image

### empty keychain
image

**Comment by paninaro** [comment]
@kimsk Can you also add a couple of test cases to `tests/core/cmds/test_keys.py` along the lines of `test_show()` and `test_show_mnemonic()` to exercise the json code path?

To run those tests, I use:
`pytest -sv -n 0 tests/core/cmds/test_keys.py`

**Comment by kimsk** [comment]
@paninaro Sounds good! I have added add `test_show_json` and `test_show_mnemonic_json` to test_keys.py.

### Tests
image

**Comment by kimsk** [comment]
The new tests somehow fail. It looks like the `--json` option is not available when tests were run on GitHub. @paninaro any suggestion for me to fix the issue?

https://github.com/Chia-Network/chia-blockchain/actions/runs/3262543510/jobs/5370644878
image

**Comment by kimsk** [comment]
By the way, I look at some of the test cases and I believe they should assert `result.output.find(<value>) != -1` instead.

https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/cmds/test_keys.py#L374
https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/cmds/test_keys.py#L389-L391
https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/cmds/test_keys.py#L548

**Comment by paninaro** [comment]
> By the way, I look at some of the test cases and I believe they should assert `result.output.find(<value>) != -1` instead. I could fix them in this PR if you are ok with it.
> 
> https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/cmds/test_keys.py#L374 https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/cmds/test_keys.py#L389-L391 https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/cmds/test_keys.py#L548

Good point, I agree that it should be checking that find doesn't return -1. I won't object to fixing those checks in this PR :)

**Comment by paninaro** [comment]
> The new tests somehow fail. It looks like the `--json` option is not available when tests were run on GitHub. @paninaro any suggestion for me to fix the issue? Thanks!
> 
> https://github.com/Chia-Network/chia-blockchain/actions/runs/3262543510/jobs/5370644878 image

Yeah this is strange. I pulled your branch and was able to run the tests successfully. I'll ask around a bit.

**Comment by paninaro** [comment]
@kimsk I figured out the issue. There's a bug that the prior tests were ignoring. Take a look at commit https://github.com/Chia-Network/chia-blockchain/commit/1cd88f25cc8d300b352a4108efb1e2ed271abda8 for the changes that I think should get everything working. Would you mind applying that commit to your PR?

**Comment by kimsk** [comment]
@paninaro Thanks! Your changes fixed all the test issues. 
image

**Review by paninaro — APPROVED** [review]
lgtm. Thanks for the contribution!

**Pull request merged**
