### PR TITLE
rework class protocol check pattern

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by arvidn** [comment]
what's the behavior of moving those checks into the class body itself?

**Comment by altendky** [comment]
It makes them located closer to the `class` code where I suspect people would expect it to be.  This should make the pattern more apparent to people (sorta...) and avoid stuff like https://github.com/Chia-Network/chia-blockchain/pull/14991.  In terms of functional change, you get a class var instead of a global (not a big deal) and the `cast()` pattern avoids 'instantiating' the class which makes it more flexible for use with classes that require parameters to be instantiated.

**Review by xdustinface — APPROVED** [review]
> you get a class var instead of a global 

Do we actually _get_ the class var in there since it's only happening `if TYPE_CHECKING`?

**Comment by altendky** [comment]
If you're type checking you do.  `;]`  Which may include IDEs, I'm not sure.

**Review by arvidn — APPROVED** [review]

**Pull request merged**
