### PR TITLE
Add additional partial headers

### PR DESCRIPTION
**Pull request by felixbrucker**
### Purpose:

Expose farmer peer id, full harvester version, harvester capacity (raw/effective) and plot count when submitting a partial.

### Current Behavior:

Currently only the full farmer version and harvester peer id are exposed

### New Behavior:

Farmer and harvester peer id and full version, as well as harvester capacity and plot count are exposed.

### Testing Notes:

Limitation: capacity and plot count are not scoped by plotnft yet, as those are not tracked separately right now in `plot_sync_receivers`. The current lookups are fast as its just a direct variable access, scoping per launcher id/contract address would require additional compute resources without a refactor of how plot_sync_receivers works right now.

- Depends on https://github.com/Chia-Network/chia-blockchain/pull/15679

### CODE REVIEW

**Comment by emlowe** [comment]
Interestingly, RFC 6648 (https://www.rfc-editor.org/rfc/rfc6648) deprecates using `X-` as the beginning nomenclature for new parameters. Perhaps `chia` should be in the name somewhere - maybe `chia-farmer-peer-id`

**Comment by emlowe** [comment]
Some Internal discussion indicates that some of these would be contentious to send by default - I suggest creating a new CHIP to discuss those and they may need to be optional to send

The harvester version itself is likely not controversial - but some of the others eliciting some internal feedback

**Comment by felixbrucker** [comment]
> some of these would be contentious to send by default - I suggest creating a new CHIP to discuss those and they may need to be optional to send

which ones exactly?

**Comment by danieljperry** [comment]
> > some of these would be contentious to send by default - I suggest creating a new CHIP to discuss those and they may need to be optional to send
> 
> which ones exactly?

Farmer peer ID. This might work well as an informational CHIP if there are other clients that could use it. I'm not familiar enough with the pooling protocols to say for sure, though.

**Comment by felixbrucker** [comment]
I don't see how that is contentious in any way, but sure i can create a chip for it

**Comment by felixbrucker** [comment]
The CHIP PR is available here: https://github.com/Chia-Network/chips/pull/114

**Review by almogdepaz — APPROVED** [review]
lgtm

**Comment by BrandtH22** [comment]
Per the conversation in the [chip](https://github.com/Chia-Network/chips/pull/114), the inherent security issues with defaulting the additional headers to not be obfuscated, and the [reduced version](https://github.com/Chia-Network/chia-blockchain/pull/18167) of the pr already adoption; this pr is being closed and not adopted into the chia codebase.

**Pull request closed without merging**
