### PR TITLE
Update pyinstaller version

### PR DESCRIPTION
**Pull request by cmmarslender**
PR for testing installers with the latest pyinstaller version.

@hoffmang9 I think there was something in 4.8 for windows you warned to look out for in testing, but I'm not remembering what it was. Do you remember? [pyinstaller changelog](https://pyinstaller.readthedocs.io/en/stable/CHANGES.html#id2)

### CODE REVIEW

**Comment by hoffmang9** [comment]
Since we're mucking with the final executable's stack size, we need to pay attention to this - https://github.com/pyinstaller/pyinstaller/issues/6459

**Comment by cmmarslender** [comment]
Ok, just did some testing on this. It appears that the stack size we set still applies just fine with the new version of pyinstaller. 

Tested both `1.2.11` and the version from this PR with `dumpbin /headers .\chia.exe` and the results were:

1.2.11:

```
7A1200 size of stack reserve
1000 size of stack commit
100000 size of heap reserve
1000 size of heap commit
```


PR Version:

```
7A1200 size of stack reserve
1000 size of stack commit
100000 size of heap reserve
1000 size of heap commit
```

I also tested making a plot, since the inline comment about the stack size change implies its to enable plotting.. Was able to make a k25 plot with default settings (unsure if the issue applied to all plot sizes or just larger plots?). Plot completed successfully and passed checks with `chia plots check`

**Comment by hoffmang9** [comment]
Can we make a k=32 on Windows with this installer? I expect we're safe but that's the final real test. I'm going to approve under the assumption that will work. We can revert if it does not.

**Review by hoffmang9 — APPROVED** [review]
Ok

**Comment by cmmarslender** [comment]
> Can we make a k=32 on Windows with this installer? I expect we're safe but that's the final real test. I'm going to approve under the assumption that will work. We can revert if it does not.

Yeah I can test this on a VM that isn't running on my main computer - will report back once its complete

**Comment by cmmarslender** [comment]
Alrighty. K32 on windows completed and plot passed check with `Proofs 28 / 30, 0.9333`

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
