### PR TITLE
Use get_type_hints()

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [ ] This probably isn't a super efficient approach what with the function call.

### CODE REVIEW

**Comment by altendky** [comment]
It makes some things better anyways.

**Comment by mariano54** [comment]
We switch from `get_type_hints` to `__annotations__` because it was super slow. Why not use `__dataclass_fields__`?

**Comment by altendky** [comment]
Hence the reason for being draft.  `:]`

I think what we should do is do this once early and hold onto it in the form we want instead of spreading lots of low level api-change-prone accesses all over.  Just in a different way than the last attempt.  This was a quick check so I could see it help with the 3.10 effort and it seems to.  I'll follow up here, or in another PR, with something using `get_type_hints()` or `dataclasses.fields()` and caching the results more like other things are already being held for streamables.

**Comment by hoffmang9** [comment]
Can we close this so that I can delete the branch?

**Pull request closed without merging**
