### PR TITLE
server: Store `Version` objects instead of `str` in `WSChiaConnection`

### PR DESCRIPTION
**Pull request by xdustinface**
### Purpose:

This is just cleaner imo. Now with this PR the default version is `0`. Other way of solving this would be to make `_version: Optional[Version]` and add a 
```
@property
def version(self) -> Version:
   assert self._version is not None
   return self._version
```
and the same for `protocol_version` but i think the 0 version is good enough and comes with less overhead. 

### New Behavior:

No change in behaviour.

### CODE REVIEW

**Comment by emlowe** [comment]
Added a test for `WSChiaConnection:get_version` would eliminate the CI diff failure, as it would test the modified line.

**Comment by wallentx** [comment]
Failure. Coverage is below 100%.
-------------
Diff Coverage
Diff: origin/main...HEAD, staged and unstaged changes
-------------
chia/full_node/weight_proof.py (92.5%): Missing lines 598,979,992
tests/core/custom_types/test_proof_of_space.py (100%)
-------------
Total:   45 lines
Missing: 3 lines
Coverage: 93%
-------------

**Comment by xdustinface** [comment]
@wallentx I think you confused yourself somehow here :)

**Comment by wallentx** [comment]
> 

Lol sorry, I'm testing a bot

**Comment by emlowe** [comment]
Open and Close PR to deal with Snyk error

**Review by emlowe — APPROVED** [review]

**Pull request merged**
