### PR TITLE
do not compile ChiaLisp at import time

### LINKED ISSUE #11257: [Bug] chia in docker container with non-root user won't start / lock file problem / compile_clvm
### Environment
- custom docker image
- chia 1.3.4 compiled from source
- pipenv as venv
- python 3.9.12 (also tested with 3.9.11, 3.9.10)
- **'non-root'** user inside docker, chia runs as user 3981

### Command inside docker container
chia -h
...every chia_* cmd hangs

### Current state
deadlock, chia doesn't show anything. 

### Expected state
help is shown

### Debugging support
- Stack see below
- per try-and-error debugging I can say the problem is the custom user in combination with lock file creation of `compile_clvm`. Maybe the lock file is written to some directory with different permissions. What is this concrete directory?
- with user `root` everything works fine
- until chia 1.3.3 the custom user also worked fine

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia@27d9ea5841a5:/app$ chia -h
^CTraceback (most recent call last):
  File "/opt/chia-blockchain/.venv/bin/chia", line 5, in <module>
    from chia.cmds.chia import main
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/cmds/chia.py", line 18, in <module>
    from chia.cmds.plotters import plotters_cmd
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/cmds/plotters.py", line 2, in <module>
    from chia.plotters.plotters import call_plotters
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/plotters/plotters.py", line 5, in <module>
    from chia.plotters.bladebit import get_bladebit_install_info, plot_bladebit
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/plotters/bladebit.py", line 10, in <module>
    from chia.plotting.create_plots import resolve_plot_keys
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/plotting/create_plots.py", line 10, in <module>
    from chia.daemon.keychain_proxy import KeychainProxy, connect_to_keychain_and_validate, wrap_local_keychain
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/daemon/keychain_proxy.py", line 5, in <module>
    from chia.cmds.init_funcs import check_keys
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/cmds/init_funcs.py", line 10, in <module>
    from chia.consensus.coinbase import create_puzzlehash_for_pk
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/consensus/coinbase.py", line 6, in <module>
    from chia.wallet.puzzles.p2_delegated_puzzle_or_hidden_puzzle import puzzle_for_pk
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py", line 68, in <module>
    from .p2_conditions import puzzle_for_conditions
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/p2_conditions.py", line 17, in <module>
    MOD = load_clvm("p2_conditions.clvm")
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/load_clvm.py", line 106, in load_clvm
    return Program.from_bytes(bytes(load_serialized_clvm(clvm_filename, package_or_requirement=package_or_requirement)))
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/load_clvm.py", line 92, in load_serialized_clvm
    compile_clvm(full_path, output, search_paths=[full_path.parent])
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/load_clvm.py", line 73, in compile_clvm
    with_lock(f"{full_path}.lock", do_compile)
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/util/lock.py", line 39, in with_lock
    time.sleep(0.1)
KeyboardInterrupt
```

### PR DESCRIPTION
**Pull request by bbjubjub2494**
Similar idea as #13478 but for the `load_serialized_clvm` function.

Fixes #11257 for me

### CODE REVIEW

**Comment by lourkeur** [comment]
(we missed one)

**Review by altendky — DISMISSED** [review]
Hey @lourkeur, thanks for catching this and submitting the fix for the layer I missed.

@trepca, this looks right to me but I wanted to make sure you, or a dev of your choice, looks over this as well.

**Comment by wallentx** [comment]
@lourkeur The pre-commit and lint tests are currently failing. Are you able to address those?

**Comment by lourkeur** [comment]
@wallentx my bad, I checked based on `CONTRIBUTING.md`
- [x] `black`
- [x] `isort`
- [x] `mypy`
- [x] `flake8`
- [x] `pylint`

**Comment by lourkeur** [comment]
Would a rebate help with the CI magic?

**Review by trepca — APPROVED** [review]
lgtm, thanks @lourkeur

**Pull request merged**
