### PR TITLE
Added support in CLI to get a new address for the wallet

### PR DESCRIPTION
**Pull request by ignaci0**
Hey, please let me know your thoughts; considering the amount of code I hope it's good enough.

Also; couldn't found related tests.

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
fyi there's already a PR from over a week ago doing the same changes: 
https://github.com/Chia-Network/chia-blockchain/pull/4808 
I hope the open PR's don't reach 100 in July 😅

**Comment by Nikolaj-K** [comment]
fyi there is already a PR from over a week ago doing the same changes: https://github.com/Chia-Network/chia-blockchain/pull/4808 
I hope the open PR's don't reach 100 in June 😅

**Comment by ignaci0** [comment]
@Nikolaj-K, I missed it; otherwise I wouldn't have worked it myself. I hope either of them make it; it's quite a trivial change and it's a pity not to have it for the headless people like us.

**Comment by EHBradford** [comment]
Trying to automate via script the generation of wallet addresses via CLI commands and I am stuck.  My CLI command sequence is this:

  _chia keys generate_and_print_

I take the result, save it to a temp.txt file and create a new key as follows

  _chia keys add -f temp.txt_

Which responds with:  

  Added private key with public key fingerprint ###########
  
  I parse this to obtain the fingerprint and issue the following:
  
    _chia wallet get_address -f ###########_
  
  Which gives me the following response:
  
  No online backup file found,
   Press S to skip restore from backup
   Press F to use your own backup file: 
   
   The need to supply a key press here is negating my ability to automatically obtain a wallet address in a batch file.
   
   Would it be possible to enhance _chia wallet get_address_ to have an skip option, perhaps name it --skip_restore or perhaps --ignore?   Or whatever is appropriate.....
   
   My apologies if this is the wrong venue for bringing this up.  Just a quick hint where the question would be better posed will suffice if I am asking in the wrong place.  Pull Requests?  Or Discussion?  Or here?

**Pull request closed without merging**
