### PR TITLE
replaced concatenation and string formatting to f-strings

### PR DESCRIPTION
**Pull request by igeni**
replaced concatenation and string formatting to f-strings to avoid potential type's mismatch and unify code with rest parts

### Purpose:
replaced concatenation and string formatting to f-strings to avoid potential type's mismatch and unify code with rest parts

### CODE REVIEW

**Comment by emlowe** [comment]
Your commit is unsigned - we only allow signed commits - You will need to resolve this before this can be considered

**Comment by emlowe** [comment]
Closing until commits are signed

**Comment by igeni** [comment]
> Your commit is unsigned - we only allow signed commits - You will need to resolve this before this can be considered

how to sign a commit?

**Comment by hoffmang9** [comment]
Signing GitHub commits: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by hoffmang9** [comment]
Also note that PGP isn't the only path - we tend to find SSH signing easier - https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification

**Comment by igeni** [comment]
Thank you, Gene

**Pull request closed without merging**
