### PR TITLE
Add SIGINT handler

### PR DESCRIPTION
**Pull request by aqk**
Add a SIGINT handler that exits with exit status 0.

### CODE REVIEW

**Comment by hoffmang9** [comment]
I'm pretty sure that the reason that we moved off of using signals is that they basically do not exist on Windows

**Comment by aqk** [comment]
> I'm pretty sure that the reason that we moved off of using signals is that they basically do not exist on Windows

Gotcha, thanks!

**Comment by aqk** [comment]
Closing because this method does not work on windows.

**Comment by mariano54** [comment]
We should make a distinction between the chia services (which run servers etc), and the chia CLI. The chia services are handled by the daemon and use a specific type of signal that works well with windows:
https://github.com/Chia-Network/chia-blockchain/blob/master/src/server/start_service.py#L139

The CLI currently does not have any signal handling, and we haven't really needed it because the commands execute quickly. However, it would not be a bad idea to catch the signals even if it's only mac/linux support.

**Pull request closed without merging**
