### PR TITLE
Remove Azure MacOS CI build

### PR DESCRIPTION
**Pull request by hoffmang9**
After thinking over the weekend and reviewing the chia-blockchain MacOS build process - we can dump the azure build flow for MacOS. The risk to Mojave is being handled in chiapos wheel building with an xcode target and that's been working fine for both installers.

Note that the release CI will likely need changes to promote the GH MacOS flow to the Download page @cmmarslender @justinengland

### CODE REVIEW

**Comment by cmmarslender** [comment]
Can't merge this yet - need to rework the GHA parts - I have a branch in progress for that as we speak...

**Review by cmmarslender — DISMISSED** [review]
Approved - #10232 will need to be merged as well

**Comment by hoffmang9** [comment]
Isn't there some fancy new PR queueing in GH?

**Comment by cmmarslender** [comment]
> Isn't there some fancy new PR queueing in GH?

Last I checked, it was beta and you had to request access. We requested access a while back and haven't received it yet (unless its now GA, and I missed that somewhere)

**Review by justinengland — DISMISSED** [review]

**Review by cmmarslender — DISMISSED** [review]

**Review by justinengland — APPROVED** [review]

**Pull request merged**
