### PR TITLE
Remove accidental parameters from calls to setup_simulators_and_walle…

### PR DESCRIPTION
**Pull request by aqk**
…ts and prevent future mistakes

### CODE REVIEW

**Comment by altendky** [comment]
Looks like CI is maybe working again.  Closing and reopening to hopefully trigger a run.

**Comment by arvidn** [comment]
is `True` really implicitly converted to an `int` in python?

**Review by arvidn — APPROVED** [review]

**Review by arvidn — DISMISSED** [review]

**Comment by aqk** [comment]
Thanks - I'm glad I split this out.

In an earlier patch, I was going to preserve the `starting_height=1`, but after re-reading the named arguments a few more times, and reading some of the tests that use that fixture, I'm pretty sure this wasn't intended.

**Comment by altendky** [comment]
> is `True` really implicitly converted to an `int` in python?

It isn't "converted", rather it _is_ an `int` of value 1.  `bool` inherits from `int`.  For better or worse...

```pycon
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> type(True)
<class 'bool'>
>>> bool.__mro__
(<class 'bool'>, <class 'int'>, <class 'object'>)
>>> True == 1
True
```

**Review by altendky — APPROVED** [review]
From what I've heard the M1 failure is already being discussed separately.

**Pull request merged**
