### PR TITLE
Remove unnecessary at_full_capacity call

### PR DESCRIPTION
**Pull request by Nikolaj-K**
The `is_fee_enough` makes an (depending on the block) unnecessary call of `mempool.at_full_capacity` and a potentially unnecessary division. 

This is because if `at_full_capacity` is false, then `get_min_fee_rate` returns the float `0.0`, which can instead be checked against.
If `at_full_capacity` is true, then `get_min_fee_rate` must be called anyway.

The `at_full_capacity` is relatively cheap, but it makes the function a bit deeper than it could be.
Note: In the case of both full capacity `fees_per_cost >= self.nonzero_fee_minimum_fpc` is true, this change would lead to computation of the the true clause in get_min_fee_rate that otherwise would not be computed, so the benefit is still case dependent - you judge what situation it a better tradeoff. In that sense it's a proposal and you guys must judge the tradeoff. 
The function can be cleaned up either way, one way or the other.

----

This doesn't change the extensional behaviour, although I feel one possibly could:
* Why is not a multiplications performed instead of a uint64 division?
* Why is one check a `>` and one a `>=`? Given they are called minima, I feel like both should become `>=`?

### CODE REVIEW

**Comment by mariano54** [comment]
This changes the behaviour. Consider the case where the mempool is full but the min fee rate is 0.0. In this case, we cannot let the transaction into the mempool, because this allows attacks where people spam the mempool with 0 fee transactions. Therefore the behaviour should be different based on whether the mempool is full or not.

**Comment by Nikolaj-K** [comment]
@mariano54 Okay, then I misunderstand that this return
https://github.com/Chia-Network/chia-blockchain/blob/59de4ffe9f98de62d281695d1f519d65ef2e2ece/chia/full_node/mempool.py#L33
can end up with 0 even in the loop?

**Comment by Nikolaj-K** [comment]
Closed since wrong early exit possible in this refactor.

**Comment by Nikolaj-K** [comment]
I take it there's none yet but might be added eventually

**Pull request closed without merging**
