### PR TITLE
remove setproctitle

### PR DESCRIPTION
**Pull request by richardkiss**
Tests haven't passed yet, but in principle it should work.

### CODE REVIEW

**Review by hoffmang9 — COMMENTED** [review]
image
That's an Ubuntu 19.10 Timelord

**Comment by richardkiss** [comment]
Thanks for trying, I'll dig deeper.

**Comment by mariano54** [comment]
It would be great to get rid of setproctitcle. But it's important that we are able to shut down the node before starting. Running two nodes at once would cause issues. Also on windows, setproctitle won't work.

**Comment by richardkiss** [comment]
My subsequent tests suggests this patch does work on Ubuntu 19, and so probably any linux since this is a kernel feature. Maybe it changed in a kernel. The idea is launching `python -m module` yields `python` in top, but running a script named `module` with `#!/path/to/python` yields `module` in top.

**Comment by mariano54** [comment]
On mac what is displayed? As long as the string includes "chia_" we are fine, right?

**Comment by richardkiss** [comment]
Rebased to master.

**Comment by richardkiss** [comment]
Rebased to beta-1.4.

**Comment by richardkiss** [comment]
@hoffmang9 This is ready for test, you want to see if it meets your needs>

**Comment by hoffmang9** [comment]
image
Ubuntu 19.10

**Comment by richardkiss** [comment]
@hoffmang9 I don't get it, it worked on my Ubuntu 19.10 installation. How are you installing? How are you launching the node? What are you passing to `top` or whatever?

**Comment by richardkiss** [comment]
Looks like `htop`?

**Comment by richardkiss** [comment]
Okay, `htop` vs `top` seems to be the problem.

**Comment by hoffmang9** [comment]
You've only solved for top. ps is also a mess:
```
(venv) hoffmang@ip-172-31-8-127:~/chia-blockchain$ ps ax | grep chia
 1219 pts/0    Rl     0:10 /home/hoffmang/chia-blockchain/venv/bin/python3.7 /home/hoffmang/chia-blockchain/venv/bin/chia_full_node --port=8444 --connect_to_farmer=True --connect_to_timelord=True --rpc_port=8555
(venv) hoffmang@ip-172-31-8-127:~/chia-blockchain$
```

**Comment by mariano54** [comment]
Can I close this PR? It is out of date considering the latest daemon changes @richardkiss

**Comment by mariano54** [comment]
Closing due to inactivity

**Pull request closed without merging**
