### PR TITLE
fail for under 100% diff coverage

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
Let's try! :)

**Review by AmineKhaldi — APPROVED** [review]
How come CI isn't failing on this?

**Comment by arvidn** [comment]
I take it it only counts coverage of new or changed lines of code

**Review by arvidn — APPROVED** [review]

**Comment by arvidn** [comment]
how would one access the test coverage report?

**Comment by altendky** [comment]
Yes, this should fail if any of the lines changed by the PR are not covered in the test runs.

The diff coverage output is available at the end of the test workflow run summary page.  Scroll down at https://github.com/Chia-Network/chia-blockchain/actions/runs/4745370430 for example.  Yes, it's not great.  The HTML output is better than the markdown, but then I need a place to present the HTML.  If you go to the coverage job there https://github.com/Chia-Network/chia-blockchain/actions/runs/4745370430/jobs/8428586350 you can look at the coverage report steps for the console output.

**Comment by altendky** [comment]
We could certainly require 100% coverage overall, but then we wouldn't get a PR merged for a couple months maybe.  And...  it would be impossibly huge.

**Pull request merged**
