### PR TITLE
fix mempool TX cache cost

### LINKED ISSUE #7720: Mempool corruption causes node bans/disconnects - was Cannot farm
One the appearance everything on GUI seems normal, but pool's estimated space keep dropping, last partial submitted was long time ago and then I check log around the time of last submitted partial and see ERROR:

2021-07-21T19:42:23.897 full_node full_node_server        : ERROR    Exception: list index out of range, {'host': '198.72.183.54', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 229, in respond_transaction
  File "chia\full_node\full_node.py", line 1649, in respond_transaction
  File "chia\full_node\mempool_manager.py", line 415, in add_spendbundle
  File "chia\full_node\mempool_manager.py", line 483, in add_to_potential_tx_set
IndexError: list index out of range

2021-07-21T19:42:23.899 full_node full_node_server        : ERROR    Exception: list index out of range <class 'IndexError'>, closing connection {'host': '198.72.183.54', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 229, in respond_transaction
  File "chia\full_node\full_node.py", line 1649, in respond_transaction
  File "chia\full_node\mempool_manager.py", line 415, in add_spendbundle
  File "chia\full_node\mempool_manager.py", line 483, in add_to_potential_tx_set
IndexError: list index out of range

### PR DESCRIPTION
**Pull request by arvidn**
The cost of the mempool TX cache (for spend bundles that can't be included in a block yet) would not be reset when the cache was emptied.

This needs a test as well.

### CODE REVIEW

**Review by emlowe — DISMISSED** [review]
This seems correct to me. It would be nice to have a test for this as well.

**Comment by wjblanke** [comment]
I think Arvid still had some changes to make. Arvid let us know when this can go in

**Comment by arvidn** [comment]
writing a test was a bit more complicated than I anticipated.

**Comment by arvidn** [comment]
our test infrastructure makes it complicated to write an end-to-end test exercising this part of the mempool. Instead I factored out the pending transaction cache to allow it to be unit tested. I made sure that the test exercised the bug that was fixed as well.

**Review by emlowe — DISMISSED** [review]

**Review by emlowe — APPROVED** [review]
Looks good

**Pull request merged**
