### PR TITLE
clean up various aspects of the code 

### PR DESCRIPTION
**Pull request by jack60612**
Ready for merge
Remove unused variables
removed pointless parentheses
simplified code
removed extra lines

### CODE REVIEW

**Review by mariano54 — CHANGES_REQUESTED** [review]
What lint settings are you using? We use 120 line length. it seems like your linter is misconfigured

**Comment by jack60612** [comment]
Setup all the local testing now so it should be easy now

**Comment by jack60612** [comment]
> One reason for having automated code tools like black and mypy is to standardize without arguments over style. From what I can tell, the majority of these changes are unrelated to our lint tools.

Originally it was lint but it ended up being more like best practice improvements.
Do you have a better name for the pull request then?

**Comment by jack60612** [comment]
Mostly Used a bunch of [Static methods](https://docs.python.org/3/library/functions.html#staticmethod) they technically improve performance (in the matter of ns) but they are mostly there for easier code readability

**Comment by arvidn** [comment]
I think this PR is too big and does too many things. It would be easier to review if you would split it up into smaller PRs, then it's easier to accept non-controversial changes without first having to reach consensus on everything.

**Comment by jack60612** [comment]
> I think this PR is too big and does too many things. It would be easier to review if you would split it up into smaller PRs, then it's easier to accept non-controversial changes without first having to reach consensus on everything.

ok i'll look into doing that.

**Comment by jack60612** [comment]
> I think this PR is too big and does too many things. It would be easier to review if you would split it up into smaller PRs, then it's easier to accept non-controversial changes without first having to reach consensus on everything.

Do you have any suggestions on splitting it up.
I do personally find the changes non controversial

**Comment by arvidn** [comment]
> Do you have any suggestions on splitting it up.

Maybe one PR per item in the list, where you describe what changes you made.

**Review by altendky — CHANGES_REQUESTED** [review]
Even aside from controversy, many of the changes touch lots of places and when they get interleaved together you have to context switch on every change you look at.  Also, if any issues are found later then you have to dissect the commit rather than just trying each separately.

Splitting it shouldn't be too bad.  Start a new branch, bring up a visual diff against the old, click the button in your differ to push whatever group of changes to the new branch.  Repeat for each group.

**Comment by jack60612** [comment]
Making this 2nd group separate

**Comment by jack60612** [comment]
> Making this 2nd group separate - ill remove the  @staticmethod and work on the other branch later

Let me know if that is enough splitting or if you want more

**Comment by jack60612** [comment]
@altendky do you want me to remove all static method conversions?

**Comment by altendky** [comment]
The methods that don't use `self` might need more consideration if they were intended to be part of inheritance.  If so, then they still need to be stored as an attribute.  Hopefully not, inheritance is easy to do and _hard_ to 'get right'.  So mostly, I'm not super interested in digging into that for this many cases right now.  Is there a setting for one of the linters that we could keep in mind to catch these later when we do want to dig into them?

**Pull request closed without merging**
