### PR TITLE
Move DB test to new directory

### PR DESCRIPTION
**Pull request by aqk**

### CODE REVIEW

**Review by arvidn — DISMISSED** [review]
is this to make it cheaper to re-run?

**Comment by aqk** [comment]
Yes, just to make it quicker to re-run. Thanks!

**Comment by Gbolahan657** [comment]
If you really need someone to help you mailto: hackerdecon936@gmail.com now

**Review by wjblanke — DISMISSED** [review]
aok

**Comment by wallentx** [comment]
@aqk this has unsigned commits. You should be able to interactive rebase, edit the commit, and `git commit --amend '-S', and then `git rebase --continue`. Might require a `git push --force-with-lease` after.

**Review by wallentx — APPROVED** [review]
Tested verified signoff
(I wanted to verify we could, but this is not what we would want to actually do)

**Comment by aqk** [comment]
@wallentx Thank you

**Review by trepca — APPROVED** [review]

**Pull request merged**
