### PR TITLE
Factors out loading one plot, and no longer uses shared mutable state…

### PR DESCRIPTION
**Pull request by mariano54**
… between all the threads.

This fixes some flaky tests (harvester and farmer rpc duplicate plots check).

This is passing except for ARM64 which is broken on all branches

### CODE REVIEW

**Comment by wbendick** [comment]
I benchmarked this PR, It ran 4-5 times slower than the version in main

**Comment by mariano54** [comment]
Thanks, which benchmark did you run?

**Comment by mariano54** [comment]
I just ran with main and with this branch with 498 k22 plots and saw the same results.

```
2021-04-13T19:54:45.558 harvester harvester_server        : DEBUG    Time taken to process harvester_handshake from eb03ea2926a8f253626e9ab5992f4362477ec36a8d40a95b5ceb82218ef3d6cf is 1.551229476928711 seconds
```

Can you describe how you replicated the slowness?

**Comment by wbendick** [comment]
I timed running chia check plots on a harvester with ~30k plots on ~1k disks

**Comment by mariano54** [comment]
Did you account for the fact that stuff is getting cached on disk when running `chia check plots` twice in a row? Need to run it 4 times instead

**Comment by wbendick** [comment]
I ran it twice

**Comment by mariano54** [comment]
Closing since @xdustinface has refactored this code.

**Pull request closed without merging**
