### PR TITLE
Issues found in RPC API review

### PR DESCRIPTION
**Pull request by ChiaMineJP**

### CODE REVIEW

**Comment by emlowe** [comment]
Looks like `"mempool_size": 0` was removed in https://github.com/Chia-Network/chia-blockchain/pull/9974 - however, doesn't seem any rationale for it .

**Comment by ChiaMineJP** [comment]
> Looks like `"mempool_size": 0` was removed in #9974 - however, doesn't seem any rationale for it .

I'll ask @Quexington for reviewing.

**Review by Quexington — APPROVED** [review]
This looks good to me, but I didn't remove the mempool_size thing (at least not that I know of)

**Comment by ChiaMineJP** [comment]
> This looks good to me, but I didn't remove the mempool_size thing (at least not that I know of)

Sorry, I should have investigated further...

**Pull request merged**
