### PR TITLE
Migrate to testnet. increase weight proof recent blocks, and increase…

### PR DESCRIPTION
**Pull request by mariano54**
* testnet folder under .chia
* don't ban localhost
* recent blocks increased to 1000
* Increase RAM usage to realistic mainnet levels
* selected network is now testnet6

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
Init.py still needs updating, right?

**Comment by mariano54** [comment]
init.py uses DEFAULT_ROOT

**Comment by hoffmang9** [comment]
I'll review init.py anyway because we may look for the folders to migrate from in testnet now and of course they aren't there.

**Review by hoffmang9 — APPROVED** [review]
And done.

**Pull request merged**
