### PR TITLE
add get_version to daemon wss endpoint

### PR DESCRIPTION
**Pull request by dkackman**
This PR adds the ability to get the chia version via the daemon rpc interface. This is helpful in remote management scenarios.

(black reformatted one unrelated function in daemon/server/py. I'm happy to include that reformat but didn't want to mix two unrelated things)

### CODE REVIEW

**Review by jack60612 — DISMISSED** [review]
lgtm

**Comment by dkackman** [comment]
> 
> 
> Hey Don, I was going to merge this but should really have a test as well. We are trying to enforce tests for new RPCs. Could u add one and it will go in next release. Cheers, Bill

Trying to add test to `tests/core/daemon/test_daemon.py`.

`py.test ./tests/core/daemon -s -v` outputs:

```bash
======================================================================================================= ERRORS =======================================================================================================
____________________________________________________________________________________ ERROR collecting core/daemon/test_daemon.py _____________________________________________________________________________________
ImportError while importing test module '/home/don/src/github/dkackman/chia-blockchain/tests/core/daemon/test_daemon.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/core/daemon/test_daemon.py:3: in <module>
    from tests.block_tools import BlockTools, create_block_tools, create_block_tools_async
E   ModuleNotFoundError: No module named 'tests'
============================================================================================== short test summary info ===============================================================================================
ERROR tests/core/daemon/test_daemon.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================== 1 error in 0.18s =================================================================================================
```

Am in then `venv` and have executed the steps in `run-py-tests.sh`.

This seems like the logical place to put this test. Any guidance?

**Comment by dkackman** [comment]
> 
> 
> Hey Don, I was going to merge this but should really have a test as well. We are trying to enforce tests for new RPCs. Could u add one and it will go in next release. Cheers, Bill

@wjblanke  done

`tests/core/daemon/test_daemon.py` doesn't seem like it's in a working state - or at least i couldn't get it to run successfully, so I added a new `test_daemon_rpc.py` in the core folder. Happy to move it elsewhere if that makes more sense.

**Review by wjblanke — DISMISSED** [review]
aok

**Pull request merged**
