### PR TITLE
Improve testnet connectivity.

### PR DESCRIPTION
**Pull request by fchirica**
Improve network connectivity by restricting peers running default network port of another network (i.e. testnet nodes running 8444). additionally, we don't propagate those peers either.

### CODE REVIEW

**Comment by emlowe** [comment]
Just to check, this doesn't require me to run mainnet on 8444 right? I can still run mainnet or testnet on any port I want with the exception of the default port for another network.
That is, I can run mainnet on anything OTHER THAN 58444
And I can run testnet on anything OTHER THAN 8444

**Comment by hoffmang9** [comment]
It looks like if you set your mainnet port to 8446 then you wouldn't gossip and 8444 addresses - but maybe I'm missing something

**Comment by fchirica** [comment]
> It looks like if you set your mainnet port to 8446 then you wouldn't gossip and 8444 addresses - but maybe I'm missing something

in case the port is 8446, it'll miss from `NETWORK_ID_DEFAULT_PORTS`, making `_peer_has_wrong_network_port` return False. so the code will work as before in that case.

**Comment by emlowe** [comment]
The idea is that every port should work for `mainnet` EXCEPT 58444 which is the default `testnet` port. And every port should work for `testnet` EXCEPT 8444 which is the default `mainnet` port.

But at first read, I had the same question.

**Comment by emlowe** [comment]
Should I expect my node to continue to try to connect to these peers? I am testing this branch and I still see my `testnet` 
node trying to connect to other peers on 8448

**Review by emlowe — APPROVED** [review]
Approved, but this will take some time before it actually helps anyone

**Pull request merged**
