### PR TITLE
exploring loop test adjustments

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by arvidn** [comment]
what's the objective with this patch?

**Comment by arvidn** [comment]
this test consistently fail on my computer, because I run a chia full node.

```
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8444): address already in use
```

**Comment by altendky** [comment]
> what's the objective with this patch?

I hope the result is to make these tests more deterministic, less timing sensitive.  In so doing i felt comfortable reducing the repetition and connection counts so the tests could complete in less time.  We may well also want a test more like what this is changing away from but it might belong on the benchmark runner instead.

I'll take a look at the failure you also pointed out.

**Review by arvidn — APPROVED** [review]

**Comment by altendky** [comment]
The address in use issue is pre-existing.  I'll follow up on that.

**Pull request merged**
