### PR TITLE
Move simulator tests over to new file, to allow other programs to use it

### PR DESCRIPTION
**Pull request by jack60612**
@cameroncooper requested this, in order to make it easier for other tools to use the simulator.  #12703 merged so now ready

### CODE REVIEW

**Comment by jack60612** [comment]
rebased

**Comment by jack60612** [comment]
rebased again, 12703 is getting merged soon, so pr should be ready soon

**Comment by jack60612** [comment]
last rebase was cherry pick to main, too many rebases

**Review by paninaro — APPROVED** [review]
lgtm

**Pull request merged**
