### PR TITLE
reusable workflow for a single test workflow

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [x] Review redundancy between `runs` configuration and matrix excludes

### CODE REVIEW

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/runs/6682244657?check_suite_focus=true
```
================================== FAILURES ===================================
______ TestFileKeyringSynchronization.test_writer_lock_released_on_abort ______
[gw0] win32 -- Python 3.8.10 d:\a\chia-blockchain\chia-blockchain\venv\scripts\python.exe
tests\util\keyring.py:73: in inner
    return method(self, *args, **kwargs)
tests\core\util\test_file_keyring_synchronization.py:434: in test_writer_lock_released_on_abort
    assert lock.acquire_write_lock(timeout=(2)) is True
E   assert False is True
E    +  where False = <bound method _InterProcessReaderWriterLock.acquire_write_lock of <fasteners.process_lock._WindowsInterProcessReaderWriterLock object at 0x0000020358F0ED00>>(timeout=2)
E    +    where <bound method _InterProcessReaderWriterLock.acquire_write_lock of <fasteners.process_lock._WindowsInterProcessReaderWriterLock object at 0x0000020358F0ED00>> = <fasteners.process_lock._WindowsInterProcessReaderWriterLock object at 0x0000020358F0ED00>.acquire_write_lock

During handling of the above exception, another exception occurred:
tests\util\keyring.py:73: in inner
    return method(self, *args, **kwargs)
tests\util\keyring.py:193: in __exit__
    self.cleanup()
tests\util\keyring.py:205: in cleanup
    shutil.rmtree(self.keychain._temp_dir)
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\shutil.py:740: in rmtree
    return _rmtree_unsafe(path, onerror)
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\shutil.py:618: in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\shutil.py:616: in _rmtree_unsafe
    os.unlink(fullname)
E   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\test_keyring_wrapper7odh2o5v\\.keyring.yaml.lock'
```

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/runs/6691092193?check_suite_focus=true
```
================================== FAILURES ===================================
___________ TestPoolWalletRpc.test_absorb_pooling[trusted_and_fee1] ___________
[gw0] win32 -- Python 3.9.13 D:\a\chia-blockchain\chia-blockchain\venv\scripts\python.exe
tests\pools\test_pool_rpc.py:757: in test_absorb_pooling
    ret = await client.pw_absorb_rewards(2, fee)
chia\rpc\wallet_rpc_client.py:337: in pw_absorb_rewards
    reply = await self.fetch(
chia\rpc\rpc_client.py:49: in fetch
    raise ValueError(res_json)
E   ValueError: {'error': 'Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.', 'success': False}
```

**Review by cmmarslender — DISMISSED** [review]

**Review by cmmarslender — DISMISSED** [review]

**Review by emlowe — DISMISSED** [review]

**Review by wjblanke — DISMISSED** [review]
aok

**Review by emlowe — APPROVED** [review]
seems all good to me

**Pull request merged**
