### PR TITLE
Fix regression plots check output < 5 correctly; original fix PR 1105

### PR DESCRIPTION
**Pull request by eFishCent**
PR 1105 fix has regressed due to updated check_plots.py code over writing PR 1105.
Making fix permanent in dev.

### CODE REVIEW

**Comment by hoffmang9** [comment]
Thank you @barbem also!

**Review by hoffmang9 — APPROVED** [review]
looks good

**Comment by barbem** [comment]
Thanks, please keep the name of authors when you merge.

**Comment by barbem** [comment]
If I understand, I must open a poll request to dev instead of main?

**Comment by hoffmang9** [comment]
Yes. We make all the pre-release changes in dev. Main is basically just a holding pen for the last release.

**Pull request merged**
