### PR TITLE
Must force a flush here so reloaded cache doesn't have bogus values

### PR DESCRIPTION
**Pull request by wjblanke**
### Purpose:

Ensure cache coherency of height to hash

### Current Behavior:

Node could return orphaned blocks due to reorgs

### New Behavior:

Reorgs flush out height to hash cache

### Testing Notes:

Must force reorg, restart, then query block

### CODE REVIEW

**Review by arvidn — COMMENTED** [review]
when the node starts up, this cache is verified against the blockchain database and patched up in case of any discrepancy. I don't see how this could make any real difference

**Comment by wjblanke** [comment]
arvid, on startup the cache is fixed up by taking the database and going down until you hit the top of the cache right?
if the top of the cache is bogus, due to an unflushed reorg, those blocks are orphans and not correct

**Comment by arvidn** [comment]
> arvid, on startup the cache is fixed up by taking the database and going down until you hit the top of the cache right?

Oh, not quite. it starts at the peak and moves down the chain until the cache matches the database. i.e. after the fixup, the cache is expected to match the DB. Since the DB is the authoritative source of our state, that should be sufficient.

> if the top of the cache is bogus, due to an unflushed reorg, those blocks are orphans and not correct

If the top of the chain in the DB are the same orphaned blocks, that's OK. Then we'll reorg once we find a better peak.
If the DB peak have different blocks than the cache, the cache will be updated to match.

**Comment by wjblanke** [comment]
> > arvid, on startup the cache is fixed up by taking the database and going down until you hit the top of the cache right?
> 
> Oh, not quite. it starts at the peak and moves down the chain until the cache matches the database. i.e. after the fixup, the cache is expected to match the DB. Since the DB is the authoritative source of our state, that should be sufficient.
> 
> > if the top of the cache is bogus, due to an unflushed reorg, those blocks are orphans and not correct
> 
> If the top of the chain in the DB are the same orphaned blocks, that's OK. Then we'll reorg once we find a better peak. If the DB peak have different blocks than the cache, the cache will be updated to match.

Ya i see that now
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/full_node/block_height_map.py#L175

ok looking at other areas

**Pull request closed without merging**
