### PR TITLE
default new installs to use v2 blockchain database schema

### PR DESCRIPTION
**Pull request by arvidn**
Leave an option to initialize a v1 database

### CODE REVIEW

**Comment by arvidn** [comment]
the filename of the database file currently have the version number in it. The option in this PR to create a v1 database doesn't attempt to change the filename in the config file. Should it?

**Comment by aqk** [comment]
Yes, if they use `--v1-db`, it's reasonable to assume they want to set that DB as the active one in the config.
If you do add that, make sure to add a print statement like "setting DB version v1 in config"

**Comment by arvidn** [comment]
@aqk well, I made that change, but I'm not printing any messages about it

**Review by wjblanke — APPROVED** [review]
aok

**Review by jack60612 — APPROVED** [review]
YAY

**Pull request merged**
