### PR TITLE
Use the new 2 argument form of substr 

### PR DESCRIPTION
**Pull request by aqk**
Use the new 2 argument form of substr from clvm 0.9.5 for a smaller deserializer

This is tested in https://github.com/Chia-Network/chia-blockchain/blob/main/tests/clvm/test_chialisp_deserialization.py

### CODE REVIEW

**Review by richardkiss — APPROVED** [review]
Looks good!

**Comment by hoffmang9** [comment]
Is this compatible with the running mainnet?

**Comment by hoffmang9** [comment]
I meant running main branch testnet...

**Comment by aqk** [comment]
Yes, this is compatible.

**Pull request merged**
