### PR TITLE
tests: Make sure pool plots getting removed from `BlockTools` at the end

### PR DESCRIPTION
**Pull request by xdustinface**
Prior to this PR the pool plots created by the pool tests were not removed from the global `BlockTools.expected_plots` if the test failed which happens here and there because they are flaky. Since the global `BlockTools` obviously outlives the parameterization of a test (i.e. in `test_absorb_pooling`) there were many CI runs stucking at:

```
2022-01-30T23:25:54.0633324Z 23:25:54 chia.plotting.manager: ERROR _refresh_callback raised:  with the traceback: Traceback (most recent call last):
2022-01-30T23:25:54.0634415Z 2022-01-30T23:25:54.063 full_node chia.plotting.manager   : [31mERROR   [0m _refresh_callback raised:  with the traceback: Traceback (most recent call last):
2022-01-30T23:25:54.0635521Z   File "/home/runner/work/chia-blockchain/chia-blockchain/chia/plotting/manager.py", line 281, in _refresh_task
2022-01-30T23:25:54.0636160Z     self._refresh_callback(PlotRefreshEvents.batch_processed, batch_result)
2022-01-30T23:25:54.0636916Z   File "/home/runner/work/chia-blockchain/chia-blockchain/tests/block_tools.py", line 178, in test_callback
2022-01-30T23:25:54.0682983Z     assert update_result.remaining == len(self.expected_plots) - self.total_result.processed
2022-01-30T23:25:54.0683833Z   File "/home/runner/work/chia-blockchain/chia-blockchain/chia/plotting/manager.py", line 281, in _refresh_task
2022-01-30T23:25:54.0684293Z AssertionError
```

And getting canceled after a long time like here after ~40min https://github.com/Chia-Network/chia-blockchain/runs/5007793256?check_suite_focus=true.

This PR introduces the class `TemporaryPoolPlot` which provides an async context manager which creates the plot on entry and removes it on exit.

Note: Hide Whitespace changes :)

### CODE REVIEW

**Comment by arvidn** [comment]
it still seems to be unreliable: https://github.com/Chia-Network/chia-blockchain/runs/5014939996?check_suite_focus=true#step:12:23111

**Review by arvidn — COMMENTED** [review]
looks good. but are there more places this new context manager should be used?

**Comment by xdustinface** [comment]
> it still seems to be unreliable: https://github.com/Chia-Network/chia-blockchain/runs/5014939996?check_suite_focus=true#step:12:23111

Yes they are but this is not related to the plot loading and this PR isn't trying to fix the flakiness. It fixes the issue that if one test fails the whole test action gets stuck like you see in the one i linked in the initial description. Now in the link you sent you can see the actual issue which leads to the flakiness: 

```
>       await time_out_assert(
            5,
            full_node_api.full_node.mempool_manager.get_spendbundle,
            absorb_tx.spend_bundle,
            absorb_tx.name,
        )
E       AssertionError: Timed assertion timed out after 5 seconds
```

> looks good. but are there more places this new context manager should be used?

Not really or what places do you think about?

**Comment by xdustinface** [comment]
@arvidn Okay again, like i said in https://github.com/Chia-Network/chia-blockchain/pull/10052#issuecomment-1026403871: Those failures are **not** related to here and this PR is **not** here to fix the flakiness of the tests.

> just some place that might prevent these failures:
> 
> ```
> FAILED tests/pools/test_pool_rpc.py::TestPoolWalletRpc::test_absorb_pooling[0-False]
> FAILED tests/pools/test_pool_rpc.py::TestPoolWalletRpc::test_absorb_pooling[10-False]
> ```

^ Those were there before this PR but you couldn't see them in the logs because `pytest` was hanging in the nowhere.

This PR only makes sure the tests complete gracefully even if one of them fails. Maybe read the initial description + my last comment again, and compare the log output of this (without this PR i.e. it stucks) https://github.com/Chia-Network/chia-blockchain/runs/5007793256?check_suite_focus=true with this (with this PR i.e. it fails gracefully and you see the actual test failures) https://github.com/Chia-Network/chia-blockchain/runs/5014939996?check_suite_focus=true#step:12:23111.

**Review by arvidn — APPROVED** [review]

**Review by jack60612 — APPROVED** [review]
lgtm

**Pull request merged**
