### PR TITLE
Added compression level and harvesting mode to harvester protocol/mes…

### PR DESCRIPTION
**Pull request by ChiaMineJP**
This PR is a partial PR cut from cmj.plot2_0 branch.

### CODE REVIEW

**Comment by emlowe** [comment]
I believe `get_harvester_config` and `update_harvester_config` need tests (I might suggest `test_farmer_harvester_rpc.py`)

**Review by emlowe — CHANGES_REQUESTED** [review]
I believe `get_harvester_config` and `update_harvester_config` need tests (I might suggest `test_farmer_harvester_rpc.py`)

**Comment by ChiaMineJP** [comment]
@emlowe Yes, I'll add tests

**Review by emlowe — APPROVED** [review]
Approved - Coverage diff down to a single line which is acceptable

**Pull request merged**
