### PR TITLE
fix some variable maybe none in branches

### PR DESCRIPTION
**Pull request by aisk**
A common usage in chia's codes is create a client in a try branch, and close it at outside of this branch. In most case this will cause not errors, but it may cause problem and will make some linters (like pyright) not happy.

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
Any particular reason why the close's aren't inside the `try`-clauses after the setting of the clients?

**Comment by aisk** [comment]
> Any particular reason why the close's aren't inside the `try`-clauses after the setting of the clients?

Maybe we want after client is created and then error happened, the client is closed?

**Comment by Nikolaj-K** [comment]
@aisk But that can also happen upon catching the issue and then the setup with `= None` would be avoided. If it's clear it can be instantiated, then one could do that outside the `try`-block and if not, probably there should be separate try's for all calls that are at danger of failing. (Not saying those should be straightened out with this PR)

**Comment by aisk** [comment]
> @aisk But the closing can also happen upon catching the exception, and this way the setup with `= None` would be avoided.
> If on the other hand it's clear the client can be instantiated, then one could do that outside the `try`-block. And if not, probably there should be separate try's for all calls that are at danger of failing.
> (Not saying those should be straightened out with this PR)

Yes, I think refactor the codes to little branch in try statement is a good choice.

**Comment by hoffmang9** [comment]
Keeping alive

**Comment by emlowe** [comment]
This pr is no longer relevant due to substantial code changes in the meantime. Apologies for the ridiculous delay in getting to this.

**Pull request closed without merging**
