### PR TITLE
Few additional sets of test SSL certs/keys for CI

### PR DESCRIPTION
**Pull request by paninaro**
Possible solution to CI issues involving nodes using the same SSL certs, resulting in node id conflicts.

Example error message: "Trying to connect to a peer ({'host': 'localhost', 'port': 41131}) with the same peer_id"

When using `get_next_private_ca_cert_and_key()` or `get_next_nodes_certs_and_keys()`, a wrapper object is returned which internally tracks when the SSL test collateral is in use (simple constructor/destructor semantics).

### CODE REVIEW

**Review by mariano54 — COMMENTED** [review]
It's worth a try, thanks for addressing this.

**Review by jack60612 — COMMENTED** [review]
All of the code is way cleaner + tests pass, and this code is fairly simple. However, I don't understand how this will solve the problem you mentioned above. does the state of which ssl certs are in use somehow get passed in somewhere, or am I missing something?

**Comment by mariano54** [comment]
Lint failure needs to be fixed

**Review by mariano54 — DISMISSED** [review]
Pending lint fix before merge

**Comment by paninaro** [comment]
> Pending lint fix before merge

Should be fixed by https://github.com/Chia-Network/chia-blockchain/pull/12704.

**Comment by jack60612** [comment]
> > Pending lint fix before merge
> 
> Should be fixed by #12704.

try catching up with main

**Comment by paninaro** [comment]
> All of the code is way cleaner + tests pass, and this code is fairly simple. However, I don't understand how this will solve the problem you mentioned above. does the state of which ssl certs are in use somehow get passed in somewhere, or am I missing something?

It may not fix the CI failures, but if the assumption is that some tests are using all of the test certs/keys, then adding a few more may help. The other changes have been added to provide some logging if we detect that a set of certs/keys is being reused while still in use by some part of the test.

**Review by jack60612 — DISMISSED** [review]
lgtm

**Review by mariano54 — DISMISSED** [review]

**Comment by paninaro** [comment]
Rebased on top of main. Changes previously made to `test_start_simulator.py` have been moved to `simulator_test_tools.py`

**Review by jack60612 — APPROVED** [review]
lgtm, hope it helps

**Review by mariano54 — APPROVED** [review]

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
