### PR TITLE
Test faster reorg

### PR DESCRIPTION
**Pull request by aqk**
Please merge #7056 first

### CODE REVIEW

**Comment by arvidn** [comment]
this patch updates the `chia-blockchain-gui` submodule, most likely accidentally.

**Comment by arvidn** [comment]
@aqk could you add a description what this patch does? (other than extending the generation of the workflow files to include the resource usage checks). The title is a bit cryptic. Is it only test/CI changes?

**Comment by aqk** [comment]
I'll break this up into two commits, so you can see what's really going on. I'll update this PR after we merge these two
https://github.com/Chia-Network/chia-blockchain/pull/7181
https://github.com/Chia-Network/chia-blockchain/pull/7056

**Comment by emlowe** [comment]
Closing old draft PR - please re-open if this remains relevant

**Pull request closed without merging**
