### PR TITLE
force index in get_coin_records_by_names

### PR DESCRIPTION
**Pull request by 0xJohnZW**
In the 'get_coin_records_by_names' method, if 'include_spent_coins' is False, and the num of names > 2, SQLite will use the 'coin_spent_index', which leads to an API timeout
```python
import aiosqlite
import asyncio

async def show_explain(names, include_spent_coins, db):
    print(f"names num: {len(names)}, include_spent_coins: {include_spent_coins}")
    sql = (
        f"explain query plan SELECT confirmed_index, spent_index, coinbase, puzzle_hash, "
        f'coin_parent, amount, timestamp FROM coin_record WHERE coin_name in ({"?," * (len(names) - 1)}?) '
        f"AND confirmed_index>=? AND confirmed_index<? "
        f"{'' if include_spent_coins else 'AND spent_index=0'}"
    )
    async with db.execute(sql, tuple(names) + (0,(2 ** 32) - 1)) as cursor:
        row = await cursor.fetchone()
        print("explain: ", row[-1])

async def main():
    db = await aiosqlite.connect("/root/.chia/mainnet/db/blockchain_v2_testnet10.sqlite")
    names = ["b0f667137fa6a52797d3fa2f48481e0e007f9653355ec301e4b7467d532b21da","84b1deb930dd9da0c900f28c1afd9a591dea6d8827f92a397a058149e70e5773","68321a8b8ae6838de9c946919a7296706d41990b89f2b440c8c7314f6445c9cd","25300172aa6265ceacbf0229b331a1c0de768dad1b18e20f6938ab30e5267949"]
    names = [bytes.fromhex(s) for s in names]
    test_params = [
        [names[:2], True], [names, True], [names[:2], False], [names, False], [names[:3], False],
    ]
    for params in test_params:
        await show_explain(*params, db)
    await db.close()

asyncio.run(main())
```
```
names num: 2, include_spent_coins: True
explain:  SEARCH TABLE coin_record USING INDEX sqlite_autoindex_coin_record_1 (coin_name=?)
names num: 4, include_spent_coins: True
explain:  SEARCH TABLE coin_record USING INDEX sqlite_autoindex_coin_record_1 (coin_name=?)
names num: 2, include_spent_coins: False
explain:  SEARCH TABLE coin_record USING INDEX sqlite_autoindex_coin_record_1 (coin_name=?)
names num: 4, include_spent_coins: False
explain:  SEARCH TABLE coin_record USING INDEX coin_spent_index (spent_index=?)
names num: 3, include_spent_coins: False
explain:  SEARCH TABLE coin_record USING INDEX coin_spent_index (spent_index=?)
```

### CODE REVIEW

**Comment by mariano54** [comment]
Thank you! do you mind fixing the linting issue pointed out by the CI?

**Review by hoffmang9 — APPROVED** [review]
This lgtm and thank you!

**Comment by arvidn** [comment]
does sqlite guarantee stability of the implicitly created index name `sqlite_autoindex_coin_record_1`?
I'm having a hard time finding this documented, but I take it `coin_record_1` refers to the index created for the primary key, `coin_name`, right?

**Comment by neurosis69** [comment]
> does sqlite guarantee stability of the implicitly created index name `sqlite_autoindex_coin_record_1`? I'm having a hard time finding this documented, but I take it `coin_record_1` refers to the index created for the primary key, `coin_name`, right?

yes, an automatically created index supporting a PK is an internal object, the name has always format like "sqlite_autoindex_TABLE_N".
[Documentation here](https://www.sqlite.org/fileformat2.html#intschema)

btw, this is probably only a problem because the query optimizer has no clue about the data distribution.

For the future you may want to give db statistics a try.

To test it you can either run `analyze;` in the database, which can take a long time depending on your systems HW.
Or, as every node has presumable the same database containing the same datasets/rows, you can just set/deliver the statistics during new deployments.

If you want to test/compare it, here are the necessary stmts for the very simple v1 sqlite_stat1 table(statistic values are taken from my db, a few weeks old):
```
pragma writable_schema=1;
CREATE TABLE sqlite_stat1(tbl,idx,stat);
pragma writable_schema=0;
INSERT INTO sqlite_stat1 VALUES('coin_record','coin_parent_index','92178907 7');
INSERT INTO sqlite_stat1 VALUES('coin_record','coin_puzzle_hash','92178907 12');
INSERT INTO sqlite_stat1 VALUES('coin_record','coin_spent_index','92178907 182');
INSERT INTO sqlite_stat1 VALUES('coin_record','coin_confirmed_index','92178907 154');
INSERT INTO sqlite_stat1 VALUES('coin_record','sqlite_autoindex_coin_record_1','92178907 1');
INSERT INTO sqlite_stat1 VALUES('hints','hint_index','1021243 3');
INSERT INTO sqlite_stat1 VALUES('hints','sqlite_autoindex_hints_1','1021243 1 1');
INSERT INTO sqlite_stat1 VALUES('sub_epoch_segments_v3','sqlite_autoindex_sub_epoch_segments_v3_1','4398 1');
INSERT INTO sqlite_stat1 VALUES('current_peak','sqlite_autoindex_current_peak_1','1 1');
INSERT INTO sqlite_stat1 VALUES('full_blocks','is_fully_compactified','1689446 844723 844723');
INSERT INTO sqlite_stat1 VALUES('full_blocks','main_chain','1689446 1 1');
INSERT INTO sqlite_stat1 VALUES('full_blocks','height','1689456 2');
INSERT INTO sqlite_stat1 VALUES('full_blocks','sqlite_autoindex_full_blocks_1','1689456 1');
INSERT INTO sqlite_stat1 VALUES('database_version',NULL,'1');
```

The `pragma writable_schema=1` is only necessary as we don't want to run the long-op + resource intensive `analyze;` and sqlite would prevent us to create an internal object otherwise. 

If you are planning to use statistics in one of the future relases, I'd not suggest to use the sqlite_stat1 version, as there are only very basic informations stored. But to show for this use case it gives sufficient information.

**Review by arvidn — APPROVED** [review]

**Pull request merged**
