### PR TITLE
add run-py-linters.sh for local linting

### PR DESCRIPTION
**Pull request by altendky**
This differs from https://github.com/Chia-Network/chia-blockchain/blob/fceb39f783392a32f43b562de1e85e810e913005/run-py-tests.sh in that it does not attempt to create the env and does install `chia-blockchain[dev]` as `--editable`.

`run-py-tests.sh` does try to create the env and in so doing can shove a different Python version into the env.  It also presumes that you have run `install.sh` since it expects to find an `activate` script in the root.  Further, it does not does not install `--editable` like `install.sh` does, thus leaving further changes to the source unrepresented in the installed copy.

I will also note that both `run-py-*.sh` scripts seem unlikely to work on Windows unless we have an `install.sh`-alike that handles Windows but still provides an `activate` bash script in the root.  In general, I use [tox](https://tox.readthedocs.io/en/latest/) for these sort of 'create an env and do something in it' activities.  I then use the same tox environment both locally and in CI, as opposed to CI-only setups.

Draft for:
- [x] Making it match CI (at least that it is quiet right now like CI is)
- [ ] Unbroken `main` related to https://github.com/Chia-Network/clvm_rs/pull/123

### CODE REVIEW

**Comment by altendky** [comment]
Presently getting some pylint complaints locally that don't show up in CI.

```
---- mypy
Success: no issues found in 412 source files
---- mypy passed

---- flake8
---- flake8 passed

---- black
All done! ✨ 🍰 ✨
412 files would be left unchanged.
---- black passed

---- pylint
************* Module chia.full_node.mempool_check_conditions
chia/full_node/mempool_check_conditions.py:5:0: E0611: No name 'STRICT_MODE' in module 'clvm_rs' (no-name-in-module)
************* Module chia.types.blockchain_format.program
chia/types/blockchain_format/program.py:10:0: E0611: No name 'STRICT_MODE' in module 'clvm_rs' (no-name-in-module)
chia/types/blockchain_format/program.py:10:0: E0611: No name 'deserialize_and_run_program2' in module 'clvm_rs' (no-name-in-module)
chia/types/blockchain_format/program.py:10:0: E0611: No name 'serialized_length' in module 'clvm_rs' (no-name-in-module)
chia/types/blockchain_format/program.py:10:0: E0611: No name 'run_generator' in module 'clvm_rs' (no-name-in-module)
************* Module tests.core.util.test_type_checking
tests/core/util/test_type_checking.py:57:12: E1121: Too many positional arguments for constructor call (too-many-function-args)
---- pylint FAILED

---- Some checks FAILED
```

**Comment by arvidn** [comment]
this seems to overlap with the `pre-commit` configuration we already have. Are there any linters we run in CI that isn't part of pre-commit? I would think it's better to extend the existing configuration instead

**Comment by arvidn** [comment]
also, we should probably document

```
pre-commit install
```

**Comment by altendky** [comment]
That does seem to fill this role, thanks for pointing it out.  I haven't used pre-commit much yet so I forget to look for it.  One thing I notice is that the config files are down in `.github/linters/` rather than using their standard names at the top of the projects.  Maybe we could move the config files to their standard locations and tell the GitHub linter to use them from their?  Maybe also just use pre-commit in CI rather than the GitHub linter?  pre-commit doesn't seem to be installing most dependencies so mypy is having trouble, I'm trying to figure that out.

https://github.com/Chia-Network/chia-blockchain/blob/b5537fcc53ae1b0fea014a66da06926832d547c4/.pre-commit-config.yaml

I won't close this PR quite yet, but it seems like that will likely happen.

**Comment by altendky** [comment]
From what I can tell, pre-commit is not really usable for mypy unless you are going to maintain a duplicated list of dependencies in the pre-commit configuration file.  https://github.com/pre-commit/pre-commit/issues/2061  I've tried to use pre-commit a couple times before and it hasn't ended up really working out despite being a useful idea.

**Pull request closed without merging**
