### PR TITLE
Replace pylint with ruff

### PR DESCRIPTION
**Pull request by wallentx**
<table>
  <tr>
    <th width="420">🌐 Breaking News 📰</th>
    <th>Special Press Conference</th>
  </tr>
  <tr>
    <td>
     dumple-skump
     LIVE BROADCAST FROM THE MEN'S WAREHOUSE 
                                                                                           
    </td>
    <td align="right" style="vertical-align:top;">
      <em>
        This PR is going to make code great again, folks. A lotta hard work went into this, I'll tell you.. A lot of concepts of hard work in here... and... You ever hear about <code>Ruff</code>? <br /> Let me tell you, Ruff is absolutely tremendous — believe me. It’s very, very fast — and I know fast — it's the fastest, actually — and the best, most efficient linter like you’ve never seen. Not like that horrible pylint, which is slow and outdated. Compared to pylint, Ruff is like a rocket ship. And not one of those loser ships that blows up and wastes all of that beautiful fuel. <br /> Millions and millions of Developers everywhere are saying it’s saving them so much time, making their code cleaner and better than ever before. And I know them all very well, and I trust them. Ask anyone. They all say that all the code now is dirty because of pylint. It's never been worse. It's a failing project, run by bums and perverts! That's what they say - I didn't say it, but that's what they said... so, who knows.. Ruff is winning bigly in the world of code linting. Nobody does it better, and that’s a fact.
      </em>
    </td>
  </tr>
</table>

### CODE REVIEW

**Comment by Quexington** [comment]
For reference, here's a breakdown of the pylint <-> ruff parity: https://github.com/astral-sh/ruff/issues/970

**Comment by Quexington** [comment]
The biggest difference it seems to me between this and pylint off the bat is that it does not have type inference

**Comment by wallentx** [comment]
Yep, I figured that this might not provide 1:1 functionality with what pylint provides, but I wasn't sure what was absent until I just attempted to implement it. I also wasn't sure if 1:1 parity was essential, or if there were just a few rules that were nice to have, that you could do without, or could handle with something similar.
https://github.com/Chia-Network/chia-blockchain/pull/18649/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R184-R196

> The biggest difference it seems to me between this and pylint off the bat is that it does not have type inference or multi file analysis

Good find on ruff#290, and good to know there's some missing baseline functionality that makes this a non-starter. It does look like they have a specific label to track those 2 things - https://github.com/astral-sh/ruff/issues?q=sort%3Aupdated-desc+is%3Aopen+label%3Ared-knot

Also, this fellow's script looks like it might be of use some day in the future: https://gist.github.com/pcorpet/e776a8e794264b818c9cc6d06c11ef15

I'm not sure how far out things are from this being feature-ready to investigate using, so let me know if it's worth it to keep this in a draft state as a reminder, or a thing to poke at occasionally, else I can just close this for now. Letsbehonest this was just an excuse submit a PR from a branch named with emojis.

**Comment by Quexington** [comment]
I'm not saying those two things are deal breakers, I'm just adding documentation.  I personally dislike pylint's type inference because I don't think it's very good and we have mypy checking the stuff better.  Not sure about multi-file checking, but I (personally) have been an advocate for just deleting pylint altogether because I don't feel like it gives very helpful errors and often gives errors that don't seem to matter.

**Comment by Quexington** [comment]
Also @wallentx did you intend to also remove the pylint check at the same time?

**Comment by wallentx** [comment]
> Also @wallentx did you intend to also remove the pylint check at the same time?

I think my nature just led me to that by default. Romantics are wary of broken hearts, and breaking them, and know better than to scatter their affections.

**Comment by wallentx** [comment]
> Hey, it's Mike.
> Listen, I’ve been waiting on this pull request, but I’m getting a bad feeling...
>
> Yeah, two plus two aren't adding up, if you catch my drift.
> Well, the whole thing stinks, and you know..
> Yeah, I'd bet you a pallet of pillows You-Know-Who is behind it.
> Dominion!
> Yeah, I know, I know..
> *I know that!* But *trust me*—I've seen this before. We’re not taking any chances.
>
> _I'm_ not taking any chances... I can't afford it.
> Hey- gotta go.
> Closing it down now.
> Mmkay, God bless, bye.

**Pull request closed without merging**
