### PR TITLE
List unopenable plots at end of plots check

### LINKED ISSUE #2825: [BUG-MINOR] plots marked as "Invalid plot header magic" are not included in summary by `chia plots check`
The fact that chia seems to be randomly taking some plots with "Invalid plot header magic" aside, it is also not reporting these plots as invalid in the `chia plots check`  summary:

```
(venv) speedster@cohen:~$ chia plots check -n 100 -g /farm/acre26/plots/chachacha-plot-k32-2021-04-24-02-28-00211f7b93d4e342a7af6bb4dd3f2bacce5c4e161c90c2ab38a69704b8e69e1b.plot
2021-04-26T10:07:48.324  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_tools loading code

2021-04-26T10:07:52.439  chia.plotting.plot_tools         : INFO     Searching directories ['/farm/acre12/plots', '/farm/acre14/plots', '/farm/acre15/plots', '/farm/acre16/plots', '/farm/acre17/plots', '/farm/acre18/plots', '/farm/acre19/plots', '/farm/acre20/plots', '/farm/acre21/plots', '/farm/acre22/plots', '/farm/acre23/plots', '/farm/acre24/plots', '/farm/acre5/plots', '/farm/acre6/plots', '/farm/acre7/plots', '/farm/acre8/plots', '/farm/acre2/plots', '/farm/acre4/plots', '/farm/acre3/plots', '/farm/acre25/plots', '/farm/acre28/plots', '/mnt/transfer/plots', '/farm/acre26/plots']
2021-04-26T10:07:52.508  chia.plotting.plot_tools         : INFO     Only loading plots that contain "/farm/acre26/plots/chachacha-plot-k32-2021-04-24-02-28-00211f7b93d4e342a7af6bb4dd3f2bacce5c4e161c90c2ab38a69704b8e69e1b.plot" in the file or directory name
2021-04-26T10:07:52.699  chia.plotting.plot_tools         : ERROR    Failed to open file /farm/acre26/plots/chachacha-plot-k32-2021-04-24-02-28-00211f7b93d4e342a7af6bb4dd3f2bacce5c4e161c90c2ab38a69704b8e69e1b.plot. Invalid plot header magic Traceback (most recent call last):
  File "/home/speedster/dev/chia-blockchain/chia/plotting/plot_tools.py", line 183, in process_file
    prover = DiskProver(str(filename))
ValueError: Invalid plot header magic

2021-04-26T10:07:52.700  chia.plotting.plot_tools         : INFO     Loaded a total of 0 plots of size 0.0 TiB, in 0.3909459114074707 seconds
2021-04-26T10:07:52.701  chia.plotting.check_plots        : INFO     
2021-04-26T10:07:52.702  chia.plotting.check_plots        : INFO     
2021-04-26T10:07:52.702  chia.plotting.check_plots        : INFO     Summary
2021-04-26T10:07:52.702  chia.plotting.check_plots        : INFO     Found 0 valid plots, total size 0.00000 TiB
2021-04-26T10:07:52.702  chia.plotting.check_plots        : WARNING  1 invalid plots found:
(venv) speedster@cohen:~$ 
```

1) All "invalid" plots should be reported in the `chia plots check` summary
2) I am crossing my fingers that when looking for this bug you uncover whatever bug which has started to randomly tag plots that passed muster previously as "Invalid plot header magic"

### PR DESCRIPTION
**Pull request by altendky**
Closes https://github.com/Chia-Network/chia-blockchain/issues/2825

### CODE REVIEW

**Review by hoffmang9 — DISMISSED** [review]
lgtm

**Review by emlowe — COMMENTED** [review]
Nice

**Review by emlowe — DISMISSED** [review]
nice

**Review by xdustinface — CHANGES_REQUESTED** [review]
Is there a reason to not just use `Path.__str__` like below in the comments?

**Review by xdustinface — APPROVED** [review]

**Pull request merged**
