### PR TITLE
rename testnet constants to default constants, because they are the base for all networks

### PR DESCRIPTION
**Pull request by jack60612**

### CODE REVIEW

**Review by mariano54 — DISMISSED** [review]
nice

**Review by emlowe — DISMISSED** [review]
I'm a little confused - this is not mainnet genesis - it does not match mainnet genesis listed in initial-config.yaml - so why is this called mainnet?

**Comment by jack60612** [comment]
> I'm a little confused - this is not mainnet genesis - it does not match mainnet genesis listed in initial-config.yaml - so why is this called mainnet?

These are the base constants for all networks, which then get overridden depending on the network. 
another possible name is base constants but mainnet sounded more accurate.

**Comment by emlowe** [comment]
I think this name is more confusing. It seems it's neither mainnet nor testnet. It's default - so I would call it `default_kwargs`

**Comment by mariano54** [comment]
These are the mainnet constants, except for the initial challenge (since when we released 1.0 we didn't have the challenge yet). That said, default_kwargs is fine too

**Review by wjblanke — APPROVED** [review]
aok

**Review by wallentx — APPROVED** [review]
:shipit:

**Pull request merged**
