### PR TITLE
use a better index when picking random blocks to compactify

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aqk** [comment]
Do these indexes already exist / does this PR require another PR?

**Comment by arvidn** [comment]
yes. the index `is_fully_compactified` is created [here](https://github.com/Chia-Network/chia-blockchain/pull/9351/files#diff-93a564af2275d87306b87d322d695e40d1c11b0628606e56954c4c207ecead47R56).

**Review by fchirica — DISMISSED** [review]

**Comment by arvidn** [comment]
is there any chance this test failure is caused by these changes? I'm having a hard time interpreting the failure. And this test never passes when I run it locally (because of "address in use")

**Comment by arvidn** [comment]
aha, found it.

@neurosis69 the sql query is failing:

https://github.com/Chia-Network/chia-blockchain/runs/4297176850?check_suite_focus=true#step:14:102

```
09:22:46 chia.full_node.full_node: ERROR Exception Stack: Traceback (most recent call last):
  File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/full_node.py", line 2236, in broadcast_uncompact_blocks
    heights = await self.block_store.get_random_not_compactified(target_uncompact_proofs)
  File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/block_store.py", line 356, in get_random_not_compactified
    "SELECT height FROM full_blocks "
[...]
sqlite3.OperationalError: no query solution
```

**Comment by neurosis69** [comment]
> aha, found it.
> 
> @neurosis69 the sql query is failing:
> 
> https://github.com/Chia-Network/chia-blockchain/runs/4297176850?check_suite_focus=true#step:14:102
> 
> ```
> 09:22:46 chia.full_node.full_node: ERROR Exception Stack: Traceback (most recent call last):
>   File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/full_node.py", line 2236, in broadcast_uncompact_blocks
>     heights = await self.block_store.get_random_not_compactified(target_uncompact_proofs)
>   File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/block_store.py", line 356, in get_random_not_compactified
>     "SELECT height FROM full_blocks "
> [...]
> sqlite3.OperationalError: no query solution
> ```



> aha, found it.
> 
> @neurosis69 the sql query is failing:
> 
> https://github.com/Chia-Network/chia-blockchain/runs/4297176850?check_suite_focus=true#step:14:102
> 
> ```
> 09:22:46 chia.full_node.full_node: ERROR Exception Stack: Traceback (most recent call last):
>   File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/full_node.py", line 2236, in broadcast_uncompact_blocks
>     heights = await self.block_store.get_random_not_compactified(target_uncompact_proofs)
>   File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/block_store.py", line 356, in get_random_not_compactified
>     "SELECT height FROM full_blocks "
> [...]
> sqlite3.OperationalError: no query solution
> ```

@arvidn 
quick test on my side.
The query didn't work when these f" strings are mixed with normal " strings. 
But I didn't also see any errors, just didn't get results.

Using f" strings for all stmts worked on my side:
```
        cursor = await self.db.execute(
            f"SELECT height FROM full_blocks "
            f"INDEXED BY is_fully_compactified "
            f"GROUP BY height HAVING sum(is_fully_compactified)=0 "
            f"ORDER BY RANDOM() LIMIT {number}"
        )
```

**Comment by arvidn** [comment]
thanks! I usually get warnings on f-strings with no`{}` blocks in them. But maybe when you concatenate them like this you need that.

**Comment by arvidn** [comment]
it's still failing with:

```
14:12:47 chia.full_node.full_node: ERROR Exception Stack: Traceback (most recent call last):
  File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/full_node.py", line 2238, in broadcast_uncompact_blocks
    heights = await self.block_store.get_random_not_compactified(target_uncompact_proofs)
  File "/home/runner/work/chia-blockchain/chia-blockchain/chia/full_node/block_store.py", line 356, in get_random_not_compactified
    f"SELECT height FROM full_blocks "
  File "/home/runner/work/chia-blockchain/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/runner/work/chia-blockchain/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/runner/work/chia-blockchain/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: no query solution
```

**Comment by neurosis69** [comment]
commited this sql change also to my repo #9226 and awaiting results of the automatic test.
"no query solution" means that the INDEXED BY clause is not working, I have no idea why this is happening.

unfortunately I can't directly execute this test on my side with `./venv/bin/py.test tests/simulation/test_*.py -s -v --durations 0`,
because for some reasons I'm not able to install a timelord any more. It worked a couple of months ago.

On my "Clear Linux" as well as on my Ubuntu hosts the `sh install-timelord.sh` is failing with the following error
``` 
(venv) chia@plotter1~/chia-blockchain (latest) $ sh install-timelord.sh
Timelord requires CMake 3.14+ to compile vdf_client.
Python version: python3.9
install-timelord.sh: line 43: type: apt-get: not found
dnf is /usr/bin/dnf
Found RedHat.
Installing chiavdf from source on RedHat/CentOS/Fedora
yum install gcc gcc-c++ gmp-devel python3-devel libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 -y
sudo: yum: command not found
venv/bin/python -m pip install --force --no-binary chiavdf chiavdf==1.0.3
Collecting chiavdf==1.0.3
  Using cached chiavdf-1.0.3.tar.gz (635 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/chia/chia-blockchain/venv/bin/python /home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpn5j6q7_3
       cwd: /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd
  Complete output (89 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 11.2.1
  -- The CXX compiler identification is GNU 11.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/g++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  GMP_INCLUDES=/usr/local/include
  -- Found GMP: /usr/local/include (Required is at least version "5.1.0")
  GMP_INCLUDES=/usr/local/include
  -- Found GMPXX: /usr/lib64/libgmpxx.so
  -- pybind11 v2.6.2
  -- Found PythonInterp: /home/chia/chia-blockchain/venv/bin/python (found version "3.9.7")
  -- Found PythonLibs: python3.9
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd
  [ 16%] Building CXX object CMakeFiles/verifier_test.dir/verifier_test.cpp.o
  [ 33%] Building CXX object CMakeFiles/chiavdf.dir/python_bindings/fastvdf.cpp.o
  [ 50%] Building C object CMakeFiles/verifier_test.dir/refcode/lzcnt.c.o
  [ 66%] Building C object CMakeFiles/chiavdf.dir/refcode/lzcnt.c.o
  In file included from /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd/_deps/pybind11-src-src/include/pybind11/pytypes.h:12,
                   from /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd/_deps/pybind11-src-src/include/pybind11/cast.h:13,
                   from /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd/_deps/pybind11-src-src/include/pybind11/attr.h:13,
                   from /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd/_deps/pybind11-src-src/include/pybind11/pybind11.h:45,
                   from /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd/src/python_bindings/fastvdf.cpp:1:
  /tmp/pip-install-ppq_969w/chiavdf_d3d7e740154b44a1ad868bc6f02ae5bd/_deps/pybind11-src-src/include/pybind11/detail/common.h:124:10: fatal error: Python.h: No such file or directory
    124 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  gmake[2]: *** [CMakeFiles/chiavdf.dir/build.make:76: CMakeFiles/chiavdf.dir/python_bindings/fastvdf.cpp.o] Error 1
  gmake[2]: *** Waiting for unfinished jobs....
  gmake[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/chiavdf.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
  [ 83%] Linking CXX executable verifier_test
  [ 83%] Built target verifier_test
  gmake: *** [Makefile:91: all] Error 2
  Traceback (most recent call last):
    File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/chia/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-cvxny85b/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-cvxny85b/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-cvxny85b/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 267, in <module>
      setup(
    File "/tmp/pip-build-env-cvxny85b/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-cvxny85b/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 112, in run
      self.build_extension(ext)
    File "setup.py", line 140, in build_extension
      subprocess.check_call(["cmake", "--build", "."] + build_args)
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Could not build wheels for chiavdf, which is required to install pyproject.toml-based projects
ERROR: Could not find venv/lib/python3.9/site-packages/vdf_bench
To estimate a timelord on this CPU try './vdf_bench square_asm 400000' for an ips estimate.
```

**Comment by hoffmang9** [comment]
Your system is missing the python3-devel or its equivalent for Clear.

**Comment by neurosis69** [comment]
Thanks, I will check this later. 

@arvidn 
To which sqlite db does this `test_simulation.py` connect? 
Is the database built from scratch using the provided scripts and then later deleted again?
From what I found out the db should be named "blockchain_tets.db", right?

My wild guess would be, that the simulation runs against a db where the index is missing.

**Comment by neurosis69** [comment]
The problem with the timelord installation was a broken python 3.10/3.9 mixed installation on my side.
Fixed that by reinstalling python 3.9, timelord is now running.

Still need to figure out how these tests work, I think I prepared everything according to CONTRIBUTING.md.
Have now a `py.test tests -v --durations 0` running again.

**Comment by neurosis69** [comment]
Found out myself that the database is built from scratch to /tmp during the tests and the index `is_fully_compactified` is part of these dbs.

I executed the test on the current main branch, 1x with the change and 1x using the old stmt. 

Both tests ran into the same errors, but not to the index related `no query solution`:
```
2021-11-24T16:12:17.830 introducer asyncio                : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-91' coro=<spawn_process() running at /home/chia/chia-blockchain/chia/timelord/timelord_launcher.py:77> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80372310>()]>>
2021-11-24T16:12:17.830 harvester asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-91' coro=<spawn_process() running at /home/chia/chia-blockchain/chia/timelord/timelord_launcher.py:77> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80372310>()]>>
2021-11-24T16:12:17.830 farmer asyncio                    : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-91' coro=<spawn_process() running at /home/chia/chia-blockchain/chia/timelord/timelord_launcher.py:77> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80372310>()]>>
2021-11-24T16:12:17.830 timelord asyncio                  : ERROR    Task was destroyed but it is pending!
...
task: <Task pending name='Task-1319' coro=<FullNode._refresh_ui_connections() running at /home/chia/chia-blockchain/chia/full_node/full_node.py:460> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e801595e0>()]>>
2021-11-24T16:12:17.831 harvester asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1319' coro=<FullNode._refresh_ui_connections() running at /home/chia/chia-blockchain/chia/full_node/full_node.py:460> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e801595e0>()]>>
2021-11-24T16:12:17.831 farmer asyncio                    : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1319' coro=<FullNode._refresh_ui_connections() running at /home/chia/chia-blockchain/chia/full_node/full_node.py:460> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e801595e0>()]>>
2021-11-24T16:12:17.831 timelord asyncio                  : ERROR    Task was destroyed but it is pending!
...
task: <Task pending name='Task-1199' coro=<FullNodeAPI.new_unfinished_block.<locals>.eventually_clear() running at /home/chia/chia-blockchain/chia/full_node/full_node_api.py:426> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80186070>()]>>
2021-11-24T16:12:17.832 harvester asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1199' coro=<FullNodeAPI.new_unfinished_block.<locals>.eventually_clear() running at /home/chia/chia-blockchain/chia/full_node/full_node_api.py:426> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80186070>()]>>
2021-11-24T16:12:17.832 farmer asyncio                    : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1199' coro=<FullNodeAPI.new_unfinished_block.<locals>.eventually_clear() running at /home/chia/chia-blockchain/chia/full_node/full_node_api.py:426> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80186070>()]>>
...
2021-11-24T16:12:17.832 introducer asyncio                : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1419' coro=<FullNode._refresh_ui_connections() done, defined at /home/chia/chia-blockchain/chia/full_node/full_node.py:458> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80080460>()]>>
2021-11-24T16:12:17.832 harvester asyncio                 : ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-1419' coro=<FullNode._refresh_ui_connections() done, defined at /home/chia/chia-blockchain/chia/full_node/full_node.py:458> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f1e80080460>()]>>
...
```

I don't think that the error is related to the changed SQL statement.

**Comment by arvidn** [comment]
I think this is obsolete now, with v2

**Pull request closed without merging**
