### PR TITLE
replace some asyncio.get_event_loop().run_until_complete() with asyncio.run()

### PR DESCRIPTION
**Pull request by altendky**
Extracted from https://github.com/Chia-Network/chia-blockchain/pull/9930.

### CODE REVIEW

**Review by xdustinface — CHANGES_REQUESTED** [review]
Any reason to not adjust the ones in `block_tools.py`?

**Comment by altendky** [comment]
There was some funny business there where the fact we were doing silly stuff actually caused problems when doing it a bit less silly.  I'm punting on that for the sake of getting 3.10 done.  There's a warning ignore added related to those so they are 'on a list' as needing to be addressed.   Sort of.

**Review by xdustinface — APPROVED** [review]
> There was some funny business there where the fact we were doing silly stuff actually caused problems when doing it a bit less silly.

Hm, ok but i don't really understand whats different in there and what kind of "funny business" would lead to an issue since it works just fine (at least locally).

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
