### PR TITLE
add missing cost constants for conditions

### PR DESCRIPTION
**Pull request by arvidn**
Perhaps it's a bit meaningless to have names for all these zeros. I think we should either have these constants, for consistency, or remove all the zero-constants.

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
aok

**Comment by wjblanke** [comment]
Maybe add this but comment out all the zero values? I don't think python will compile this out, it would just slow things down, no?

**Comment by arvidn** [comment]
I don't know what you mean by commenting out all the zero values. You mean make all the constants and code using them comments?

I think it would make more sense to remove the code and the constatns, and just leave comments in the code explaining that most conditions don't have costs associated with them

**Comment by Nikolaj-K** [comment]
I think you can divide the lines by two via
```python
CONDITION_COSTS = {
    ConditionOpcode.AGG_SIG_UNSAFE: ConditionCost.AGG_SIG,
    ConditionOpcode.AGG_SIG_ME: ConditionCost.AGG_SIG,
    ConditionOpcode.CREATE_COIN: ConditionCost.CREATE_COIN,
    ConditionOpcode.ASSERT_SECONDS_ABSOLUTE: ConditionCost.ASSERT_SECONDS_ABSOLUTE,
    ConditionOpcode.ASSERT_SECONDS_RELATIVE: ConditionCost.ASSERT_SECONDS_RELATIVE,
    ConditionOpcode.ASSERT_HEIGHT_ABSOLUTE: ConditionCost.ASSERT_HEIGHT_ABSOLUTE,
    ConditionOpcode.ASSERT_HEIGHT_RELATIVE: ConditionCost.ASSERT_HEIGHT_RELATIVE,
    ConditionOpcode.ASSERT_MY_COIN_ID: ConditionCost.ASSERT_MY_COIN_ID,
    ConditionOpcode.ASSERT_MY_PARENT_ID: ConditionCost.ASSERT_MY_PARENT_ID,
    ConditionOpcode.ASSERT_MY_PUZZLEHASH: ConditionCost.ASSERT_MY_PUZZLEHASH,
    ConditionOpcode.ASSERT_MY_AMOUNT: ConditionCost.ASSERT_MY_AMOUNT,
    ConditionOpcode.RESERVE_FEE: ConditionCost.RESERVE_FEE,
    ConditionOpcode.CREATE_COIN_ANNOUNCEMENT: ConditionCost.CREATE_COIN_ANNOUNCEMENT,
    ConditionOpcode.ASSERT_COIN_ANNOUNCEMENT: ConditionCost.ASSERT_COIN_ANNOUNCEMENT,
    ConditionOpcode.CREATE_PUZZLE_ANNOUNCEMENT: ConditionCost.CREATE_PUZZLE_ANNOUNCEMENT,
    ConditionOpcode.ASSERT_PUZZLE_ANNOUNCEMENT: ConditionCost.ASSERT_PUZZLE_ANNOUNCEMENT,
}

cost = CONDITION_COSTS.get(condition, None)

if cost:
    total_cost += len(cvp_list) * cost.value
```

**Comment by wjblanke** [comment]
Right, either way. I know putting this in code makes things clearer, but while C++ would optimize this all out I think Python may actually have to execute it all. If I am wrong please correct me.

> I don't know what you mean by commenting out all the zero values. You mean make all the constants and code using them comments?
> 
> I think it would make more sense to remove the code and the constatns, and just leave comments in the code explaining that most conditions don't have costs associated with them

**Pull request merged**
