### PR TITLE
Add support for multiple paralel queues of plots

### PR DESCRIPTION
**Pull request by jespino**
The interface for this changes are here: Chia-Network/chia-blockchain-gui#128

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]
Nice!

**Comment by hoffmang9** [comment]
```
08:53:39.424 daemon __main__                   : INFO     chia daemon exiting in 5 seconds
08:53:39.432 daemon __main__                   : INFO     Daemon WebSocketServer closed
08:53:58.411 daemon __main__                   : INFO     Starting Daemon Server
08:53:58.414 daemon __main__                   : INFO     Waiting Daemon WebSocketServer closure
08:53:59.057 daemon __main__                   : INFO     Register service {'service': 'wallet_ui'}
08:53:59.058 daemon __main__                   : INFO     registered for service wallet_ui
08:53:59.059 daemon __main__                   : INFO     Register service {'service': 'chia plots create'}
08:53:59.059 daemon __main__                   : INFO     registered for service chia plots create
```
INFO logs. Stops here with that dialog. No additional logs after clicking OK.

**Comment by hoffmang9** [comment]
It's the type checking. I'll move over there.

**Comment by jespino** [comment]
@hoffmang9 yes, I'll check it now.

**Comment by jespino** [comment]
Added here: d0383d989c6b97a590a62ec177fbf053ac4c87ca and fixed here #1183

**Pull request merged**
