### PR TITLE
set the execute mode on install-gui.sh

### PR DESCRIPTION
**Pull request by rongou**
In the installation wiki (https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian) there is an instruction to chmod the `install-gui.sh` file
```bash
chmod +x ./install-gui.sh
```
but it seems easier to just set the mode bits in the repo file.

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]
Good idea, thanks!

**Review by wjblanke — APPROVED** [review]
aok

**Comment by evilstack** [comment]
if you run it as `sh install-gui.sh` as per the install docs, the execute permission isn't needed

**Comment by rongou** [comment]
Yeah I edited the wiki to use `sh install-gui.sh`. Once this goes into a new release, I can change it back, sans the `chmod` line.

**Pull request merged**
