### PR TITLE
Add ALLOW_BACKREFS as a flag to get_puzzle_and_solution_for_coin in full_node_api.py

### PR DESCRIPTION
**Pull request by Quexington**

### CODE REVIEW

**Review by arvidn — COMMENTED** [review]
this looks correct. It would be great to paramaterize our test for this function on whether the hard fork has activated or not as well (maybe `conftest.Mode`, to cover soft forks as well)

**Comment by arvidn** [comment]
I think we might want to consider this fix for the 2.0 release branch as well

**Comment by arvidn** [comment]
one issue is that passing in `ALLOW_BACKREFS` not only affects the parsing of the input, it also implies that the *output* is allowed to use backrefs. Which is problematic, because then the full node's response uses this encoding, and our wallet isn't prepared for that. (I was thinking I would have a year about to fix that).

**Comment by emlowe** [comment]
Yea, I think this should be re-targeted to `release/2.0.0`

**Review by emlowe — APPROVED** [review]

**Pull request merged**
