### PR TITLE
Add timing metrics to plot check

### PR DESCRIPTION
**Pull request by aarcro**
I wanted to be more confident I can return proofs in time. I believe if this metric stays under about 25 seconds(?) everything should be fast enough, would love it if someone can confirm this hypothesis.

### CODE REVIEW

**Comment by marcoabreu** [comment]
Be aware that a full proof check will happen very very rarely. So I wouldn't average them but each individual one is important.

I'd also throw an error if they are above ~15s or something like that. You need max 5s for qualities, max 15s for full proof and then you got max 10 secs left to propagate the result.

**Review by parisnakitakejser — DISMISSED** [review]

**Comment by aarcro** [comment]
> Be aware that a full proof check will happen very very rarely. So I wouldn't average them but each individual one is important.
> 
> I'd also throw an error if they are above ~15s or something like that. You need max 5s for qualities, max 15s for full proof and then you got max 10 secs left to propagate the result.

Thanks for the feedback. I put a check in place for the runtime, and promotes from info to warning if it runs long, with a longer warning message. Also removed the average stat since that's not terribly useful.

**Comment by aarcro** [comment]
I'm not sure why the test suite failed. Doesn't seem related to my change, so crossing my fingers for the second attempt here.

**Comment by aarcro** [comment]
@parisnakitakejser Hoping this can get reviewed again and merged.

**Comment by hoffmang9** [comment]
Things that are not portable pool plotting are taking a back seat right now.

**Review by mariano54 — DISMISSED** [review]

**Comment by aarcro** [comment]
Thanks for the review. I can rebase if needed. Or let me know if there's anything else to do before a merge.

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
