### PR TITLE
consolidate `--fingerprint` definitions

### PR DESCRIPTION
**Pull request by altendky**
### Purpose:

Avoid the duplication...  before I make a bunch more adding wallet selection control to the DataLayer commands.

### CODE REVIEW

**Comment by altendky** [comment]
FYI @Quexington @jack60612.

**Review by Quexington — APPROVED** [review]
Big fan of this

**Review by emlowe — APPROVED** [review]
Nice. looks good to me.

**Review by jack60612 — APPROVED** [review]
Lgtm

**Pull request merged**
