### PR TITLE
Add a full node RPC endpoint, get_mempool_item_by_coin_name

### PR DESCRIPTION
**Pull request by kimsk**
### Purpose:
Implement a new endpoint to get mempool item by a coin name mentioned in https://github.com/Chia-Network/chia-blockchain/issues/14810.

#### pytest
tests/core/test_full_node_rpc/test_coin_name_not_found_in_mempool
tests/core/test_full_node_rpc/test_coin_name_found_in_mempool

##### found
image

##### not found
image

### CODE REVIEW

**Comment by Yakuhito** [comment]
Wow - thank you!

**Comment by emlowe** [comment]
Error: The following new issues have been introduced:
chia/rpc/full_node_rpc_api.py:745: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]

`request: Dict[str,Any]` should fix that

**Comment by Yakuhito** [comment]
Hey there! I know I was the one who originally opened an issue, but it seems this endpoint needs to be changed based on #13799. From my understanding, multiple mempool items can now exist that contain the same CoinSpend. I would make the endpoint return a list of those, and name it  `get_mempool_items_by_coin_name`. This could also allow you to delete the `if len(mempool_items) == 0` condition (just return an empty list).

**Comment by kimsk** [comment]
> Easy enough to add a test to test the Exception case on line 747. I suspect the test code can't trigger the if is_overflow_block condition ( I might be inclined to just remove that if check from the test as it doesn't seem relevant to the specific test.)
@emlowe good suggestions. I update the tests and add the exception test (i.e., line 747).

**Comment by kimsk** [comment]
> I would make the endpoint return a list of those, and name it get_mempool_items_by_coin_name. This could also allow you to delete the if len(mempool_items) == 0 condition (just return an empty list).

@Yakuhito  That was my original implementation 😄. Since 1.8.2 allows multiple mempool items with the same coin id now, I agree that we should update the RPC to return a list as well as its name to `get_mempool_items_by_coin_name`.

@emlowe is it fine to just use this PR or you prefer closing this one and re-open the new one?

**Comment by kimsk** [comment]
Use this #16019 instead.

**Pull request closed without merging**
