### PR TITLE
Adding more type annotations (to enable eventually disallow_incomplete_defs) in mypy.ini

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Review by mariano54 — DISMISSED** [review]

**Comment by hoffmang9** [comment]
We should likely revive this.

**Comment by jespino** [comment]
@hoffmang9 I'm ok updating it.

**Comment by jespino** [comment]
@hoffmang9 this is also revived :)

**Comment by mariano54** [comment]
Closing due to merge conflicts, and a lot of this has been done in main.

**Pull request closed without merging**
