### PR TITLE
Assume about 100 nodes for respond_peer limits

### PR DESCRIPTION
**Pull request by tedshroyer**
Due to the frequency settings of respond_peers being the same as request_peers, a full node will Rate limit respond_peer messages as all of the respond peer messages will be retried every second  in send_messages wait_and_retry (chia/server/ws_connection.py:332). PR settings are preventing any 'Rate limiting' on a full_node with 50 connected clients, but may need further consideration for future proofing.

See bad behavior of current rate limit below:
```

(venv) [ec2-user@ip-172-31-45-96 chia-blockchain]$ head ~/.chia/mainnet/log/debug.log.7 
2021-05-02T15:49:17.648 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.649 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.650 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.650 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.650 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.650 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.650 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.650 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.651 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}
2021-05-02T15:49:17.651 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 1}}

(venv) [ec2-user@ip-172-31-45-96 chia-blockchain]$ tail  ~/.chia/mainnet/log/debug.log
2021-05-02T16:34:12.070 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 2}}
2021-05-02T16:34:12.071 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 2}}
2021-05-02T16:34:12.071 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 3}}
2021-05-02T16:34:12.071 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 3}}
2021-05-02T16:34:12.071 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 3}}
2021-05-02T16:34:12.099 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 3}}
2021-05-02T16:34:12.099 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 3}}
2021-05-02T16:34:12.099 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 3}}
2021-05-02T16:34:12.099 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 4}}
2021-05-02T16:34:12.099 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 4}}

(venv) [ec2-user@ip-172-31-45-96 chia-blockchain]$ grep 'Rate limit' ~/.chia/mainnet/log/debug* | wc -l
1069118


(venv) [ec2-user@ip-172-31-45-96 chia-blockchain]$ tail -n 100  ~/.chia/mainnet/log/debug.log
2021-05-02T16:39:55.241 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.241 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.241 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.241 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.241 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.241 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.242 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.242 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.242 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.242 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.242 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.242 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.243 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.243 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.243 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.243 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.243 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.243 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.244 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.245 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.245 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.245 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.245 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.245 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.245 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.246 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.247 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.247 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.247 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.247 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.247 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.247 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.248 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.249 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.249 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.249 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.249 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.249 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.249 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.250 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.251 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.251 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.251 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.251 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.251 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.251 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.252 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.253 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.253 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.253 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.253 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.253 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.253 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.254 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.255 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.255 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.255 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.255 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.256 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.256 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.256 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.256 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.256 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}
2021-05-02T16:39:55.257 full_node full_node_server        : DEBUG    Rate limiting ourselves. message type: respond_peers, peer: {{peer 5}}

```

### CODE REVIEW

**Comment by tedshroyer** [comment]
How can I rerun a check without making a new PR?  I don't see how relaxing the rate limit could cause a wallet failure that seemingly inverted a balance?
```
 >       assert await wallet.get_confirmed_balance() == fund_owners_initial_balance - 101
E       assert 2000000000000 == 1999999999899
E         +2000000000000
E         -1999999999899
```

**Comment by hoffmang9** [comment]
If you can link me to the actions workflow, I can rerun it. Otherwise you can make a trivial additional commit to this PR (like a minor README change) and everything will re-run for you.

**Comment by tedshroyer** [comment]
> If you can link me to the actions workflow, I can rerun it. Otherwise you can make a trivial additional commit to this PR (like a minor README change) and everything will re-run for you.

@hoffmang9 Is this the right link? https://github.com/Chia-Network/chia-blockchain/actions/runs/805229296/workflow

**Comment by hoffmang9** [comment]
Ah - yeah - that one is just a flaky test. You can ignore.

**Comment by tedshroyer** [comment]
@hoffmang9 I can't tell for sure, but I think this rate limiting on respond_peers combined with websocket server retries was making my full_nodes crash.  What do you think about changing "Rate limiting ourselves." to WARNING from DEBUG and combining with this?

**Comment by arvidn** [comment]
This is probably a step in the right direction, however, if someone configures their node to have more than 100 peers, presumably it starts to fail again.

It seems to me the proper fix would be to rate limit these requests *per peer*. i.e. not have a global rate limit.

**Comment by mariano54** [comment]
These limits are already per peer.
This solution won't work, because old peers will still have the low limit, and will disconnect you for exceeding the limit. We need a way to set different limits based on protocol version number.

**Comment by mariano54** [comment]
This is a hacky way to fix this for the time being: 
https://github.com/Chia-Network/chia-blockchain/pull/3508

**Comment by tedshroyer** [comment]
> This solution won't work, because old peers will still have the low limit, and will disconnect you for exceeding the limit. We need a way to set different limits based on protocol version number.
@mariano54 
Will an old peer do anything negative if it gets too many responses for a short time?  It seems it will stabilize after some time as the number of respond_peers responses you should get is equal to the number of request_peers sent

**Comment by tedshroyer** [comment]
Closing PR.  Opening bug #3605 .

**Pull request closed without merging**
