### PR TITLE
Farm page overhaul

### PR DESCRIPTION
**Pull request by embiem**
Creating this draft PR to track my work on this.

This PR will contain the overhauled Farm page and any necessary React general components, like Tooltip and Table.

I also decided to refactor some logic into hooks, which will make it easier to re-use the same data (like total chia farmed) in other places.

Remaining TODOs:

- [ ] get the latest attempted proofs by adding a new RPC to the harvester
- [ ] create a hook to retrieve latest attempted proofs and use it in new Farm page
- [ ] move Plots section of the current Farm page to the Plots page

### CODE REVIEW

**Comment by embiem** [comment]
@hoffmang9 is this work no longer necessary? I was going to add the mentioned TODOs and once finalized un-draft this PR.

**Comment by hoffmang9** [comment]
That was an auto close due to our release process - reopening

**Comment by seeden** [comment]
Hi @embiem. I am doing refactoring of the whole UI application.
I will take a look at this after merge of my branch https://github.com/Chia-Network/chia-blockchain/tree/ui-refactor

**Comment by embiem** [comment]
@seeden alright. I just pushed my latest changes in a new commit. Didn't have too much time to work on this, sadly. Hope it's still useful.

**Comment by embiem** [comment]
@seeden Once you get to it, please give me an update. I'd still like to contribute to the frontend, but don't know what/where I should work on right now. I guess I'd better wait for your UI Refactor first?

**Comment by seeden** [comment]
Hi @embiem. Sure, I will. Thank you

**Comment by hoffmang9** [comment]
I believe this has been superseded by https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta19

I'm going to close this but feel free to start a new PR based on the updated changes

**Pull request closed without merging**
