### PR TITLE
Do not assert if pool_state is none

### PR DESCRIPTION
**Pull request by emlowe**
Possible fix for issues PaulH is seeing in main release #9890

### CODE REVIEW

**Comment by mariano54** [comment]
Hmm this is sketchy. Why would pool state be None? We might be ignoring a valid transaction for the pool wallet

**Comment by emlowe** [comment]
Was a quick test based on some feedback from Straya - it's quite possibly it's not the proper fix.

**Comment by Quexington** [comment]
I had to make this change in the atari branch to support launchers for non-pool singletons but I did it a bit differently although I think semantically these end up being the same thing. https://github.com/Chia-Network/chia-blockchain/blob/c2768d386fbee4ea927604949e1abac6814eac0c/chia/wallet/wallet_state_manager.py#L864

**Comment by Quexington** [comment]
> Hmm this is sketchy. Why would pool state be None? We might be ignoring a valid transaction for the pool wallet

The function will return none if there is no hint to a new state such as during an absorb.  This assertion is likely just for mypy.

**Comment by mariano54** [comment]
> > Hmm this is sketchy. Why would pool state be None? We might be ignoring a valid transaction for the pool wallet
> 
> The function will return none if there is no hint to a new state such as during an absorb. This assertion is likely just for mypy.

I see, thank you for explaining. We should at least have a comment when checking for None that says that it's possible for it to be None in an absorb scenario.

**Review by mariano54 — APPROVED** [review]

**Comment by wjblanke** [comment]
Paul did this fix your issue?

**Pull request merged**
