### PR TITLE
Fixed/disabled some keyring tests. Disabled tests have been addressed…

### PR DESCRIPTION
**Pull request by paninaro**
… in keyring_macos and keyring_windows branches, awaiting PR approval.

### CODE REVIEW

**Review by emlowe — DISMISSED** [review]
seems fine

**Review by jack60612 — DISMISSED** [review]
AOK

**Review by xdustinface — CHANGES_REQUESTED** [review]
Requires some reformatting to make the linter happy.

**Review by jack60612 — DISMISSED** [review]
Looks good after lint fix

**Comment by xdustinface** [comment]
Hmm i'm still getting pretty frequent random failures like below when i test `tests/core/util`:

```
core/util/test_file_keyring_synchronization.py:74 (TestFileKeyringSynchronization.test_multiple_writers)
None != passphrase 13

Expected :passphrase 13
Actual   :None
<Click to see difference>

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/dustinface/chia/chia-blockchain/tests/core/util/test_file_keyring_synchronization.py", line 42, in dummy_set_passphrase
    assert found_passphrase == passphrase
AssertionError: assert None == 'passphrase 13'
"""

The above exception was the direct cause of the following exception:

self = <tests.core.util.test_file_keyring_synchronization.TestFileKeyringSynchronization object at 0x7f70a0574460>

    @using_temp_file_keyring()
    def test_multiple_writers(self):
        # Temporarily disabled. Fixes are in keyring_macos and keyring_windows branches
        if platform != "linux":
            return
    
        num_workers = 20
        keyring_path = str(KeyringWrapper.get_shared_instance().keyring.keyring_path)
        passphrase_list = list(
            map(lambda x: ("test-service", f"test-user-{x}", f"passphrase {x}", keyring_path), range(num_workers))
        )
    
        # When: spinning off children to each set a passphrase concurrently
        with Pool(processes=num_workers) as pool:
            res = pool.starmap_async(dummy_set_passphrase, passphrase_list)
>           res.get(timeout=10)  # 10 second timeout to prevent a bad test from spoiling the fun

test_file_keyring_synchronization.py:90:
```

**Comment by paninaro** [comment]
> Hmm i'm still getting pretty frequent random failures like below when i test `tests/core/util`:
> 
> ```
> core/util/test_file_keyring_synchronization.py:74 (TestFileKeyringSynchronization.test_multiple_writers)
> None != passphrase 13
> 
> Expected :passphrase 13
> Actual   :None
> <Click to see difference>
> 
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/home/dustinface/chia/chia-blockchain/tests/core/util/test_file_keyring_synchronization.py", line 42, in dummy_set_passphrase
>     assert found_passphrase == passphrase
> AssertionError: assert None == 'passphrase 13'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> self = <tests.core.util.test_file_keyring_synchronization.TestFileKeyringSynchronization object at 0x7f70a0574460>
> 
>     @using_temp_file_keyring()
>     def test_multiple_writers(self):
>         # Temporarily disabled. Fixes are in keyring_macos and keyring_windows branches
>         if platform != "linux":
>             return
>     
>         num_workers = 20
>         keyring_path = str(KeyringWrapper.get_shared_instance().keyring.keyring_path)
>         passphrase_list = list(
>             map(lambda x: ("test-service", f"test-user-{x}", f"passphrase {x}", keyring_path), range(num_workers))
>         )
>     
>         # When: spinning off children to each set a passphrase concurrently
>         with Pool(processes=num_workers) as pool:
>             res = pool.starmap_async(dummy_set_passphrase, passphrase_list)
> >           res.get(timeout=10)  # 10 second timeout to prevent a bad test from spoiling the fun
> 
> test_file_keyring_synchronization.py:90:
> ```

What version of Ubuntu are you running? I've been trying to repro this on 20.04.3 with Python 3.9.6 as well as Python 3.8.12, but I'm not seeing any failures. I'll note that I have seen these failures on macOS, and made some changes in the keyring_macos branch to address them. If need be, I can try applying just those changes in this branch to see if they fix the issue on Linux.

**Comment by paninaro** [comment]
> > Hmm i'm still getting pretty frequent random failures like below when i test `tests/core/util`:
> > ```
> > core/util/test_file_keyring_synchronization.py:74 (TestFileKeyringSynchronization.test_multiple_writers)
> > None != passphrase 13
> > 
> > Expected :passphrase 13
> > Actual   :None
> > <Click to see difference>
> > 
> > multiprocessing.pool.RemoteTraceback: 
> > """
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
> >     result = (True, func(*args, **kwds))
> >   File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
> >     return list(itertools.starmap(args[0], args[1]))
> >   File "/home/dustinface/chia/chia-blockchain/tests/core/util/test_file_keyring_synchronization.py", line 42, in dummy_set_passphrase
> >     assert found_passphrase == passphrase
> > AssertionError: assert None == 'passphrase 13'
> > """
> > 
> > The above exception was the direct cause of the following exception:
> > 
> > self = <tests.core.util.test_file_keyring_synchronization.TestFileKeyringSynchronization object at 0x7f70a0574460>
> > 
> >     @using_temp_file_keyring()
> >     def test_multiple_writers(self):
> >         # Temporarily disabled. Fixes are in keyring_macos and keyring_windows branches
> >         if platform != "linux":
> >             return
> >     
> >         num_workers = 20
> >         keyring_path = str(KeyringWrapper.get_shared_instance().keyring.keyring_path)
> >         passphrase_list = list(
> >             map(lambda x: ("test-service", f"test-user-{x}", f"passphrase {x}", keyring_path), range(num_workers))
> >         )
> >     
> >         # When: spinning off children to each set a passphrase concurrently
> >         with Pool(processes=num_workers) as pool:
> >             res = pool.starmap_async(dummy_set_passphrase, passphrase_list)
> > >           res.get(timeout=10)  # 10 second timeout to prevent a bad test from spoiling the fun
> > 
> > test_file_keyring_synchronization.py:90:
> > ```
> 
> What version of Ubuntu are you running? I've been trying to repro this on 20.04.3 with Python 3.9.6 as well as Python 3.8.12, but I'm not seeing any failures. I'll note that I have seen these failures on macOS, and made some changes in the keyring_macos branch to address them. If need be, I can try applying just those changes in this branch to see if they fix the issue on Linux.

I could also just disable the test for now and see if the issue is addressed by my other PRs

**Comment by xdustinface** [comment]
@paninaro I'm on Ubuntu 20.04.2 with Python 3.8.10. Funny that you don't see any issues since this is very reproducible here.

I think its the best if you enable those two tests with this PR for CI so that we can see if we get the failures there too.

**Comment by xdustinface** [comment]
@paninaro If you look here https://github.com/Chia-Network/chia-blockchain/pull/8728/checks?check_run_id=3805092276 its not only me, CI also gets failures for `test_multiple_writers`.

**Comment by paninaro** [comment]
Replaced by https://github.com/Chia-Network/chia-blockchain/pull/8766

**Pull request closed without merging**
