### PR TITLE
`@dataclass` `FullNode` to avoid risks of instances without attributes set

### PR DESCRIPTION
**Pull request by altendky**
While running 1.0rc8 I did a `chia stop -d all` and noticed the following traceback in the log.  In the same `if` block I noticed the other not-initialized attributes as well.  I don't know if the error is indicative of another problem, but it seems that these should at least be initialized to `None` and type hinted accordingly.

```python-traceback
Traceback (most recent call last):
  File "/home/chia/.local/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/chia/chia-blockchain/src/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/chia/chia-blockchain/src/server/start_service.py", line 211, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/home/chia/chia-blockchain/src/server/start_service.py", line 162, in _accept_signal
    self.stop()
  File "/home/chia/chia-blockchain/src/server/start_service.py", line 172, in stop
    self._node._close()
  File "/home/chia/chia-blockchain/src/full_node/full_node.py", line 503, in _close
    if self.blockchain is not None:
AttributeError: 'FullNode' object has no attribute 'blockchain'
```

### CODE REVIEW

**Comment by mariano54** [comment]
It's only an issue before the green flag hits, but it should not cause any issues. I decided against fixing this, to minimize changes before mainnet.

**Comment by altendky** [comment]
@mariano54 is that a suggestion to abandon the change?  Or just that it's not worth changing in the midst of everything else this week?  I have no reason to prioritize this.  It just seemed that `is not None` checks ought not fail with an `AttributeError`.

**Comment by mariano54** [comment]
Yeah we should abandon, since we will remove the whole green flag system after launch is done, so we can normally initialize everything when we create the object

**Comment by mariano54** [comment]
Anyway, thanks for making the PR!

**Comment by altendky** [comment]
@mariano54, maybe you'll get a small chuckle anyways out of this necro-PR'ing.

I think the actual issue was addressed in https://github.com/Chia-Network/chia-blockchain/pull/12447 and at the time I didn't bother to trick GitHub into allowing me to resurrect this, so, I'll use it for this `@dataclass` application that will avoid future related issues.

**Review by xdustinface — DISMISSED** [review]

**Review by emlowe — DISMISSED** [review]

**Review by emlowe — APPROVED** [review]

**Pull request merged**
