### PR TITLE
Windows 64bit: Mutiple windows getting opened on its own

### PR DESCRIPTION
**Pull request by SS20201978**
I had left Chia for plotting.
Issue 1) After a day i can find around 5 windows opened up with "keys" screen displayed.
image
Issue 2) When i selected the private key it went to "wallet" screen. When i clicked "plot" screen existing lot information is no more there.
All the five screens same state.
Issue 3) I closed 1 screen. All five screens got closed after a warning:
image
image
Present state:
All screens are closed:
image
image
image

### CODE REVIEW

**Comment by Yostra** [comment]
I think you intended to create a new issue, I'm closing this PR.

https://github.com/Chia-Network/chia-blockchain/issues/new/choose

**Comment by Yostra** [comment]
I, copied it here: https://github.com/Chia-Network/chia-blockchain/issues/428

**Comment by SS20201978** [comment]
Thanks. So are you taking care of the issue? Or I need to post it somewhere
else?

**Comment by Yostra** [comment]
Yup, no need to repost. Thx for reporting this bug.

**Pull request closed without merging**
