### PR TITLE
Ms.new breaking changes

### PR DESCRIPTION
**Pull request by mariano54**
This PR makes some notable breaking changes in preparation for mainnet.

1. The formula for computing iterations is simplified, so that only one division is necessary, and inverting the (1-x) into just x. 
2.There are new timestamp rules. A block N must have a greater timestamp than block N-1. Also, a block's timestamp cannot be more than 5 minutes in the future.
3. A List[Tuple[uint16, str]] is added to the handshake. These are the capabilities that the node supports, to add new features to the protocol.
4. The message_id is now before the data in each message.

### CODE REVIEW

**Review by bramcohen — APPROVED** [review]
Looks good but we should double-check exactly what the maximum k is (looks like it's 59 inclusive?)

**Comment by mariano54** [comment]
Yeah, do you want to change that value?

**Comment by bramcohen** [comment]
> Yeah, do you want to change that value?

We probably want to leave it where it is, but we should check that it really is the maximum it can be and that we're documenting it correctly. If I recall correctly the limiting factor on how big it can be is in the middle tables which need to produce 4*k bits for the metadata plus another k bits for the bucket, which adds up to 5*k total bits and 59*5 = 295 which is larger than the 256 bits of output which are produced by blake3, so either I'm remembering this wrong or the value is set or documented wrong. All are possible.

**Review by hoffmang9 — APPROVED** [review]
Did you and @bramcohen get to a final answer on 59 inclusive or exclusive for k?

**Comment by mariano54** [comment]
Not yet, we need to look at chiapos to see what values can be allowed. Anyways, nobody will be passing k=50 at any point in the next few years, so we have some time

**Comment by hoffmang9** [comment]
A very, very good point. 👍🏻

**Comment by mariano54** [comment]
Although now that I think about it, it might be good to cap it at 50 just in case, if we are not confident of the behaviour of chiapos with k>50

**Comment by hoffmang9** [comment]
And I'm confident that it's the only one that exists in the universe.

**Pull request merged**
