### PR TITLE
Remote UI

### PR DESCRIPTION
**Pull request by dkackman**
This PR enables the react UI to interact with deamons running on remote machines. This allows the farmer/wallet/full node to be run headless on a pi, but still be graphically managed via the react UI.

With these changes the UI can be run via electron and also as a node module with a browser based UI. In either mode, the UI can interact with a daemon on the `localhost` or remotely (with `localhost` always being the default). Whenever running in the browser, or with a remote daemon, the UI will not attempt to start or stop the daemon. When running via electron, on the same machine as the daemon, it will start and stop along with the UI as it currently does.

To test the node app
````
cd electron-react
npm install
npm start
````
A browser will open at `localhost:3000` to host the UI. To attach the browser UI to a remote daemon, the remote host name can be supplied as a query parameter: `localhost:3000?selfHostName=<remote machine name or ip>`

To run the electron UI against a remote daemon, the remote host name can be passed via the command line: `Chia.exe --selfHostName=<remote machine name or ip>`

In all cases the UI expects the daemon to be listening on port 55400. 

To run the UI from a browser, the _nodejs_ service needs to be running somewhere on the network. Depending on where you run the _nodejs_ service you may need to change the port the daemon listens to:
- If the _nodejs_ service and dameon are not on the same machine, `config.yaml` needs to have the daemon listen on `0.0.0.0` instead of `localhost`. Find the unindented line `self_hostname: localhost` and change it to `self_hostname: 0.0.0.0`. _note:_ doing this intentionally exposes the daemon on the network, so firewall rules should be such that traffic is restricted to only the UI hosts you intend. With `ufw` for instance add a rule like this `ufw allow from <ip of ui machine> to any port 55400 proto tcp`
- Alternatively the _nodejs_ service can run on that same server as the daemon, in which case the service can talk to the daemon on `localhost `but will need setup to be hosted. [pm2](https://pm2.keymetrics.io/docs/usage/quick-start/) is a simple solution to host a nodejs service. It has advantages for simplicity of use and security. (you'd still want to use firewall or webserver rules to control client access as the UI does not authenticate.)

from the electron-react directory
````
npm run build
cd build
pm2 serve . 3000
pm2 startup
pm2 save
````
will build, serve, and daemonize the nodejs service as well as restart it at boot

### CODE REVIEW

**Comment by dkackman** [comment]
@mariano54 - this is the new PR for remote ui. The current dev branch is throwing an Unknown Error in the react UI on `selectKeys` which I believe is related to other changes in dev. I haven't had a chance to debug but I'm 90% sure it isn't related to these changes. I could use some help being sure about that though. Setting to a draft state.

**Comment by hoffmang9** [comment]
Making sure both @Yostra and @seeden see this too.

**Comment by dkackman** [comment]
When clicking Select Key option on the first screen. Consistent repro on my setup.

image

**Comment by seeden** [comment]
I will merge/add this feature after my refactoring.

**Comment by Yostra** [comment]
@dkackman  can you set log level to INFO and check if there's something being logged when that error happens?

**We need client ssl authentication before merging this into dev.** 

Also there is functionality that gets lost when ui and daemon are split away, this is ok, as long as we alert user that this functionality is not supported and not fail silently.

Drag and drop functionality in different use cases [Recovery form backup file, Trades].
This fails because UI sends path to drag&dropped file and service has to be on same machine to access it.

Logging in plotting fails for same reason but in different direction. We pipe the plotting logs to a file and then tail that file from the electron.

We could merge this into a different branch and continue with development, SSL support was on our TODO already.

**Comment by dkackman** [comment]
> @dkackman can you set log level to INFO and check if there's something being logged when that error happens?

Will do.

> We could merge this into a different branch and continue with development, SSL support was on our TODO already.
That makes sense. I didn't vet the entire UI and it'd make sense to disable or remove features that don't work remotely.

**Comment by dkackman** [comment]
@Yostra 
This is what shows up in the logs when I see that error on SelectKeys:

````
13:38:36.085 wallet src.rpc.rpc_server         : INFO     Rpc call <- log_in
13:38:36.096 wallet aiosqlite                  : ERROR    exception occurred while closing connection
Traceback (most recent call last):
  File "aiosqlite\core.py", line 158, in close
  File "aiosqlite\core.py", line 64, in _conn
ValueError: no active connection
13:38:36.152 wallet src.rpc.rpc_server         : INFO     Rpc response -> log_in
13:38:36.161 wallet wallet_server              : INFO     Received EOF from ('127.0.0.1', 8444), closing connection.
13:38:36.097 full_node full_node_server        : INFO     Received EOF from ('127.0.0.1', 58530), closing connection.
````

**Comment by dkackman** [comment]
@Yostra Is it the daemon's service that needs to have SSL added? When I `($env:HTTPS = "true") -and (npm start)` the web socket is properly upgraded by CSP to `wss` but the daemon does not respond.

**Comment by Yostra** [comment]
@dkackman The error look like there's some DB issue, I would delete the db file and try again. 

Yes, 
Something similar to this needs to be added to the daemon.
https://github.com/Chia-Network/chia-blockchain/blob/301801993ca3d4cc5bf71952af29effae507b2ea/src/server/ssl_context.py#L21

We currently generate SSL certs for comm between [fullnode <-> farmer] and [farmer <-> harvester]. We could reuse that one. (We need to do both client and server authentication with it)

From UX perspective, client needs to be able to pick a cert it wants to use for remote server, and remote daemon server should have path to the cert in config or accept CLI args. 

(all of this benefits even when not using the remote server)

**Comment by dkackman** [comment]
> 
> 
> @dkackman The error look like there's some DB issue, I would delete the db file and try again.
> 
I can repro this on a clean db and with a fresh pull from dev. Have you been able to repro it?
> 
> From UX perspective, client needs to be able to pick a cert it wants to use for remote server, and remote daemon server should have path to the cert in config or accept CLI args.
> 
> (this should be done by default for local connection as well)

All makes sense. When I get over the above hurdle I can make a start.

**Pull request merged**
