### PR TITLE
Update workflows to use GITHUB_OUTPUT

### PR DESCRIPTION
**Pull request by zcomputerwiz**
Use GITHUB_OUTPUT in workflows instead of set-output.

GitHub is deprecating set-output as per their blog:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### CODE REVIEW

**Comment by zcomputerwiz** [comment]
I added checks for OS in the Tests and Benchmarks workflows to use PowerShell syntax for Windows or Bash for others.
An alternative could be to specify shell: Bash instead though I have not tested that.

I also added workflow_dispatch to the MacOS and Linux ARM64 build workflows for the convenience of on-demand runs and consistency with the other build workflows.

**Review by altendky — CHANGES_REQUESTED** [review]
1) I created conflicts for you (sorry...) by changing the setup Python actions to all use our wrapper where you had updated at least some of them.
2) The benchmarks workflow is Linux only so no need for compatibility complexity there.  If we need that I would prefer the change to be done in a separate PR.
3) I think I would rather see the `shell: bash` option so we can reduce the duplication around the caching.  I may at some point push for using bash everywhere since the point of our CI setup isn't to test if we can write PowerShell.  `:]`

Thanks again for the work here and for identifying the failures in my similar PR.  I'm very much looking forward to eliminating all those annotations on the build.

**Comment by altendky** [comment]
I'm also happy to just make the changes if you prefer that, I don't need to dump tedious work on you.  I just try not to take over other people's contributions without they're approval.

**Comment by zcomputerwiz** [comment]
No worries, I'll make the changes!

**Review by altendky — APPROVED** [review]
Thanks for helping with the cleanup.  With this I think we're getting close to dealing with all the annotations.  Well, other than the closed event loop stuff...

**Comment by altendky** [comment]
Sorry for the wait here, I'm going to try to get this the rest of the way through the process.

**Review by emlowe — APPROVED** [review]

**Review by cmmarslender — APPROVED** [review]

**Comment by wallentx** [comment]
@zcomputerwiz it looks like your commits in this PR are unsigned, which is blocking us from merging due to branch protection rules that we have in place. To save you the trouble of attempting to clean all these up for resubmission, I've created a separate PR, where you will see that you are fully accredited for authorship https://github.com/Chia-Network/chia-blockchain/pull/13911
Please feel free to review it for accuracy.

I'll work on getting that one merged in, and will close this PR for now.

**Pull request closed without merging**
