### PR TITLE
Remove code related to no-longer-used websockets library

### PR DESCRIPTION
**Pull request by altendky**
Follow up after https://github.com/Chia-Network/chia-blockchain/pull/10611.

### CODE REVIEW

**Review by hoffmang9 — DISMISSED** [review]
lgtm

**Review by jack60612 — APPROVED** [review]
lgtm

**Comment by jack60612** [comment]
@altendky can you also remove websockets from [https://github.com/Chia-Network/chia-blockchain/blob/2a6564c0a7741ad84d38afae9670db8ca0a0cd4d/pylintrc#L253](https://github.com/Chia-Network/chia-blockchain/blob/2a6564c0a7741ad84d38afae9670db8ca0a0cd4d/pylintrc#L253) And [https://github.com/Chia-Network/chia-blockchain/blob/c5426068aaed59efeb9fc3c763935d96e4f8df42/tests/core/daemon/test_daemon.py#L88](https://github.com/Chia-Network/chia-blockchain/blob/c5426068aaed59efeb9fc3c763935d96e4f8df42/tests/core/daemon/test_daemon.py#L88)

**Review by jack60612 — CHANGES_REQUESTED** [review]
Not all logging tweaks were removed, check my comments.

**Review by jack60612 — APPROVED** [review]
Thank you, lgtm and sorry for missing that before.

**Pull request merged**
