### PR TITLE
CHIA-1685 Simplify return values for validate_block_body

### PR DESCRIPTION
**Pull request by AmineKhaldi**
### Purpose:

There is no need to return the conditions that we already receive as input.

### Current Behavior:

We currently accept conditions as input and then return them back when the block is valid, along with the validation outcome.

### New Behavior:

We just return the validation outcome.

### CODE REVIEW

**Review by arvidn — COMMENTED** [review]
looks good. Would it be OK to land https://github.com/Chia-Network/chia-blockchain/pull/18812 first though? I think this PR would be easier to rebase

**Comment by AmineKhaldi** [comment]
> looks good. Would it be OK to land #18812 first though? I think this PR would be easier to rebase

Yep, let's do that.

**Comment by arvidn** [comment]
this is the missing coverage:
```
chia/consensus/block_body_validation.py (58.3%): Missing lines 237,249,345,347,349,388,391,416,422,428,512,523,527,536,552
```

IT seems like a lot of lines. are they all reasonable to not have coverage for?

**Comment by AmineKhaldi** [comment]
> this is the missing coverage:
> 
> ```
> chia/consensus/block_body_validation.py (58.3%): Missing lines 237,249,345,347,349,388,391,416,422,428,512,523,527,536,552
> ```
> 
> IT seems like a lot of lines. are they all reasonable to not have coverage for?

All of them exist before this PR.

**Review by arvidn — APPROVED** [review]

**Pull request merged**
