### PR TITLE
Change the block generator output format to allow adding more fields …

### PR DESCRIPTION
**Pull request by aqk**
…in future

### CODE REVIEW

**Review by richardkiss — DISMISSED** [review]
Looks great!

**Comment by aqk** [comment]
THIS WILL BREAK CONSENSUS.

A lot.

**Comment by mariano54** [comment]
Note: test_block_compression test is disabled by accident in main, this test should be enabled in this PR

**Review by atyhieu — APPROVED** [review]

**Review by atyhieu — APPROVED** [review]

**Review by atyhieu — APPROVED** [review]

**Review by atyhieu — APPROVED** [review]

**Comment by aqk** [comment]
This PR is superseded by https://github.com/Chia-Network/chia-blockchain/pull/2084

**Pull request closed without merging**
