### PR TITLE
Remove mempool checking for exact replacement set

### PR DESCRIPTION
**Pull request by Quexington**
Right now the mempool checks that a spend bundle that is meant to replace another spend bundle has the exact same coins being spent within it.  I'm not sure what the reason for this is, but it creates a problem when thinking about offers:

If someone (maker) makes an offer, they create a partial spend bundle.  If someone (taker) then takes the offer, they fill the spend bundle in with their own coins in addition to the coins of the maker.  The taker could push the now complete offer into the mempool with zero fee and have it sit there for potentially hours.  Meanwhile, the maker sees a drop in the price of the asset they were requesting, so they go to create a transaction which cancels their offer at all cost (a fee of 1XCH we'll say).  The maker's cancellation spend bundle can never make it into the mempool with the current logic.  They can only cancel their coins, not the ones the taker added, and they are therefore ineligible to replace the slow transaction because they cannot spend the exact set of coins.

### CODE REVIEW

**Review by arvidn — APPROVED** [review]

**Review by mariano54 — CHANGES_REQUESTED** [review]
I do not agree with this change. It adds a potential attack. 
The attack is that someone can first bundle my transaction with theirs. Then, they perform this replacement attack and remove my piece from the bundle. My transaction will now be removed from the mempool because of this logic.

Attacks that are outside of the mempool should be handled outside of the mempool. If the centralized matching system allows for those attacks, it should be fixed there.

**Comment by arvidn** [comment]
I don't understand that attack. Is this assuming that you haven't posted your bundle to the network yet? or that someone early on intercepts it and adds its own parts to it?

once your bundle is in the mempool, it can't be pushed out by this technique, right?

**Comment by Quexington** [comment]
I'm not sure I understand either.  The only way that someone could push your spend bundle out of the mempool is if they could spend one of the coins in it.  If both parties can spend the coin, the transaction with the higher fee can and should replace the other one.

**Comment by arvidn** [comment]
I suppose you could first add your new spend bundle, which incorporates the victim bundle, with a high fee. That will replace the victim, right? Then you can replace your bundle with a new one that doesn't have the victim in it, with an even higher fee, which will replace it and the victim is dropped

**Comment by Quexington** [comment]
I see, well that would have been possible previously too because you've described creating a superset which is what the check was checking for.

**Comment by arvidn** [comment]
the last step wouldn't be possible, which is where you actually drop the victim bundle

**Comment by Quexington** [comment]
Oh yeah I see.  Okay so that's what the reason for the check was, makes sense.

**Comment by arvidn** [comment]
this attack should be explained in the code or the test.

an alternative (which may not be feasible) would be to keep the original (replaced) bundle around, and once it's no longer conflicting with anything, we add it back, with its original place-in-line. It might expose us to a DoS of keeping tons of bundles around

**Comment by mariano54** [comment]
> this attack should be explained in the code or the test.
> 
> an alternative (which may not be feasible) would be to keep the original (replaced) bundle around, and once it's no longer conflicting with anything, we add it back, with its original place-in-line. It might expose us to a DoS of keeping tons of bundles around

Yeah this alternative is more optimal from the farmer's perspective, which is what we want (maximize fees). But it does add some complexity and requires supporting signature subtraction in BLS. One way to do it is to only replace when it's either a superset or a subset, and when the new bundle has both higher fee and higher fee per cost. This would require the attacker to actually spend funds if they want to attack it.

**Comment by mariano54** [comment]
added comment:
https://github.com/Chia-Network/chia-blockchain/pull/9632/files

**Comment by Quexington** [comment]
Closing this PR in deference to a more sophisticated implementation later.

**Pull request closed without merging**
