### PR TITLE
stop using deprecated set-output

### PR DESCRIPTION
**Pull request by altendky**
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

1. `"::set-output name=(.*)::(.*)"` -> `"$1=$2" >> \$GITHUB_OUTPUT`
2. `::set-output name=(.*)::(.*)` -> `"$1=$2" >> \$GITHUB_OUTPUT`

### CODE REVIEW

**Comment by altendky** [comment]
fyi @wallentx and @cmmarslender

**Comment by altendky** [comment]
Apparently I totally didn't understand something...

**Review by zcomputerwiz — COMMENTED** [review]
I had opened a pull request ( #13730 ) to update this as well - and I encountered the same problems with the Windows build and test workflows at first but did get them all working.

One solution is to use the Windows PowerShell syntax instead, the other would be to specify shell: Bash in the get pip and npm cache directory steps. I have not tried the second since the first seems to work just fine.

**Comment by altendky** [comment]
Yeah, your PR was pointed out to me this morning.  Thanks for the contribution.  I have run projects with bash on all systems for the workflows but I think we're not doing that here, and I indeed fail to handle the Windows case properly.  We'll look through these PRs when we get a chance and get something in.

**Pull request closed without merging**
