### PR TITLE
added height check

### PR DESCRIPTION
**Pull request by wjblanke**

### CODE REVIEW

**Comment by arvidn** [comment]
we really should have a unit test exercising the `cs_height` > `height`.

**Comment by wjblanke** [comment]
It looks like this is double checked in can_use_peer_request_cache() which seems to be the only place that uses this cache

**Comment by wjblanke** [comment]
if coin_state.created_height is not None and coin_state.created_height > fork_height:
        return False
    if coin_state.spent_height is not None and coin_state.spent_height > fork_height:
        return False

**Comment by mariano54** [comment]
We should still fix this I think

**Pull request closed without merging**
