### PR TITLE
Timeout for retrieving a decompressor.

### PR DESCRIPTION
**Pull request by fchirica**
If no decompressor is available within `decompressor_timeout` seconds, we abort the operation.

### CODE REVIEW

**Review by emlowe — DISMISSED** [review]

**Review by wallentx — DISMISSED** [review]
Several CLI commands are broken, and it seems the macos chiapos wheels are somehow invalid?

**Comment by altendky** [comment]
The wheel check was run on macOS 10.14 seemingly.

https://github.com/Chia-Network/chia-blockchain/actions/runs/5871107557/job/15921053154?pr=16047#step:5:15
> platform: macOS-10.14.6-x86_64-i386-64bit

https://github.com/Chia-Network/chia-blockchain/actions/runs/5871107557/job/15921053154?pr=16047#step:1:2
> Runner name: 'macpro-01-mojave-01-msp'

But...  we ask for 11.

https://github.com/Chia-Network/chia-blockchain/blob/7b9801fa7f8be84f528f8aa0d09eeb685676053a/.github/workflows/check_wheel_availability.yaml#L36

They still list `macos-11` as valid here at least.  https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by altendky** [comment]
Nevermind, https://github.com/Chia-Network/chia-blockchain/actions/runs/5871107557/workflow?pr=16047#L36 that build actually asked for `macos-10.14` specifically...

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/commit/29c1e1c38008a213509ffcd4aebdbb8ae9f01a15 is on `main` and not on `release/2.0.0`.  So either we go back to building 10.14 wheels for now or we get the 10.14 drop updates into release.

**Review by emlowe — APPROVED** [review]

**Pull request merged**
