### PR TITLE
Update GUI and changelog for 1.0.2

### PR DESCRIPTION
**Pull request by hoffmang9**
### Added

- We have released version 1.0.0 of [chiapos](https://github.com/Chia-Network/chiapos). This includes a 20% speed increase for bitfield plotting compared to the previous version on the same machine. In many cases this will mean that bitfield plotting is as fast or faster than non bitfield plotting.
- @xorinox improved our support for RedHat related distributions in `install.sh`.
- @ayaseen improved our support for RedHat related distributions in `install-timelord.sh`.
- We have addded Dutch and Polish to supported translations. Thanks @psydafke, @WesleyVH, @pieterhauwaerts, @bartlomiej.tokarzewski, @abstruso, @feel.the.code, and @Axadiw for contributions to [translations on Crowdin](https://crowdin.com/project/chia-blockchain).
- The GUI now supports "Exclude final directory" when plotting. This is found in the Advanced Options for step 2 on the plot creation page.

### Changed

- Wallet now uses a trusted node and, when syncing from that node, Wallet does not do as many validations.
- @jespino changed `chia keys show` to require the `--show-mnemonic-seed` before it displays your 24 work private key mnemonic.
- We decreased the size of the block cache in node to perform better with longer chains.
- @Flofie caught an error in CONTRIBUTING.md.
- We no longer rely on aiter so it has been removed.
- Keyring deprecated the use of OS_X in favor of MacOS.
- "Broken pipe" error was decreased to a warning.
- Many non critical log messages were decreased from warning to info log level.
- Harvester should now log the plot file name if it finds a bad plot at error log level.

### Fixed

- Peer ips were being written to the database on a per ip basis. This caused a lot of wasted disk activity and was costing full node performance.
- We fixed an issue where the last block wasn't fetched by the GUI.
- There was an edge case with full node store that can stall syncing.
- There was a potential node locking issue that could have prevented a Timelord from getting a new peak and cause a chain stall.
- We did not correctly support some Crowdin locales. Pirate English was starting to overwrite US English for example.

### CODE REVIEW

**Comment by NuAngel** [comment]
Can someone provide more details on "exclude final directory?" Does this just mean the resulting plot file is not moved from a temporary directory to a final directory, it's just plotted and then farmed from one single directory?

**Comment by PsyDafke** [comment]
> Can someone provide more details on "exclude final directory?" Does this just mean the resulting plot file is not moved from a temporary directory to a final directory, it's just plotted and then farmed from one single directory?

No, it's just an option, to exclude the destination folder on a plotter, to be added to it's harvester config.
More specific, when you have a shared storage as destination for multiple plotters, and 1 farmer has it al ready in it's harvester config... the other plotters won't farm that same dir x times.

**Comment by hoffmang9** [comment]
It means that a new directory is not created 
image

**Comment by NuAngel** [comment]
@hoffmang9 not created in the Harvester specifically, but the plot file can still be moved to a "final" directory, correct? Just not added to the active Harvester? I believe that's what @PsyDafke was explaining.

I hope you can see my confusion. I'm also trying to get more clear answers for people asking in the Chia subreddit.

**Comment by PsyDafke** [comment]
> @hoffmang9 not created in the Harvester specifically, but the plot file can still be moved to a "final" directory, correct? Just not added to the active Harvester? I believe that's what @PsyDafke was explaining.
> 
> I hope you can see my confusion. I'm also trying to get more clear answers for people asking in the Chia subreddit.

It has noting to do with the plotting process. Plots will still be moved to the destination folder, but the plotter won't add that folder to it's own harvester aka in it's config.yaml.
Like I explained before, this is just a specific scenario, where multiple plotters share a destination. You don't wan't each plotter to add that same destination to their config, and all start harvesting the same plotfiles.

**Pull request merged**
