### PR TITLE
add DataLayer batch insert benchmark

### PR DESCRIPTION
**Pull request by altendky**
### Testing Notes:

Draft For:
- [x] Reviewing sumo vs. beast runtimes and selecting final limits https://github.com/Chia-Network/chia-blockchain/pull/15656

### CODE REVIEW

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/actions/runs/5393572228/jobs/9793500029?pr=15645#step:10:3369
```
FAILED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=100-pre_count=1000] Asserting maximum duration: test_benchmark_batch_insert_speed[count=100-pre_count=1000]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 1.6951037489999408
    overhead: 2.5463799988756364e-05
     allowed: 1e-06
     percent: 169510375 %

FAILED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=1000-pre_count=0] Asserting maximum duration: test_benchmark_batch_insert_speed[count=1000-pre_count=0]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 12.462575949999973
    overhead: 2.5296900014382116e-05
     allowed: 1e-06
     percent: 1246257595 %

FAILED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=1000-pre_count=1000] Asserting maximum duration: test_benchmark_batch_insert_speed[count=1000-pre_count=1000]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 14.597117126999933
    overhead: 2.574209996737409e-05
     allowed: 1e-06
     percent: 1459711713 %
```

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/actions/runs/5393572228/jobs/9794169186#step:10:3368
```
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=100-pre_count=0] Asserting maximum duration: test_benchmark_batch_insert_speed[count=100-pre_count=0]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 0.8875016399999822
    overhead: 2.6592199969854845e-05
     allowed: 1e-06
     percent: 88750164 %

FAILED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=100-pre_count=1000] Asserting maximum duration: test_benchmark_batch_insert_speed[count=100-pre_count=1000]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 1.4420034039999337
    overhead: 2.623199999334247e-05
     allowed: 1e-06
     percent: 144200340 %

FAILED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=1000-pre_count=0] Asserting maximum duration: test_benchmark_batch_insert_speed[count=1000-pre_count=0]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 12.61665311899992
    overhead: 2.698880001616999e-05
     allowed: 1e-06
     percent: 1261665312 %

FAILED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[count=1000-pre_count=1000] Asserting maximum duration: test_benchmark_batch_insert_speed[count=1000-pre_count=1000]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1305
    run time: 14.61410799700002
    overhead: 2.4791299995285954e-05
     allowed: 1e-06
     percent: 1461410800 %

FAILED
```

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/actions/runs/5394223238/jobs/9795089484?pr=15645#step:10:2910
```
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[pre=0,count=100] Asserting maximum duration: test_benchmark_batch_insert_speed[pre=0,count=100]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1337
    run time: 0.8579352660000268
    overhead: 2.5736900010997487e-05
     allowed: 1.2
     percent: 71 %
PASSED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[pre=1000,count=100] Asserting maximum duration: test_benchmark_batch_insert_speed[pre=1000,count=100]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1337
    run time: 1.4282826529999966
    overhead: 2.523130001463869e-05
     allowed: 2
     percent: 71 %
PASSED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[pre=0,count=1000] Asserting maximum duration: test_benchmark_batch_insert_speed[pre=0,count=1000]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1337
    run time: 12.417243099000075
    overhead: 2.5559200014413364e-05
     allowed: 15
     percent: 83 %
PASSED
tests/core/data_layer/test_data_store.py::test_benchmark_batch_insert_speed[pre=1000,count=1000] Asserting maximum duration: test_benchmark_batch_insert_speed[pre=1000,count=1000]
/home/ubuntu/actions-runner/_work/chia-blockchain/chia-blockchain/tests/core/data_layer/test_data_store.py:1337
    run time: 14.556486317000008
    overhead: 2.586880000308156e-05
     allowed: 18
     percent: 81 %
PASSED
```

**Review by emlowe — DISMISSED** [review]

**Comment by emlowe** [comment]
code coverage exemption for benchmark tests - (well the code clearly runs, so there really isn't a coverage gap)

**Review by paninaro — APPROVED** [review]

**Pull request merged**
