### PR TITLE
add benchmark for MempoolManager.add_spendbundle

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
this produces output like this:

```
Building SpendBundles
  peer 0
     reward coins
     spend bundles
  peer 1
     reward coins
     spend bundles
  peer 2
     reward coins
     spend bundles
  peer 3
     reward coins
     spend bundles
  peer 4
     reward coins
     spend bundles
Single-threaded
Profiling add_spendbundle()
initialize MempoolManager
output written to: mempool-add-st.png
add_spendbundle time: 4.2477s
4.25ms per add_spendbundle() call
output written to: mempool-create-st.png
create_bundle_from_mempool time: 3.6301s
Building SpendBundles
  peer 0
     reward coins
     spend bundles
  peer 1
     reward coins
     spend bundles
  peer 2
     reward coins
     spend bundles
  peer 3
     reward coins
     spend bundles
  peer 4
     reward coins
     spend bundles
Multi-threaded
Profiling add_spendbundle()
initialize MempoolManager
output written to: mempool-add-mt.png
add_spendbundle time: 2.1249s
2.12ms per add_spendbundle() call
output written to: mempool-create-mt.png
create_bundle_from_mempool time: 3.6885s
```

as well as profiles generated by `gprof2dot` + `graphviz`

**Review by trepca — APPROVED** [review]
tested it locally, works well

it might be good to also test things with more extreme spend bundle sizes, like minting a couple NFTs or a complex puzzle

**Review by mariano54 — APPROVED** [review]
This is very useful! Looks like it's pretty efficient already, considering BLS validation can take 1-3ms.

**Comment by arvidn** [comment]
>  Looks like it's pretty efficient already, considering BLS validation can take 1-3ms.

The purpose of the single-threaded variant is to get a profile of what's happening on the worker threads, to be able to optimize that as well.

The most relevant metric is the multi-threaded one, where the measurement is of time spent in the main thread. The precious time. 2.1 ms versus 4.25 ms isn't a great speed-up. There's a material work done in the "sequential part".

I have some outstanding patches to address some of that though.

**Comment by arvidn** [comment]
if we increase the mempool size to 50 blocks. Each block fits approximately 2000 spend bundles. Adding 1 spend bundle takes 2.1ms, but only 21% of that time is actual CPU time on the main thread (the other time is idling, waiting for the worker thread). So, the total CPU time, on the main thread, to fill up the mempool would be:

2000 * 50 = 100000 spend bundle
100000 * 2.1ms = 210s
210s * 21% = 44.1s

# 44.1 seconds

**Review by wjblanke — APPROVED** [review]
aok

**Pull request merged**
