### PR TITLE
separate trusted and non-trusted wallet sync to simplify them a bit

### PR DESCRIPTION
**Pull request by arvidn**
and don't chunk coin states in trusted sync.

### CODE REVIEW

**Comment by mariano54** [comment]
@almogdepaz  is working on a similar change, might want to coordinate.

**Comment by almogdepaz** [comment]
i did some work on this here, also separated the non trusted long vs short sync
https://github.com/Chia-Network/chia-blockchain/pull/12586
maybe you can take a look ?

**Comment by almogdepaz** [comment]
hi @arvidn i did some work on this here
https://github.com/Chia-Network/chia-blockchain/pull/12586
maybe you can take a look ?

**Comment by Gbolahan657** [comment]
If you truly need help contact hackerdecon936@gmail.com

**Pull request closed without merging**
