### PR TITLE
Add support for pending transactions to get_mempool_item_by_tx_id().

### PR DESCRIPTION
**Pull request by rwarren**
The original implementation of `get_mempool_item_by_tx_id()` only gets
transactions that have actually made it into the mempool. Transactions that
have been queued up for the future with `MempoolInclusionStatus.PENDING`
(e.g. those with `ASSERT_HEIGHT_*` conditions) are completely missed by the
function.

Adding the optional `include_pending` argument allows for the retrieval of
these PENDING transactions as well. The default value of `False` ensures that
no old code will have problems.

This change resolves some confusion that can result after pushing a tx with
`push_tx`. It is typical to monitor progress of the transaction by checking
the mempool status with `get_mempool_item_by_tx_id()`... except that PENDING
transactions (that are relegated to `MempoolManager.potential_cache`) were
always reporting back as "not in mempool", even though they are queued up to
potentially enter the mempool in the next round. Code that interpreted "not
in mempool" as a trigger to check `Coin.spent` for included coins to see if
the tx was successful or not would fail in this case. Also worth noting is
that, although `push_tx` returns the `MempoolInclusionStatus` to let you know
that the tx is `PENDING`, there are still timing considerations when polling
to see if the tx is still in the mempool. Detection of mempool presence could
be missed if polling timing is off.  The `include_pending` flag solves all of
these issues since the result can now be interpreted as "waiting for the
mempool to process the tx", whether or not the tx is in the mempool, or
PENDING.

### CODE REVIEW

**Review by Quexington — COMMENTED** [review]
Can you add a couple lines to test this here if possible?: https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/test_full_node_rpc.py

**Comment by rwarren** [comment]
> Can you add a couple lines to test this here if possible?: https://github.com/Chia-Network/chia-blockchain/blob/main/tests/core/test_full_node_rpc.py

I started to have a look at adding some tests, but I can't get the base test to run without pumping out a bunch of warnings and errors (although `py.test` it does say both tests pass).  I'm a bit worried my test env is messed up... not run your tests before.

Is this giant output normal?
https://gist.githubusercontent.com/rwarren/6de2b3ea1a0d92b2ce762b310915f098/raw/0ff9ff44e32b841ea23d39f4e2ba4a315be366a9/gistfile1.txt

**Comment by rwarren** [comment]
Added some basic testing, despite the wall of pre-existing warnings (and a few errors).  Tests still pass.

**Comment by arvidn** [comment]
the issue you're seeing with the tests is that the log handler in the tests always prints logs to the console. So tests that deliberately trigger errors (to make sure they are caught) still print all of those to the console, making it look like the *test* is failing. The trick is to ignore `[ERROR]` and look for `PASSED` and `FAILED` instead.

I'm hoping that, at some point in the future, we can make the log sink print to an internal list and have the test actually ensure only expected errors happened.

**Comment by arvidn** [comment]
> Is this giant output normal?

It's not your fault, and it's not good. but it's not necessarily indicating a bug in production code, just poorly written tests

**Comment by arvidn** [comment]
this patch looks reasonable to me. you need to rebase it now though

**Comment by emlowe** [comment]
We also enable the live log output in pytest by default which results in quite a lot of fluff....
If you want something less chatty - you can try

`pytest -o log_cli=0 -p no:warnings --show-capture=stdout `

**Comment by rwarren** [comment]
Rebased.

**Comment by rwarren** [comment]
Not sure how you want to resolve those conflicts, since it is with a line of code I intentionally left exactly as it was originally.  LGTM analysis failures are driven by that merge conflict.

**Review by Quexington — DISMISSED** [review]
Seems reasonable

**Comment by emlowe** [comment]
close and reopen for new CI run

**Review by emlowe — DISMISSED** [review]

**Comment by wallentx** [comment]
@emlowe @rwarren The first commit in this PR is unsigned 😵‍💫
I tried to interactive rebase to fix it, but the prior rebasing made made my attempt very angry.
I had to create a new branch off main, and apply the diff from this PR (just add `.diff` or `.patch` to the end of a PR URL) to my new branch, which resulted in https://github.com/Chia-Network/chia-blockchain/pull/13976
You can compare the diff of this PR - https://patch-diff.githubusercontent.com/raw/Chia-Network/chia-blockchain/pull/9443.diff
with the diff of my PR - https://patch-diff.githubusercontent.com/raw/Chia-Network/chia-blockchain/pull/13976.diff
I also had to do some trickery to add you and @rwarren as co-author.
We can close this PR out, and resume with the other one, assuming all of the CI passes.

**Comment by rwarren** [comment]
@wallentx  - really not sure why my first commit was not verified. Weird. This is so old I have no memory of state at the time, though. 🤷‍♂️ 

All good with the diff application. Thanks for the trickery effort on maintaining authorship.  A pretty minor change, but appreciated nonetheless. 😄

**Pull request closed without merging**
