### PR TITLE
drop support for database schema v1

### PR DESCRIPTION
**Pull request by arvidn**
This cuts down on the number of test cases we run, and simplifies store classes.

This PR is best reviewed one commit at a time.

### CODE REVIEW

**Comment by arvidn** [comment]
```
chia/full_node/block_height_map.py (93.3%): Missing lines 78
chia/full_node/block_store.py (95.9%): Missing lines 329,358,382
```

**Review by fchirica — DISMISSED** [review]

**Review by fchirica — APPROVED** [review]

**Review by trepca — APPROVED** [review]

**Comment by trepca** [comment]
we might want to provide some instructions for people that upgrade to 2.0 but don't migrate to v2 db

**Comment by arvidn** [comment]
this is going into `main`, so if you're on 2.0 you can still migrate the db. But, yes. upgrading to 2.1 would break it if you're still on v1

**Comment by arvidn** [comment]
we should include these instructions in the 2.0.0 release notes:

```
chia db upgrade --input ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
```

**Pull request merged**
