### PR TITLE
Cleanup sqlite pragmas

### PR DESCRIPTION
**Pull request by arvidn**
* execute the sqlite pragmas only once, at the level where the database is opened
* change pragma synchronous command from `2` to `FULL` to make it clearer what it means. See the sqlite documentation [here](https://sqlite.org/pragma.html#pragma_synchronous).

### CODE REVIEW

**Comment by arvidn** [comment]
the synchronous mode are documented here: https://www.sqlite.org/pragma.html#pragma_synchronous

It says:

> WAL mode is safe from corruption with synchronous=NORMAL

and:

> A transaction committed in WAL mode with synchronous=NORMAL might roll back following a power loss or system crash. Transactions are durable across application crashes regardless of the synchronous setting or journal mode. The synchronous=NORMAL setting is a good choice for most applications running in WAL mode.

**Comment by sh1neryu** [comment]
> 
> 
>     * execute the sqlite pragmas only once, at the lever where the database is opened
> 
>     * change pragma synchronous from FULL (2) to NORMAL. We should not make every DB write pay the cost of protecting against kernel panic or power failure. In those events, the DB can be rebuilt
> 
>     * add comments to coin store about coin_name uniqueness

hello.... in windows 10 user and use GUI minner how can make it happen? thanks

**Comment by Yostra** [comment]
After re-reading the docs, I think we could change sync mode to normal with no worries. This part made me think that: 
``` WAL mode is safe from corruption with synchronous=NORMAL```
Corruption issues with sync mode normal in testnet were prior to switching to WAL mode

**Review by Yostra — APPROVED** [review]

**Review by mariano54 — APPROVED** [review]

**Comment by wjblanke** [comment]
Arvid is this rolled into your recent work? Was about to merge but we wanted to ask

**Comment by arvidn** [comment]
I'm not sure what you mean by "rolled into". I have another patch waiting on this to land, and I think this is still good to land and relevant.

**Pull request merged**
