### PR TITLE
fix typo and index issues in wallet database

### PR DESCRIPTION
**Pull request by arvidn**
This PR addresses the most serious issues raised by @neurosis69 here: https://github.com/Chia-Network/chia-blockchain/issues/10276

it:

* fixed the `PRIMARY_KEY` typo
* introduce a pre-commit check for duplicate index and table names
* deduplicates index names in wallet database ('name', 'wallet_type' and 'wallet_id')

This is the output from the checking script:

```
$ python tests/check_sql_statements.py 
duplicate INDEX "name"
    key_val_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS name on key_val_store(key)")
    wallet_action_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS name on action_queue(name)")
duplicate INDEX "wallet_type"
    wallet_action_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_type on action_queue(wallet_type)")
    wallet_coin_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_type on coin_record(wallet_type)")
duplicate INDEX "wallet_id"
    wallet_action_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_id on action_queue(wallet_id)")
    wallet_coin_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_id on coin_record(wallet_id)")
duplicate INDEX "wallet_type"
    wallet_coin_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_type on coin_record(wallet_type)")
    wallet_puzzle_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_type on derivation_paths(wallet_type)")
duplicate INDEX "wallet_id"
    wallet_coin_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_id on coin_record(wallet_id)")
    wallet_puzzle_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_id on derivation_paths(wallet_id)")
duplicate INDEX "wallet_id"
    wallet_puzzle_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_id on derivation_paths(wallet_id)")
    wallet_transaction_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS wallet_id on transaction_record(wallet_id)")
duplicate INDEX "name"
    wallet_action_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS name on action_queue(name)")
    wallet_user_store.py:        await self.db_connection.execute("CREATE INDEX IF NOT EXISTS name on users_wallets(name)")
```

Duplicate index names will fail to be created for all but the first one.

The wallet store classes are created in this order:

https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/wallet_state_manager.py#L144
```
        self.coin_store = await WalletCoinStore.create(self.db_wrapper)
        self.tx_store = await WalletTransactionStore.create(self.db_wrapper)
        self.puzzle_store = await WalletPuzzleStore.create(self.db_wrapper)
        self.user_store = await WalletUserStore.create(self.db_wrapper)
        self.action_store = await WalletActionStore.create(self.db_wrapper)
        self.basic_store = await KeyValStore.create(self.db_wrapper)
        self.trade_manager = await TradeManager.create(self, self.db_wrapper)
        self.user_settings = await UserSettings.create(self.basic_store)
        self.pool_store = await WalletPoolStore.create(self.db_wrapper)
        self.interested_store = await WalletInterestedStore.create(self.db_wrapper)
```

"name" is created in key_val_store.py, wallet_action_store.py and wallet_user_store.py. WalletUserStore is created first, and won't be created in key_val_store nor wallet_action_store.

"wallet_type" is created in wallet_action_store.py, wallet_coin_store.py and wallet_puzzle_store.py. WalletCoinStore creates it first and won't be created in wallet_puzzle_store nor wallet_action_store.

"wallet_id" is created in wallet_action_store.py, wallet_coin_store.py, wallet_puzzle_store.py and wallet_transaction_store.py. It's first created in WalletCoinStore. It won't be created in wallet_action_store, wallet_puzzle_store nor wallet_transaction_store.

The indexes are renamed according to this reasoning.

### CODE REVIEW

**Comment by mariano54** [comment]
I hope it doesn't trigger some exception when adding duplicates, we should do some manual testing too before release

**Comment by arvidn** [comment]
good point

**Comment by arvidn** [comment]
We should ensure we have tests that exercise duplicate puzzle hashes in this table.

@neurosis69 created a ticket with more comments about the wallet DB, here: https://github.com/Chia-Network/chia-blockchain/issues/10276

**Comment by neurosis69** [comment]
With PR #10139 i proposed a separation of the SQL DDL commands from the other code.
This would make it easier for DB specialists to review the schema code and also easier to see the whole schema at a glance.
@altendky suggested a different way how to use relative directory access, but I wasn't able to implement this right in my PR

**Comment by neurosis69** [comment]
Regarding the tests, not sure if you would like this, but you can also query the database if the schema is correct.
This should also report missing indexes.


Regarding tests.

for instance, in v2  there are 6 coin_record indexes in the wallet db needed. 
the DDLs in a separate file would look like this:
```sql
CREATE INDEX IF NOT EXISTS coin_confirmed_height on coin_record(confirmed_height);
CREATE INDEX IF NOT EXISTS coin_spent_height on coin_record(spent_height);
CREATE INDEX IF NOT EXISTS coin_spent on coin_record(spent);
CREATE INDEX IF NOT EXISTS coin_puzzlehash on coin_record(puzzle_hash);
CREATE INDEX IF NOT EXISTS wallet_type on coin_record(wallet_type);
CREATE INDEX IF NOT EXISTS wallet_id on coin_record(wallet_id);
```

a very simple test would be to compare the statements from aboves DDL script with the indexes in the database.
```sql
SELECT replace(sql, 'CREATE INDEX', 'CREATE INDEX IF NOT EXISTS') 
FROM sqlite_master 
WHERE tbl_name = 'coin_record' AND type = 'index';
```

**Review by mariano54 — APPROVED** [review]
Seems safe enough, as long as we do some full syn tests with it (and we can take advantage and merge a few other things before manual test)

**Pull request merged**
