### PR TITLE
Speed up cli executiong (by import on demand)

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Review by mariano54 — DISMISSED** [review]
LGTM! just need to get tests passing

**Comment by hoffmang9** [comment]
Reopening and moving to target main.

**Comment by justinengland** [comment]
@jespino or @mariano54  can you address these merge conflicts quickly and we can get these merged into main?

**Comment by jespino** [comment]
I can do it tomorrow during my morning like in 10 hours or so.

**Comment by jespino** [comment]
@justinengland done! :)

**Pull request merged**
