### PR TITLE
Add systemd init files to CLI-only Linux packages

### PR DESCRIPTION
**Pull request by TheLastCicada**
### Purpose:
Add Systemd initialization files to the .deb and .rpm CLI-only installers for more friendly process management.  This specifically helps hobby and enterprise users running Chia on a headless Linux server, which a big improvement being the ability to easily start Chia services at boot.  This is currently a pain-point for the Carbon users attempting to install Chia and the carbon applications in their infrastructure.  

These bundled systemd files allow the user to pass in the Linux user that Chia should run as and assumes default ports and locations for the CHIA_ROOT directory.  This likely covers a very large percentage of users and those who need customization can modify their own systemd files.  By passing in the user to the systemd script, multiple versions of Chia could be run on a single system using different Linux user accounts for the CHIA_ROOT.  

### Current Behavior:
No bundled init files.

### New Behavior:
If installed with the CLI .rpm or .deb file, Linux admins will be able to start Chia services with

```
systemctl start chia-full-node@username
systemctl start chia-wallet@username
systemctl start chia-data-layer@username
```

These services will start at boot with the following commands:

```
systemctl enable chia-full-node@username
systemctl enable chia-wallet@username
systemctl enable chia-data-layer@username
```

### CODE REVIEW

**Review by cmmarslender — DISMISSED** [review]

**Review by cmmarslender — APPROVED** [review]

**Review by wjblanke — APPROVED** [review]
aok

**Comment by TCB13** [comment]
I've a question about this PR.

Starting the entire thing required the user to enter a password to unlock the wallet, how will that be handled with this?

Thank you.

**Comment by cmmarslender** [comment]
> I've a question about this PR.
> 
> Starting the entire thing required the user to enter a password to unlock the wallet, how will that be handled with this?
> 
> Thank you.

Currently, the systemd configs are most beneficial to those without password protected keys, or running services that aren't utilizing keys (full node). There are possibly some clever integrations you could come up with that notify you of a need to unlock your keys, but those are a bit out of scope for the current iteration here. 

What I personally do to work around this is and successfully farm on boot is to just leave the keys that my plots are tied to without a password, and have my payout addresses all set to pay to another set of keys that aren't online on the farming host.

**Comment by TCB13** [comment]
@cmmarslender okay... but then this update once it gets released will probably break tons of setups. New systemd services will be installed and automatically try to start a full node / wallet and the process will stay in the background asking for password. Meanwhile a user might run the cli manually and have both instances opening the same database.

How are you planning to handle this?

**Comment by cmmarslender** [comment]
> @cmmarslender ~okay... but then this update once it gets released will probably break tons of setups with a simple apt upgrade.~
> 
> ~New systemd services will be installed and automatically try to start a full node / wallet and the process will stay in the background asking for password. Meanwhile a user might run the cli manually and have both instances opening the same database.~
> 
> ~How are you planning to handle this?~
> 
> Okay I see, you're not enabling those by default.

Correct, not enabled by default. Just there as an option in case you would like to use them with your setup without having to manually create your own systemd configs.

**Pull request merged**
