### PR TITLE
retryAfter: 5 (24x) for conflict check

### PR DESCRIPTION
**Pull request by altendky**
I don't really know how long the `UNKNOWN` mergeability state usually takes to resolve but that is the trigger for the 120 second delays on each PR in that state.  This can be seen if you look through the action source and run the workflow with debug enabled.  I don't believe I've seen it rerun more than one out of the 5 (at least default) retries.  I propose this 2 second retry to start and see how it goes.  Unless it repeats multiple times this should induce no extra load in terms of queries and will reduce runner load by not having the runner sitting there doing nothing for two minutes.

```
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]{
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  "mergeable": "UNKNOWN",
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  "number": 13389,
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  "permalink": "https://github.com/Chia-Network/chia-blockchain/pull/13389",
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  "title": "Delete DID wallet after transfer",
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  "updatedAt": "2022-09-09T16:29:20Z",
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  "labels": {
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]    "nodes": []
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]  }
Sun, 11 Sep 2022 14:30:48 GMT
##[debug]}
Sun, 11 Sep 2022 14:30:48 GMT
for PR "Delete DID wallet after transfer": Retrying after 120s.
Sun, 11 Sep 2022 14:32:48 GMT
retrying with 5 retries remaining.
```

Draft for:
- [x] Consideration of actual retry behavior
- [x] Seeing if https://github.com/Chia-Network/chia-blockchain/pull/13424 fixes it with the new retry logic

### CODE REVIEW

**Comment by altendky** [comment]
@alexciesielski, I saw your issue report over at https://github.com/eps1lon/actions-label-merge-conflict/issues/84 and it seemed like we may be having the same trouble.  I believe there isn't anything particularly wrong except that the 120 second default retry delay might be longer than we need.  That said, I don't actually know how long the `UNKNOWN` state generally lasts.  We'll see if I can get some data here in this repo.  It looks like maybe newer versions of the API (?) use an optional boolean instead (true, false, or null).  https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request

**Comment by altendky** [comment]
I'll leave this running (fish, not bash) for awhile and see if i can get any data on the 'normal' duration of the unknown mergeability state.

```fish
while true; date --iso-8601=s; gh api graphql -F owner='chia-network' -F repo='chia-blockchain' -F baseRefName='main' -f query='query openPullRequests($owner: String!, $repo: String!, $after: String, $baseRefName: String) { 
                         repository(owner:$owner, name: $repo) { 
                           pullRequests(first: 100, after: $after, states: OPEN, baseRefName: $baseRefName) {
                             nodes {
                               mergeable
                               number
                               permalink
                               title
                               updatedAt
                               labels(first: 100) {
                                 nodes {
                                   name
                                 }
                               }
                             }
                             pageInfo {
                               endCursor
                               hasNextPage
                             }
                           }
                         }
                       }' | jq '.data.repository.pullRequests.nodes[] | select(.mergeable=="UNKNOWN")'; sleep 10; end
```

**Comment by alexciesielski** [comment]
After being rejected so nicely by the actions author I looked into it a bit more.

Being informed about your PR being conflicted (which was the whole reason for seeking out this action) is possible natively in Github under your profiles settings, maybe you will find it useful too.

**Comment by altendky** [comment]
Thanks for the heads up.  I looked around a bit but haven't found that setting yet.  Which section is it in?

If I can collect some data on how long they stay unknown I may propose a change to the default.

**Comment by alexciesielski** [comment]
https://github.com/settings/reminders

Select your org and enable real-time reminders > Select "Your PR has merge conflicts"

**Comment by altendky** [comment]
Found it, thanks.  Though that appears to be a slack integration feature.

> Receive immediate Slack messages when certain events happen

image

**Comment by altendky** [comment]
I've seen a few cases so far of the unknown status.  One of them was three requests in a row as such with the 10 second delay between them.  At this point I would probably like to target a total retry window of two minutes.  It would be nice to have exponential backoff, but let's go with 5 second retry delay and 24 attempts to get to two minutes.

**Comment by altendky** [comment]
Now that I think about it I'm a bit concerned about whether the retry is working properly.  It feels kind of like a bulk request is made, some are unknown, we iterate through the initial response and if unknown then we wait the retry period and then end up passing.  But the next one fails too as if it is maybe still using the original request data.

Also, we're on v2.0.0 and v2.0.1 says "Improve retry logic".  https://github.com/eps1lon/actions-label-merge-conflict/compare/v2.0.0..v2.0.1  Let's try that first.  https://github.com/Chia-Network/chia-blockchain/pull/13424

**Comment by altendky** [comment]
Yeah, even on that last build one of the runs (should we apply normal build triggers here?) still took 14 minutes with some failures in there.

https://github.com/Chia-Network/chia-blockchain/runs/8295607294?check_suite_focus=true#step:2:455
```
for PR "Delete DID wallet after transfer": Retrying after 120s.
retrying with 5 retries remaining.
for PR "[Draft] Retry network requests infinitely if trusted sync": Retrying after 120s.
retrying with 5 retries remaining.
for PR "util: Remove legacy keyring support": Retrying after 120s.
retrying with 5 retries remaining.
for PR "Heap profiler": Retrying after 120s.
retrying with 5 retries remaining.
for PR "separate process global setup for daemon": Retrying after 120s.
retrying with 5 retries remaining.
for PR "run expensive API requests in separate thread": Retrying after 120s.
retrying with 5 retries remaining.
for PR "farm fewer blocks for wallet offer tests": remove "merge_conflict"
Issue #13413 does not have label 'merge_conflict'. No need to remove.
for PR "set segment download timeout for cache action steps": Retrying after 120s.
retrying with 5 retries remaining.
for PR "retryAfter: 2 for conflict check": remove "merge_conflict"
Issue #13422 does not have label 'merge_conflict'. No need to remove.
for PR "Ms.no hang - core 60x": remove "merge_conflict"
Issue #13423 does not have label 'merge_conflict'. No need to remove.

**Review by cmmarslender — DISMISSED** [review]

**Comment by ChiaMineJP** [comment]
@altendky @cmmarslender 
Please defer merging this PR.
See this PR: https://github.com/Chia-Network/actions/pull/43

**Comment by ChiaMineJP** [comment]
https://github.com/Chia-Network/chia-blockchain/actions/runs/3091131663/jobs/5000827353
Removing conflict label has been success!
Seams ready to replace the conflict check action.

**Review by cmmarslender — APPROVED** [review]

**Review by emlowe — APPROVED** [review]

**Pull request merged**
