### PR TITLE
Before calling gethostbyname(); check if host is an address

### LINKED ISSUE #8565: [BUG] Cannot use IPv6 for remote harvester or between any Chia services
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8552

<div type='discussions-op-text'>

<sup>Originally posted by **cross** September 21, 2021</sup>
chia-blockchain 1.2.3, Ubuntu 20.  installed from the .deb distribution here.

I have a harvester I'm trying to connect to a farmer peer in the same building.  I have other harvesters connected via IPv4.  This newest harvester is on a segmented IPv4 network, so I'm specifying the IPv6 address of the farmer as follows in my config.yml:

```
harvester:
  chia_ssl_ca:
    crt: config/ssl/ca/chia_ca.crt
    key: config/ssl/ca/chia_ca.key
  farmer_peer:
    host: 2000:3000:4000:5000::101
    port: 8447
  logging: *id001
  network_overrides: *id002
```

But, when I start `chia start harvester -r` the following appears on my terminal:
 
```
chia_harvester: started
user@host:~$ Traceback (most recent call last):
  File "chia/server/start_harvester.py", line 57, in <module>
  File "chia/server/start_harvester.py", line 53, in main
  File "chia/server/start_service.py", line 255, in run_service
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "chia/server/start_service.py", line 249, in async_run_service
  File "chia/server/start_service.py", line 171, in run
  File "chia/server/start_service.py", line 145, in start
  File "chia/server/start_service.py", line 146, in <listcomp>
  File "chia/server/reconnect_task.py", line 12, in start_reconnect_task
socket.gaierror: [Errno -9] Address family for hostname not supported
[1752] Failed to execute script start_harvester
```

Do I have the syntax wrong, or does IPv6 connections to farmer have an issue?

(`netstat -an | grep 8447` on the farmer shows `tcp6       0      0 :::8447                 :::*                    LISTEN` amongst `tcp LISTEN` and ESTABLISHED connections via IPv4.  And I've verified I can establish the tcp connection using `telnet` to that IPv6 address, port 8447.)</div>

### PR DESCRIPTION
**Pull request by cross**
That prevents an unnecessary call, and also allows for specifying IPv6
addresses which otherwise cause exceptions here.

### CODE REVIEW

**Comment by jack60612** [comment]
I think a timelord is unnecessary

**Comment by cross** [comment]
> The current state of the art Timelord is three rocketlakes. It would be much improved to be able to address the vdf_clients directly via IPv6 on the local network too.

Yup.  IPv6 capability needs to be added in a more complete way throughout, but this was just to allow IPv6 addresses in the config.  If the code in timelord would also benefit from that, we can use PeerInfo.is_valid() too, but it would require constructing a PeerInfo for only that reason.  Happy to code it if we think that's "a good thing."

**Review by emlowe — DISMISSED** [review]
Looks good to me as a stop-gap measure. Allows entering IPv6 addresses directly into config.yaml. Does not address resolving to IPv6 - hostnames in config.yaml will still resolve to IPv4.

**Review by jack60612 — APPROVED** [review]
lgtm as a stop gap measure as @emlowe mentioned above.

**Review by jack60612 — CHANGES_REQUESTED** [review]
You did not import peerinfo for the timelord file

**Review by jack60612 — DISMISSED** [review]
LGTM

**Comment by cross** [comment]
> `pip install mypy` and then `mypy chia/timelord/timelord_launcher.py` is the quick and dirty way. There is a hook that will run them all if you want to go all in on that.

Thanks.  That found one more (that I missed because in C/C++, importing peer_info would've brought int uint16, but that doesn't work in python).  I'd be curious to know how to run all of the tests, at least the ones relevant to my Ubuntu python3 platform.  But this should get past lint/mypy now.  :-)

**Comment by emlowe** [comment]
Generally, locally one can use flake8, black, and mypy (pip install all those).
Then you run them manually if you want.
However, you can also setup vscode to do it, (or use pycharm). You set `black` as the python formatter and configure flake8 and mypy as the linters.

**Review by hoffmang9 — APPROVED** [review]
lgtm, thank you, and congrats on your first Chia PR!

**Pull request merged**
