### PR TITLE
Derivation from just a master public key

### PR DESCRIPTION
**Pull request by Yostra**

### CODE REVIEW

**Comment by mariano54** [comment]
What's the purpose of this change?

**Review by wjblanke — APPROVED** [review]
be sure to try show all keys

**Comment by xdustinface** [comment]
> To be able to derive wallet public keys from just root public key (no sk).

@Yostra But whats the point about adding this in `cmds/key_funcs.py`, where it now calculated a redundant address just to assert its the same and then not even use it? This should rather be properly tested in some test.

**Comment by mariano54** [comment]
This will fail for non observer derivation
This change should be reverted unless I'm missing something

**Comment by mariano54** [comment]
@wjblanke

**Pull request merged**
