### PR TITLE
remove proofs from unsampled segments

### PR DESCRIPTION
**Pull request by almogdepaz**
remove vdf proofs from segments that are not sampled

### CODE REVIEW

**Review by hoffmang9 — DISMISSED** [review]
+1

**Review by mariano54 — COMMENTED** [review]
Big change.. We need to test this with all the sub-epochs in the chain and see if it works. It is a good change and it could help a lot in reducing timeouts

**Comment by almogdepaz** [comment]
@mariano54 i agree with, i haven't had time to do any network testing for this yet 
we should leave it out 
also we are lowering the sample count going back to a size we know works

**Comment by justinengland** [comment]
can you please resubmit this PR to either main, or if it needs to be merged before 3/24/21, new-main, this will allow us to move forward with the new git branching strategy

**Pull request closed without merging**
