### PR TITLE
Rename `src` to `chia`.

### PR DESCRIPTION
**Pull request by richardkiss**

### CODE REVIEW

**Comment by richardkiss** [comment]
This change is quite a nightmare. Want to keep it on your radar @mariano54 & @hoffmang9.

Rebasing shouldn't actually be too hard. Recreating from scratch is pretty easy with `sed`.

I think doing it before 1.1.0 ships makes sense.

**Comment by hoffmang9** [comment]
I already peeked and went, "that's going to hurt but best to get it done for 1.1."

**Comment by mariano54** [comment]
Sure, I'm down to merge this soon. Some things we need to check:
- All of the commands work properly
- UI launches and works properly

**Comment by richardkiss** [comment]
Rebased.

**Comment by richardkiss** [comment]
Dup of https://github.com/Chia-Network/chia-blockchain/pull/1673

**Pull request closed without merging**
