### PR TITLE
Don't retry respond_peers message

### PR DESCRIPTION
**Pull request by mariano54**

### CODE REVIEW

**Review by arvidn — APPROVED** [review]
looks good. All I'm missing is the rationale to not retry `respond_peers` message

**Comment by mariano54** [comment]
We are trying to broadcast more peers / min than the actual rate limit (which is 10 per minute). Rate limits are multiplied by 0.4 when we rate limit our own outgoing messages, so that would be max 4 per minute. 

Before 1.1.2, there was no retrying, so if we sent to much they were just discarded. Now we are adding these messages to the queue over and over and the queue is not getting cleared fast enough, so the connection closes.

**Comment by tedshroyer** [comment]
@hoffmang9 / @mariano54 should I close #3474 and open a bug instead for finding a long term solution?

**Comment by arvidn** [comment]
I believe this issue in the rate limiter contributed to this problem, by pushing out and blocking other message types. https://github.com/Chia-Network/chia-blockchain/pull/3518

It's probably a good idea to create a ticket for coming up with a long term solution to this. I imagine part of that is improving the rate limiter some as well (and hopefully simplify it).

**Pull request merged**
