### PR TITLE
Exclude Files created by wheel.

### PR DESCRIPTION
**Pull request by jack60612**
Increases sanity.

### CODE REVIEW

**Comment by altendky** [comment]
Could we exclude the entire build directory?

**Comment by jack60612** [comment]
> Could we exclude the entire build directory?

Assumed you would want this but sure can do

**Comment by jack60612** [comment]
> > Could we exclude the entire build directory?
> 
> Assumed you would want this but sure can do

Oh wait confused the directories, sorry about that.

**Review by altendky — APPROVED** [review]
It looks like we have a mess of different places we build stuff, but when I `venv/bin/python -m build --wheel .` I do get a `build/` directory and that should be ignored.  Thanks.

**Pull request merged**
