### PR TITLE
refactor: Rename folder `tests/core/types` to `tests/core/custom_types`

### PR DESCRIPTION
**Pull request by xdustinface**
Seems like the name `types` in the folder conflicts there with some python standard stuff because i just can't get the debugger in PyCharm to work without this renaming. Instantly getting the following error:

```
ImportError: cannot import name 'MappingProxyType' from 'types'
(/home/me/chia/chia-blockchain/tests/core/types/__init__.py)
Traceback (most recent call last):
  File
"/snap/pycharm-professional/248/plugins/python/helpers/pydev/pydevd.py",
line 8, in <module>
    from contextlib import contextmanager
  File "/usr/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from 'types'
(/home/me/chia/chia-blockchain/tests/core/types/__init__.py)
```

If someone has an idea how else to fix this please tell me!

### CODE REVIEW

**Review by mariano54 — APPROVED** [review]

**Comment by aqk** [comment]
Good catch. Too bad pycharm has this weakness.
Pycharm+pytest has a few other quirks, too, unfortunately.

The only thing I want to point out is: make sure to run:
```
cd tests
python ./build-workflows.py
```
to make sure that still produces the workflows you want.

btw, for patches involving Python stdlib, @richardkiss is an excellent choice for reviewer.

**Comment by xdustinface** [comment]
> The only thing I want to point out is: make sure to run:
> 
> ```
> cd tests
> python ./build-workflows.py
> ```

I actually did run this, see this commit and its commit message https://github.com/Chia-Network/chia-blockchain/pull/7852/commits/b61ce04933b5f1367bfd2009e418437ef20abf2b :)

The weird thing is, it also added wallet-did tests.. they failed though so i dropped them with the last [force-push]( https://github.com/Chia-Network/chia-blockchain/compare/0bc4d24a9c0e53250a1d5ea5767fed7225f0e44d..b61ce04933b5f1367bfd2009e418437ef20abf2b) since they obviously also weren't in there before. If they should be included i guess they should be fixed and added in a separate PR? 

> btw, for patches involving Python stdlib, @richardkiss is an excellent choice for reviewer.

Okay cool, so maybe you have an idea here @richardkiss? @mariano54 said he can debug with this folder named `type` so its probably only some weirdness on my system although we have the same Ubuntu and PyCharm versions :see_no_evil:

**Comment by aqk** [comment]
Okay, great - I'll talk to Matt & to check if it's okay to drop the did tests for now, and put in a PR for that.

**Comment by aqk** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/7862/files

**Pull request merged**
