### PR TITLE
Remote daemon

### PR DESCRIPTION
**Pull request by dkackman**
This PR modifies the electron app such that it can connect to a daemon running somewhere other than `localhost`.

Of note:
- the regular `config.yaml` file is used to locate the daemon
   - the `self_hostname`, `daemon_port` and `ssl` sections are used to find and secure the wss connection
   - the remote daemon must be reachable at `wss://<self_hostname>:<daemon_port>`
- both the UI and daemon must share trusted certs
- the config file is located based on the version placed in `package.json` by the build OR in the source tree during development. _Not sure this will work in all scenarios so that could use particular review_
- The code will not attempt to start or stop the daemon if it is not at `localhost`
- I didn't change the code that gets the cert paths from the locally hosted daemon via `websocket`. That code path can probably be removed and just rely on the config file (where the python gets it anyway) but I didn't want to perturb that for the time being

### CODE REVIEW

**Comment by Yostra** [comment]
Closing until SSD changes are done, I'll reopen when done.

**Comment by hoffmang9** [comment]
@dkackman Can you rebase at your convenience?

**Comment by dkackman** [comment]
> 
> 
> @dkackman Can you rebase at your convenience?

Looks like my branch has become irreconcilable to the current dev. I'm going to close this PR, re-fork and create a new PR.

**Comment by hoffmang9** [comment]
Sorry about that as it's totally my bad.

**Comment by dkackman** [comment]
> 
> 
> Sorry about that as it's totally my bad.

No worries. Nothing a little WinMerge can't handle.

**Pull request closed without merging**
