### PR TITLE
Add a config option for peer_connect_timeout

### PR DESCRIPTION
**Pull request by cmmarslender**

### CODE REVIEW

**Review by hoffmang9 — DISMISSED** [review]
lgtm

**Review by hoffmang9 — DISMISSED** [review]
nice add

**Review by hoffmang9 — DISMISSED** [review]
still ok

**Review by jack60612 — DISMISSED** [review]

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Review by jack60612 — APPROVED** [review]

**Pull request merged**
