### PR TITLE
Remove duplicate '-e' command line flag in 'chia wallet send'

### PR DESCRIPTION
**Pull request by aqk**

### CODE REVIEW

**Review by arvidn — COMMENTED** [review]
my main comment is: is this the right `-e` to remove, or should the one associated with `--exclude-coin` be removed instead? The latter seems newer, but I could be wrong. Maybe the final state is better to allow excluding with a short option.

**Review by arvidn — APPROVED** [review]
you should give this PR a more specific title, since it will be part of the changelog

**Comment by aqk** [comment]
I think we should remove many more of the single-letter flags.

**Comment by aqk** [comment]
> my main comment is: is this the right `-e` to remove, or should the one associated with `--exclude-coin` be removed instead? The latter seems newer, but I could be wrong. Maybe the final state is better to allow excluding with a short option.

I think '-e' fits much better for exclude. I think we should remove all the single-letter options that are not clear.

**Comment by aqk** [comment]
> you should give this PR a more specific title, since it will be part of the changelog

Done, thanks!

**Comment by emlowe** [comment]
This is fixed by https://github.com/Chia-Network/chia-blockchain/pull/14100 - which is already merged, so closing this PR

**Pull request closed without merging**
