### PR TITLE
Update show.py

### PR DESCRIPTION
**Pull request by kd637xx**
Correctly show up/down for all types of nodes.

**just caught my eye, browsing the code; didn't test**

### CODE REVIEW

**Comment by hoffmang9** [comment]
This was literally just fixed yesterday in dev - https://github.com/Chia-Network/chia-blockchain/commit/cbf2c575a57ea87a8b17227d7ed53f54f7407e1d#diff-7e1e45639ce4d0c6267406d773a4f46ac6ca24dc7197d06a536721cee01efe25

But thanks very much for the PR.

**Comment by kd637xx** [comment]
Yes, but mine fixes line https://github.com/Chia-Network/chia-blockchain/commit/cbf2c575a57ea87a8b17227d7ed53f54f7407e1d#diff-7e1e45639ce4d0c6267406d773a4f46ac6ca24dc7197d06a536721cee01efe25L229

**Comment by hoffmang9** [comment]
Indeed. Thanks! There is one nit that I'll just fix once this is merged. the > needs to be in the other column to align everything correctly I believe.

**Comment by hoffmang9** [comment]
And I take that back - you have it correct.

**Comment by kd637xx** [comment]
No prob. Thank you!

**Pull request merged**
