### PR TITLE
Verify RPC in full node

### PR DESCRIPTION
**Pull request by freddiecoleman**
**Why?**

* To make it simple to verify pool owners.
* By adding it as a RPC other people can benefit from the feature as well.

This will make it possible to do things like this where the pool owner is able to set it up themselves.

pool-tags

**Manual tests**

Valid

```bash
(venv) ubuntu@ip-172-26-6-102:~/.chia/beta-1.0b28.dev6/config/ssl/full_node$ curl -k --key private_full_node.key --cert private_full_node.crt -X POST  -d '{ "message": 
"hello", "public_key": "820e3f84e1368deab22350e6f500bc50726cb9b7c1c3be215996c77be029843b790381f9b0925a68cd23dbaebd8eadb3", "signature": "ab91e486c838186cc0f096239a04efd
b8cbbf9853920fb4f3254591c7c957598e58aab5e0ac04a76f63d0007ebcbcc730c6bb0251d972423f532e4cacca79f19081fd818d28dcf6d1ef122cfa4c8644e35e3ebf94aae89d73eafe5ecc350cc73"  }' h
ttps://localhost:8555/verify | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   378  100    32  100   346   1391  15043 --:--:-- --:--:-- --:--:-- 16434
{
  "success": true,
  "valid": true
}
```

Invalid

```bash
(venv) ubuntu@ip-172-26-6-102:~/.chia/beta-1.0b28.dev6/config/ssl/full_node$ curl -k --key private_full_node.key --cert private_full_node.crt -X POST  -d '{ "message": 
"goodbye", "public_key": "820e3f84e1368deab22350e6f500bc50726cb9b7c1c3be215996c77be029843b790381f9b0925a68cd23dbaebd8eadb3", "signature": "ab91e486c838186cc0f096239a04e
fdb8cbbf9853920fb4f3254591c7c957598e58aab5e0ac04a76f63d0007ebcbcc730c6bb0251d972423f532e4cacca79f19081fd818d28dcf6d1ef122cfa4c8644e35e3ebf94aae89d73eafe5ecc350cc73"  }'
 https://localhost:8555/verify | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   381  100    33  100   348   1434  15130 --:--:-- --:--:-- --:--:-- 16565
{
  "success": true,
  "valid": false
}
```

### CODE REVIEW

**Comment by mariano54** [comment]
chia keys sign and 
chia keys verify
serve this purpose. Is there a reason why it's better to have this as an RPC as opposed to just command line tool?

**Comment by freddiecoleman** [comment]
> chia keys sign and
> chia keys verify
> serve this purpose. Is there a reason why it's better to have this as an RPC as opposed to just command line tool?

It just provides a way to do it over HTTP without dependency on python etc. You could argue it's not really the responsibility of the full node to provide this and I can just lift and shift this and wrap with a HTTP API in my own code.

**Comment by mariano54** [comment]
OK I understand the reason now. However I think it's not the responsibility of the node to do this, and I think having js bindings for blspy would be the better way to do it. (we had js bindings but they are outdated now).

Also if you use blspy directly, you don't have to make an http call.

**Comment by freddiecoleman** [comment]
> OK I understand the reason now. However I think it's not the responsibility of the node to do this, and I think having js bindings for blspy would be the better way to do it. (we had js bindings but they are outdated now).
> 
> Also if you use blspy directly, you don't have to make an http call.

That sounds great and I agree would be better so will close this. Thanks for the feedback.

**Pull request closed without merging**
